import fs from 'fs/promises';

import { LlmRouter, LlmProvider } from '../llm';
import { AssistantStrategy } from './strategies/model';
import { AssistantSource } from './source';
import { Assistant } from './index';

import * as strategies from './strategies';

/* Generated by @n1k1t/unit-generator */
it('should return spent time when status is PREPARING', () => {
  const mockSource = {
    timestamp: Date.now() - 5000,
  } as unknown as AssistantSource;
  const mockStrategy = {
    on: jest.fn(),
  } as unknown as AssistantStrategy;
  const assistant = new Assistant(mockSource, [mockStrategy], {
    cwd: '/cwd',
    provider: {} as any,
    target: 0.8,
    iterations: 3,
  });
  assistant.status = 'PREPARING';
  expect(assistant.calculateTimeSpent()).toBe(0);
});

/* Generated by @n1k1t/unit-generator */
it('should return difference between now and source timestamp when status is GENERATION', () => {
  const mockSource = {
    timestamp: Date.now() - 5000,
  } as unknown as AssistantSource;
  const mockStrategy = {
    on: jest.fn(),
  } as unknown as AssistantStrategy;
  const assistant = new Assistant(mockSource, [mockStrategy], {
    cwd: '/cwd',
    provider: {} as any,
    target: 0.8,
    iterations: 3,
  });
  assistant.status = 'PENDING';
  expect(assistant.calculateTimeSpent()).toBeGreaterThanOrEqual(4900);
});

/* Generated by @n1k1t/unit-generator */
it('should call fs.rm when clear is called', async () => {
  const rmSpy = jest.spyOn(fs, 'rm').mockResolvedValue(undefined);
  const mockSource = {
    temp: '/tmp/test-temp',
    spec: {
      content: 'some content',
      remove: jest.fn().mockResolvedValue(undefined),
    },
  } as unknown as AssistantSource;
  const mockStrategy = {
    on: jest.fn(),
  } as unknown as AssistantStrategy;
  const assistant = new Assistant(mockSource, [mockStrategy], {
    cwd: '/cwd',
    provider: {} as any,
    target: 0.8,
    iterations: 3,
  });
  await assistant.clear();
  expect(rmSpy).toHaveBeenCalledWith('/tmp/test-temp', {
    recursive: true,
    force: true,
  });
  rmSpy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should call spec.remove when clear is called and spec content is empty', async () => {
  const rmSpy = jest.spyOn(fs, 'rm').mockResolvedValue(undefined);
  const removeMock = jest.fn().mockResolvedValue(undefined);
  const mockSource = {
    temp: '/tmp/test-temp',
    spec: {
      content: '',
      remove: removeMock,
    },
  } as unknown as AssistantSource;
  const mockStrategy = {
    on: jest.fn(),
  } as unknown as AssistantStrategy;
  const assistant = new Assistant(mockSource, [mockStrategy], {
    cwd: '/cwd',
    provider: {} as any,
    target: 0.8,
    iterations: 3,
  });
  await assistant.clear();
  expect(removeMock).toHaveBeenCalled();
  rmSpy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should not call spec.remove when clear is called and spec content is not empty', async () => {
  const rmSpy = jest.spyOn(fs, 'rm').mockResolvedValue(undefined);
  const removeMock = jest.fn().mockResolvedValue(undefined);
  const mockSource = {
    temp: '/tmp/test-temp',
    spec: {
      content: 'some content',
      remove: removeMock,
    },
  } as unknown as AssistantSource;
  const mockStrategy = {
    on: jest.fn(),
  } as unknown as AssistantStrategy;
  const assistant = new Assistant(mockSource, [mockStrategy], {
    cwd: '/cwd',
    provider: {} as any,
    target: 0.8,
    iterations: 3,
  });
  await assistant.clear();
  expect(removeMock).not.toHaveBeenCalled();
  rmSpy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should complete immediately if coverage is reached and status is DONE', async () => {
  const mockSource = {
    checkHasReachedCoverage: jest.fn().mockReturnValue(true),
    temp: '/tmp/test-temp',
    spec: {
      content: 'some content',
      remove: jest.fn(),
    },
  } as unknown as AssistantSource;
  const mockStrategy = {
    on: jest.fn(),
  } as unknown as AssistantStrategy;
  const assistant = new Assistant(mockSource, [mockStrategy], {
    cwd: '/cwd',
    provider: {} as any,
    target: 0.8,
    iterations: 3,
  });
  assistant.status = 'COMPLETED';
  const clearSpy = jest.spyOn(assistant, 'clear').mockResolvedValue(undefined);
  await assistant.run();
  expect(assistant.status).toBe('COMPLETED');
  clearSpy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should skip strategies not in context.strategies list', async () => {
  const mockSource = {
    checkHasReachedCoverage: jest.fn().mockReturnValue(false),
    refresh: jest.fn(),
    compileSnapshot: jest.fn().mockReturnValue({
      cobertura: { rate: 0.5, uncovered: [] },
      spec: { content: '' },
    }),
    temp: '/tmp/test-temp',
    spec: {
      content: 'some content',
      remove: jest.fn(),
      pretty: jest.fn().mockResolvedValue(undefined),
    },
  } as unknown as AssistantSource;
  const mockStrategy1 = {
    name: 'strategy-1',
    on: jest.fn(),
    run: jest.fn().mockResolvedValue('DONE'),
  } as unknown as AssistantStrategy;
  const mockStrategy2 = {
    name: 'strategy-2',
    on: jest.fn(),
    run: jest.fn().mockResolvedValue('DONE'),
  } as unknown as AssistantStrategy;
  const assistant = new Assistant(mockSource, [mockStrategy1, mockStrategy2], {
    cwd: '/cwd',
    provider: {} as any,
    target: 0.8,
    iterations: 1,
    strategies: ['strategy-2'],
  });
  const clearSpy = jest.spyOn(assistant, 'clear').mockResolvedValue(undefined);
  await assistant.run(1);
  expect(mockStrategy1.run).not.toHaveBeenCalled();
  clearSpy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should complete if all strategies are skipped', async () => {
  const mockSource = {
    checkHasReachedCoverage: jest.fn().mockReturnValue(false),
    refresh: jest.fn(),
    compileSnapshot: jest.fn().mockReturnValue({
      cobertura: { rate: 0.5, uncovered: [] },
      spec: { content: '' },
    }),
    temp: '/tmp/test-temp',
    spec: {
      content: 'some content',
      remove: jest.fn(),
    },
  } as unknown as AssistantSource;
  const mockStrategy = {
    name: 'strategy-1',
    on: jest.fn(),
    run: jest.fn().mockResolvedValue('SKIPPED'),
  } as unknown as AssistantStrategy;
  const assistant = new Assistant(mockSource, [mockStrategy], {
    cwd: '/cwd',
    provider: {} as any,
    target: 0.8,
    iterations: 1,
    strategies: ['strategy-1'],
  });
  const clearSpy = jest.spyOn(assistant, 'clear').mockResolvedValue(undefined);
  await assistant.run(1);
  expect(assistant.status).toBe('COMPLETED');
  clearSpy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should update state action when strategy emits tool event', () => {
  const mockSource = {} as unknown as AssistantSource;
  const listeners: Record<string, Function> = {};
  const mockStrategy = {
    on: jest.fn((event, cb) => {
      listeners[event] = cb;
    }),
  } as unknown as AssistantStrategy;
  const assistant = new Assistant(mockSource, [mockStrategy], {
    cwd: '/cwd',
    provider: {} as any,
    target: 0.8,
    iterations: 3,
  });
  listeners['tool']({ iteration: 1, name: 'test-tool', status: 'OK' });
  expect(assistant.state.action).toEqual({
    type: 'tool',
    status: 'OK',
    message: '[1] test-tool',
  });
});

/* Generated by @n1k1t/unit-generator */
it('should register once listener and trigger it only once', () => {
  const mockSource = {
    checkHasReachedCoverage: jest.fn().mockReturnValue(false),
    compileSnapshot: jest.fn().mockReturnValue({
      cobertura: { rate: 0.5, uncovered: [] },
      spec: { content: '' },
    }),
    temp: '/tmp/test-temp',
    spec: {
      content: 'some content',
      remove: jest.fn(),
    },
  } as unknown as AssistantSource;
  const mockStrategy = {
    name: 'strategy-1',
    on: jest.fn(),
    run: jest.fn().mockResolvedValue('DONE'),
  } as unknown as AssistantStrategy;
  const assistant = new Assistant(mockSource, [mockStrategy], {
    cwd: '/cwd',
    provider: {} as any,
    target: 0.8,
    iterations: 2,
  });
  const clearSpy = jest.spyOn(assistant, 'clear').mockResolvedValue(undefined);
  const stepListener = jest.fn();
  assistant.once('step', stepListener);
  (assistant as any).register({
    status: 'DONE',
    snapshot: {},
    strategy: 'strategy-1',
    iteration: 1,
  });
  (assistant as any).register({
    status: 'DONE',
    snapshot: {},
    strategy: 'strategy-1',
    iteration: 2,
  });
  expect(stepListener).toHaveBeenCalledTimes(1);
  clearSpy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should build Assistant instance with correct strategies and context', async () => {
  const mockSource = {} as unknown as AssistantSource;
  const sourceBuildSpy = jest.spyOn(AssistantSource, 'build').mockResolvedValue(mockSource);
  const mockProvider = {} as unknown as LlmProvider;
  const mockRouter = {
    provide: jest.fn().mockReturnValue(mockProvider),
  };
  const routerBuildSpy = jest.spyOn(LlmRouter, 'build').mockReturnValue(mockRouter as any);
  const mockInitStrategy = { on: jest.fn() } as any;
  const mockAddStrategy = { on: jest.fn() } as any;
  const mockFixStrategy = { on: jest.fn() } as any;
  const initBuildSpy = jest.spyOn(strategies.AssistantInitStrategy, 'build').mockReturnValue(mockInitStrategy);
  const addBuildSpy = jest.spyOn(strategies.AssistantAddStrategy, 'build').mockReturnValue(mockAddStrategy);
  const fixBuildSpy = jest.spyOn(strategies.AssistantFixStrategy, 'build').mockReturnValue(mockFixStrategy);
  const assistant = await Assistant.build('some/location', {
    cwd: '/cwd',
    target: 0.9,
    iterations: 5,
    strategies: ['AssistantInitStrategy'],
  });
  expect(assistant.context).toEqual({
    cwd: '/cwd',
    provider: mockProvider,
    target: 0.9,
    iterations: 5,
    strategies: ['AssistantInitStrategy'],
  });
  sourceBuildSpy.mockRestore();
  routerBuildSpy.mockRestore();
  initBuildSpy.mockRestore();
  addBuildSpy.mockRestore();
  fixBuildSpy.mockRestore();
});
