import fs from 'fs/promises';
import path from 'path';
import { AssistantSource } from './source';
import * as strategies from './strategies';
import { Assistant } from './index';

/* Generated by @n1k1t/unit-generator */
it('should initialize with provided source, strategies, and options', () => {
  const mockSource = {};
  const mockStrategies = [] as any;
  const mockOptions = { model: 'gpt-4' };

  const assistant = new Assistant(mockSource as any, mockStrategies as any, mockOptions);

  expect(assistant.source).toBe(mockSource);
  expect(assistant.strategies).toBe(mockStrategies);
  expect(assistant.options).toBe(mockOptions);
  expect(assistant.timestamp).toBeDefined();
  expect(assistant.steps).toEqual([]);
  expect(assistant.state).toEqual({ strategy: 'NONE', status: 'PREPARING' });
});

/* Generated by @n1k1t/unit-generator */
it('should return spent time if status is COMPLETED', () => {
  const assistant = new Assistant({} as any, []);
  assistant.state.status = 'COMPLETED';
  (assistant as any)['spent'] = 1000;

  expect(assistant.calculateTimeSpent()).toEqual(1000);
});

/* Generated by @n1k1t/unit-generator */
it('should return current elapsed time if status is not COMPLETED', () => {
  const assistant = new Assistant({} as any, []);
  assistant.timestamp = Date.now() - 5000;
  assistant.state.status = 'PREPARING';

  const timeSpent = assistant.calculateTimeSpent();
  expect(timeSpent).toBeGreaterThanOrEqual(5000);
  expect(timeSpent).toBeLessThan(5100);
});

/* Generated by @n1k1t/unit-generator */
it('should register an event listener with on method', () => {
  const assistant = new Assistant({} as any, []);
  const listener = jest.fn();

  assistant.on('step', listener);
  (assistant as any)['emit']('step', { status: 'TEST' });

  expect(listener).toHaveBeenCalledWith({ status: 'TEST' });
});

/* Generated by @n1k1t/unit-generator */
it('should register a one-time event listener with once method', () => {
  const assistant = new Assistant({} as any, []);
  const listener = jest.fn();

  assistant.once('step', listener);
  (assistant as any)['emit']('step', { status: 'TEST1' });
  (assistant as any)['emit']('step', { status: 'TEST2' });

  expect(listener).toHaveBeenCalledTimes(1);
  expect(listener).toHaveBeenCalledWith({ status: 'TEST1' });
});

/* Generated by @n1k1t/unit-generator */
it('should register a step, update state, and emit a step event', () => {
  const assistant = new Assistant({} as any, []);
  const emitSpy = jest.spyOn(assistant, 'emit' as any);
  const step = { status: 'REGISTERED', snapshot: 'snap', strategy: 'STRAT', iteration: 1 };

  (assistant as any)['register'](step);

  expect(assistant.steps).toEqual([step]);
  expect(assistant.state).toEqual(step);
  expect(emitSpy).toHaveBeenCalledWith('step', step);

  emitSpy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should complete the assistant, calculate spent time, set status, and clear', async () => {
  const assistant = new Assistant({} as any, []);
  const calculateTimeSpentSpy = jest.spyOn(assistant, 'calculateTimeSpent');
  const clearSpy = jest.spyOn(assistant, 'clear').mockResolvedValue(undefined);

  assistant.timestamp = Date.now() - 1000;
  assistant.state.status = 'PREPARING';

  await (assistant as any)['complete']();

  expect(calculateTimeSpentSpy).toHaveBeenCalled();
  expect((assistant as any)['spent']).toBeGreaterThanOrEqual(1000);
  expect(assistant.state.status).toEqual('COMPLETED');
  expect(clearSpy).toHaveBeenCalled();

  calculateTimeSpentSpy.mockRestore();
  clearSpy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should return early if coverage is reached and status is DONE', async () => {
  const mockSource = {
    checkHasReachedCoverage: jest.fn().mockReturnValue(true),
    compileSnapshot: jest.fn(),
    temp: '',
    spec: { content: [], remove: jest.fn() }
  };
  const assistant = new Assistant(mockSource as any, []);
  assistant.state.status = 'DONE';

  const completeSpy = jest.spyOn(assistant, 'complete' as any).mockResolvedValue(undefined);
  const strategyRunSpy = jest.fn();

  await assistant.run();

  expect(mockSource.checkHasReachedCoverage).toHaveBeenCalled();
  expect(completeSpy).toHaveBeenCalled();
  expect(strategyRunSpy).not.toHaveBeenCalled();

  completeSpy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should execute strategies and register steps', async () => {
  const mockSource = {
    checkHasReachedCoverage: jest.fn().mockReturnValue(false),
    compileSnapshot: jest.fn().mockReturnValue('snapshot'),
    temp: '',
    spec: { content: [], remove: jest.fn() }
  };
  const mockStrategy1 = { name: 'Strategy1', run: jest.fn().mockResolvedValue('EXECUTED') };
  const mockStrategy2 = { name: 'Strategy2', run: jest.fn().mockResolvedValue('EXECUTED') };
  const assistant = new Assistant(mockSource as any, [mockStrategy1 as any, mockStrategy2 as any], { iterations: 1 });

  const registerSpy = jest.spyOn(assistant, 'register' as any);
  const completeSpy = jest.spyOn(assistant, 'complete' as any).mockResolvedValue(undefined);

  await assistant.run();

  expect(mockStrategy1.run).toHaveBeenCalledTimes(1);
  expect(mockStrategy2.run).not.toHaveBeenCalled();
  expect(registerSpy).toHaveBeenCalledWith({
    status: 'EXECUTED',
    snapshot: 'snapshot',
    strategy: 'Strategy1',
    iteration: 1,
  });
  expect(completeSpy).toHaveBeenCalled();

  registerSpy.mockRestore();
  completeSpy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should skip strategy if its run method returns SKIPPED', async () => {
  const mockSource = {
    checkHasReachedCoverage: jest.fn().mockReturnValue(false),
    compileSnapshot: jest.fn().mockReturnValue('snapshot'),
    temp: '',
    spec: { content: [], remove: jest.fn() }
  };
  const mockStrategy1 = { name: 'Strategy1', run: jest.fn().mockResolvedValue('SKIPPED') };
  const mockStrategy2 = { name: 'Strategy2', run: jest.fn().mockResolvedValue('EXECUTED') };
  const assistant = new Assistant(mockSource as any, [mockStrategy1 as any, mockStrategy2 as any], { iterations: 1 });

  const registerSpy = jest.spyOn(assistant, 'register' as any);
  const completeSpy = jest.spyOn(assistant, 'complete' as any).mockResolvedValue(undefined);

  await assistant.run();

  expect(mockStrategy1.run).toHaveBeenCalledTimes(1);
  expect(mockStrategy2.run).toHaveBeenCalledTimes(1);
  expect(registerSpy).toHaveBeenCalledWith({
    status: 'EXECUTED',
    snapshot: 'snapshot',
    strategy: 'Strategy2',
    iteration: 1,
  });
  expect(completeSpy).toHaveBeenCalled();

  registerSpy.mockRestore();
  completeSpy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should respect the iterations limit', async () => {
  const mockSource = {
    checkHasReachedCoverage: jest.fn().mockReturnValue(false),
    compileSnapshot: jest.fn().mockReturnValue('snapshot'),
    temp: '',
    spec: { content: [], remove: jest.fn() }
  };
  const mockStrategy = { name: 'Strategy', run: jest.fn().mockResolvedValue('EXECUTED') };
  const assistant = new Assistant(mockSource as any, [mockStrategy as any], { iterations: 2 });

  const registerSpy = jest.spyOn(assistant, 'register' as any);
  const completeSpy = jest.spyOn(assistant, 'complete' as any).mockResolvedValue(undefined);

  await assistant.run();

  expect(mockStrategy.run).toHaveBeenCalledTimes(2);
  expect(registerSpy).toHaveBeenCalledTimes(2);
  expect(completeSpy).toHaveBeenCalled();

  registerSpy.mockRestore();
  completeSpy.mockRestore();
});


/* Generated by @n1k1t/unit-generator */
it('should call spec.remove if spec content is empty', async () => {
  const mockSource = {
    temp: '/tmp/test-assistant',
    spec: {
      content: [],
      remove: jest.fn().mockResolvedValue(undefined),
    },
  };
  const assistant = new Assistant(mockSource as any, []);

  await assistant.clear();

  expect(mockSource.spec.remove).toHaveBeenCalledTimes(1);
});

/* Generated by @n1k1t/unit-generator */
it('should not call spec.remove if spec content is not empty', async () => {
  const mockSource = {
    temp: '/tmp/test-assistant',
    spec: {
      content: ['some content'],
      remove: jest.fn().mockResolvedValue(undefined),
    },
  };
  const assistant = new Assistant(mockSource as any, []);

  await assistant.clear();

  expect(mockSource.spec.remove).not.toHaveBeenCalled();
});

/* Generated by @n1k1t/unit-generator */
it('should use provided cwd from options and call AssistantSource.build with it', async () => {
  const mockSourceInstance = {
    temp: '/tmp/mock',
    spec: { content: [], remove: jest.fn() },
    checkHasReachedCoverage: jest.fn(),
    compileSnapshot: jest.fn(),
  };
  const mockStrategyInstance = { name: 'MockStrategy', run: jest.fn() };

  const readFileSpy = jest.spyOn(fs, 'readFile').mockResolvedValue('');
  const rmSpy = jest.spyOn(fs, 'rm').mockResolvedValue(undefined);
  const assistantSourceBuildSpy = jest.spyOn(AssistantSource, 'build').mockResolvedValue(mockSourceInstance as any);
  const initStrategyBuildSpy = jest.spyOn(strategies.AssistantInitStrategy, 'build').mockReturnValue(mockStrategyInstance as any);
  const addStrategyBuildSpy = jest.spyOn(strategies.AssistantAddStrategy, 'build').mockReturnValue(mockStrategyInstance as any);
  const fixStrategyBuildSpy = jest.spyOn(strategies.AssistantFixStrategy, 'build').mockReturnValue(mockStrategyInstance as any);
  const processCwdSpy = jest.spyOn(process, 'cwd').mockReturnValue('/mock/cwd');

  const mockLocation = '/test/location';
  const options = { cwd: '/custom/cwd' };

  await Assistant.build(mockLocation, options);

  expect(processCwdSpy).not.toHaveBeenCalled();
  expect(assistantSourceBuildSpy).toHaveBeenCalledWith(mockLocation, options);

  readFileSpy.mockRestore();
  rmSpy.mockRestore();
  assistantSourceBuildSpy.mockRestore();
  initStrategyBuildSpy.mockRestore();
  addStrategyBuildSpy.mockRestore();
  fixStrategyBuildSpy.mockRestore();
  processCwdSpy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should correctly parse package.json dependencies and .editorconfig, filtering @types and comments', async () => {
  const mockSourceInstance = {
    temp: '/tmp/mock',
    spec: { content: [], remove: jest.fn() },
    checkHasReachedCoverage: jest.fn(),
    compileSnapshot: jest.fn(),
  };
  const mockStrategyInstance = { name: 'MockStrategy', run: jest.fn() };

  const readFileSpy = jest.spyOn(fs, 'readFile').mockImplementation((filePath: any) => {
    if (filePath.includes('package.json')) {
      return Promise.resolve(JSON.stringify({
        dependencies: { 'prod-dep': '1.0.0', '@types/node': '1.0.0' },
        devDependencies: { 'dev-dep': '2.0.0', '@types/jest': '2.0.0' },
      }));
    }
    if (filePath.includes('.editorconfig')) {
      return Promise.resolve(`root = true\n# A comment\n[*]\nindent_style = space`);
    }
    return Promise.resolve('');
  });
  const rmSpy = jest.spyOn(fs, 'rm').mockResolvedValue(undefined);
  const assistantSourceBuildSpy = jest.spyOn(AssistantSource, 'build').mockResolvedValue(mockSourceInstance as any);
  const initStrategyBuildSpy = jest.spyOn(strategies.AssistantInitStrategy, 'build').mockReturnValue(mockStrategyInstance as any);
  const addStrategyBuildSpy = jest.spyOn(strategies.AssistantAddStrategy, 'build').mockReturnValue(mockStrategyInstance as any);
  const fixStrategyBuildSpy = jest.spyOn(strategies.AssistantFixStrategy, 'build').mockReturnValue(mockStrategyInstance as any);
  const processCwdSpy = jest.spyOn(process, 'cwd').mockReturnValue('/mock/cwd');

  const mockLocation = '/test/location';
  const options = { target: 0.8, model: 'gpt-3.5' };

  await Assistant.build(mockLocation, options);

  expect(readFileSpy).toHaveBeenCalledWith(path.join('/mock/cwd', 'package.json'), 'utf8');
  expect(readFileSpy).toHaveBeenCalledWith(path.join('/mock/cwd', '.editorconfig'), 'utf8');

  expect(initStrategyBuildSpy).toHaveBeenCalledWith(
    mockSourceInstance,
    expect.objectContaining({
      target: 0.8,
      model: 'gpt-3.5',
      dependencies: { 'prod-dep': '1.0.0', 'dev-dep': '2.0.0' },
      editorconfig: 'root = true\n[*]\nindent_style = space',
    })
  );

  readFileSpy.mockRestore();
  rmSpy.mockRestore();
  assistantSourceBuildSpy.mockRestore();
  initStrategyBuildSpy.mockRestore();
  addStrategyBuildSpy.mockRestore();
  fixStrategyBuildSpy.mockRestore();
  processCwdSpy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should return a new Assistant instance with compiled strategies', async () => {
  const mockSourceInstance = {
    temp: '/tmp/mock',
    spec: { content: [], remove: jest.fn() },
    checkHasReachedCoverage: jest.fn(),
    compileSnapshot: jest.fn(),
  };
  const mockStrategyInstance1 = { name: 'MockStrategy1', run: jest.fn() };
  const mockStrategyInstance2 = { name: 'MockStrategy2', run: jest.fn() };
  const mockStrategyInstance3 = { name: 'MockStrategy3', run: jest.fn() };

  const readFileSpy = jest.spyOn(fs, 'readFile').mockResolvedValue('');
  const rmSpy = jest.spyOn(fs, 'rm').mockResolvedValue(undefined);
  const assistantSourceBuildSpy = jest.spyOn(AssistantSource, 'build').mockResolvedValue(mockSourceInstance as any);
  const initStrategyBuildSpy = jest.spyOn(strategies.AssistantInitStrategy, 'build').mockReturnValue(mockStrategyInstance1 as any);
  const addStrategyBuildSpy = jest.spyOn(strategies.AssistantAddStrategy, 'build').mockReturnValue(mockStrategyInstance2 as any);
  const fixStrategyBuildSpy = jest.spyOn(strategies.AssistantFixStrategy, 'build').mockReturnValue(mockStrategyInstance3 as any);
  const processCwdSpy = jest.spyOn(process, 'cwd').mockReturnValue('/mock/cwd');

  const mockLocation = '/test/location';
  const options = { model: 'test-model' };

  const assistant = await Assistant.build(mockLocation, options);

  expect(initStrategyBuildSpy).toHaveBeenCalledWith(mockSourceInstance, expect.any(Object));
  expect(addStrategyBuildSpy).toHaveBeenCalledWith(mockSourceInstance, expect.any(Object));
  expect(fixStrategyBuildSpy).toHaveBeenCalledWith(mockSourceInstance, expect.any(Object));

  expect(assistant).toBeInstanceOf(Assistant);
  expect(assistant.source).toBe(mockSourceInstance);
  expect(assistant.strategies).toEqual([mockStrategyInstance1, mockStrategyInstance2, mockStrategyInstance3]);
  expect(assistant.options).toBe(options);

  readFileSpy.mockRestore();
  rmSpy.mockRestore();
  assistantSourceBuildSpy.mockRestore();
  initStrategyBuildSpy.mockRestore();
  addStrategyBuildSpy.mockRestore();
  fixStrategyBuildSpy.mockRestore();
  processCwdSpy.mockRestore();
});
