import { AssistantRouter } from './router';

/* Generated by @n1k1t/unit-generator */
it('should return google provider when model name contains gemini', () => {
  const router = new AssistantRouter({ key: 'test-key' });
  const result = router.provide('gemini-pro');
  expect(result.name).toBe('google/gemini-pro');
});

/* Generated by @n1k1t/unit-generator */
it('should return anthropic provider when model name contains claude', () => {
  const router = new AssistantRouter({ key: 'test-key' });
  const result = router.provide('claude-3-opus');
  expect(result.name).toBe('anthropic/claude-3-opus');
});

/* Generated by @n1k1t/unit-generator */
it('should return mistral provider when model name contains mistral', () => {
  const router = new AssistantRouter({ key: 'test-key' });
  const result = router.provide('mistral-large');
  expect(result.name).toBe('mistral/mistral-large');
});

/* Generated by @n1k1t/unit-generator */
it('should return openai provider when model name contains gpt', () => {
  const router = new AssistantRouter({ key: 'test-key' });
  const result = router.provide('gpt-4');
  expect(result.name).toBe('openai/gpt-4');
});

/* Generated by @n1k1t/unit-generator */
it('should default to openai provider when model name is unknown', () => {
  const router = new AssistantRouter({ key: 'test-key' });
  const result = router.provide('unknown-model');
  expect(result.name).toBe('openai/unknown-model');
});

/* Generated by @n1k1t/unit-generator */
it('should use explicit provider from context regardless of model name', () => {
  const router = new AssistantRouter({ key: 'test-key', provider: 'google' });
  const result = router.provide('gpt-4');
  expect(result.name).toBe('google/gpt-4');
});

/* Generated by @n1k1t/unit-generator */
it('should include thinking options for google provider', () => {
  const router = new AssistantRouter({ key: 'test-key', provider: 'google' });
  const result = router.provide('gemini-pro');
  expect(result.options).toHaveProperty('google.thinkingConfig.thinkingLevel', 'low');
});

/* Generated by @n1k1t/unit-generator */
it('should include thinking options for anthropic provider', () => {
  const router = new AssistantRouter({ key: 'test-key', provider: 'anthropic' });
  const result = router.provide('claude-3');
  expect(result.options).toHaveProperty('anthropic.thinking.type', 'enabled');
});

/* Generated by @n1k1t/unit-generator */
it('should include reasoning effort for openai provider', () => {
  const router = new AssistantRouter({ key: 'test-key', provider: 'openai' });
  const result = router.provide('gpt-4');
  expect(result.options).toHaveProperty('openai.reasoningEffort', 'low');
});

/* Generated by @n1k1t/unit-generator */
it('should not include options for mistral provider', () => {
  const router = new AssistantRouter({ key: 'test-key', provider: 'mistral' });
  const result = router.provide('mistral-tiny');
  expect(result.options).toBeUndefined();
});

/* Generated by @n1k1t/unit-generator */
it('should use provided key in the context', () => {
  const router = AssistantRouter.build({ key: 'custom-key' });
  expect(router.context.key).toBe('custom-key');
});
