import fs from 'fs/promises'
import child_process from 'child_process'
import { File } from '../file'
import { Cobertura } from '../cobertura'
import { AssistantSource } from './source';

/* Generated by @n1k1t/unit-generator */
it('checkHasReachedCoverage returns true when rate >= target', () => {
  const cobertura: any = { rate: 80, uncovered: [], assign: jest.fn(), refresh: jest.fn() };
  const file: any = { content: '', path: 'code.ts', write: jest.fn() };
  const specFile: any = { content: '', path: 'spec.ts', write: jest.fn() };
  const src = new AssistantSource({ id: '1', code: file, spec: specFile, cobertura, temp: 'tmp', target: 75 });
  expect(src.checkHasReachedCoverage()).toEqual(true);
});

/* Generated by @n1k1t/unit-generator */
it('checkHasReachedCoverage returns false when rate < target', () => {
  const cobertura: any = { rate: 50, uncovered: [], assign: jest.fn(), refresh: jest.fn() };
  const file: any = { content: '', path: 'code.ts', write: jest.fn() };
  const specFile: any = { content: '', path: 'spec.ts', write: jest.fn() };
  const src = new AssistantSource({ id: '2', code: file, spec: specFile, cobertura, temp: 'tmp', target: 75 });
  expect(src.checkHasReachedCoverage()).toEqual(false);
});

/* Generated by @n1k1t/unit-generator */
it('compileSnapshot returns expected snapshot shape', () => {
  const cobertura: any = { rate: 60, uncovered: ['a'], assign: jest.fn(), refresh: jest.fn() };
  const file: any = { content: 'spec-content', path: 'spec.ts', write: jest.fn() };
  const codeFile: any = { content: 'code', path: 'code.ts', write: jest.fn() };
  const src = new AssistantSource({ id: '3', code: codeFile, spec: file, cobertura, temp: 'tmp', target: 70 });
  expect(src.compileSnapshot()).toEqual({ cobertura: { uncovered: ['a'], rate: 60 }, spec: { content: 'spec-content' } });
});

/* Generated by @n1k1t/unit-generator */
it('save stores compiled snapshot on the instance', () => {
  const cobertura: any = { rate: 90, uncovered: [], assign: jest.fn(), refresh: jest.fn() };
  const file: any = { content: 's', path: 'spec.ts', write: jest.fn() };
  const codeFile: any = { content: 'c', path: 'code.ts', write: jest.fn() };
  const src: any = new AssistantSource({ id: '4', code: codeFile, spec: file, cobertura, temp: 'tmp', target: 50 });
  src.save();
  expect(src.saved).toEqual(src.compileSnapshot());
});

/* Generated by @n1k1t/unit-generator */
it('restore applies provided snapshot using cobertura.assign and spec.write', async () => {
  const assign = jest.fn();
  const refresh = jest.fn();
  const cobertura: any = { rate: 10, uncovered: [], assign, refresh };
  const write = jest.fn(() => Promise.resolve());
  const specFile: any = { content: '', path: 'spec.ts', write };
  const codeFile: any = { content: '', path: 'code.ts', write: jest.fn() };
  const src = new AssistantSource({ id: '5', code: codeFile, spec: specFile, cobertura, temp: 'tmp', target: 20 });
  const snapshot = { cobertura: { rate: 99, uncovered: ['x'] }, spec: { content: 'restored' } };
  await src.restore(snapshot as any);
  expect(assign).toHaveBeenCalledWith({ rate: 99, uncovered: ['x'] });
});


/* Generated by @n1k1t/unit-generator */
it('test returns FAILED when spawned exits with non-zero and stderr captured', async () => {
  const stderr = { on: jest.fn((event, cb) => { if (event === 'data') cb(Buffer.from('error-output')) }) }
  const spawned: any = { stderr, once: jest.fn((event, cb) => { if (event === 'exit') cb(1) }) }
  jest.spyOn(child_process, 'spawn').mockReturnValue(spawned)

  const refresh = jest.fn(() => Promise.resolve())
  const cobertura: any = { rate: 0, uncovered: [], assign: jest.fn(), refresh }
  const codeFile: any = { content: '', path: 'code.ts', write: jest.fn() }
  const specFile: any = { content: '', path: 'spec.ts', write: jest.fn() }
  const src = new AssistantSource({ id: 't-fail', code: codeFile, spec: specFile, cobertura, temp: 'tmp', target: 50 })

  const result = await src.test()
  expect(result).toEqual({ status: 'FAILED', message: 'error-output' })
  jest.restoreAllMocks()
})

/* Generated by @n1k1t/unit-generator */
it('test returns PASSED when spawned exits with zero', async () => {
  const stderr = { on: jest.fn() }
  const spawned: any = { stderr, once: jest.fn((event, cb) => { if (event === 'exit') cb(0) }) }
  jest.spyOn(child_process, 'spawn').mockReturnValue(spawned)

  const refresh = jest.fn(() => Promise.resolve())
  const cobertura: any = { rate: 100, uncovered: [], assign: jest.fn(), refresh }
  const codeFile: any = { content: '', path: 'code.ts', write: jest.fn() }
  const specFile: any = { content: '', path: 'spec.ts', write: jest.fn() }
  const src = new AssistantSource({ id: 't-pass', code: codeFile, spec: specFile, cobertura, temp: 'tmp', target: 50 })

  const result = await src.test()
  expect(result.status).toEqual('PASSED')
  jest.restoreAllMocks()
})

/* Generated by @n1k1t/unit-generator */
it('restore returns same instance when no snapshot provided and nothing saved', async () => {
  const cobertura: any = { rate: 1, uncovered: [], assign: jest.fn(), refresh: jest.fn() }
  const specFile: any = { content: '', path: 'spec.ts', write: jest.fn() }
  const codeFile: any = { content: '', path: 'code.ts', write: jest.fn() }
  const src = new AssistantSource({ id: 'no-snap', code: codeFile, spec: specFile, cobertura, temp: 'tmp', target: 10 })
  const res = await src.restore()
  expect(res).toBe(src)
})

/* Generated by @n1k1t/unit-generator */
it('build creates temp when missing and applies rate via cobertura.assign', async () => {
  jest.spyOn(fs, 'stat').mockRejectedValue(null)
  jest.spyOn(fs, 'mkdir').mockResolvedValue(undefined as any)
  jest.spyOn(File, 'build').mockResolvedValue({ content: '', path: 'code.ts', write: jest.fn() } as any)
  const assign = jest.fn()
  jest.spyOn(Cobertura, 'build').mockResolvedValue({ assign, rate: 0, uncovered: [], refresh: jest.fn() } as any)

  const src = await AssistantSource.build('/some/location.ts', { cwd: '/cwd', rate: 12, target: 5 })
  expect(assign).toHaveBeenCalledWith({ rate: 12 })
  jest.restoreAllMocks()
})

/* Generated by @n1k1t/unit-generator */
it('build sets provided target on the created AssistantSource', async () => {
  jest.spyOn(fs, 'stat').mockRejectedValue(null)
  jest.spyOn(fs, 'mkdir').mockResolvedValue(undefined as any)
  jest.spyOn(File, 'build').mockResolvedValue({ content: '', path: 'code.ts', write: jest.fn() } as any)
  jest.spyOn(Cobertura, 'build').mockResolvedValue({ assign: jest.fn(), rate: 0, uncovered: [], refresh: jest.fn() } as any)

  const src = await AssistantSource.build('/another/location.ts', { cwd: '/cwd', target: 77 })
  expect(src.target).toEqual(77)
  jest.restoreAllMocks()
})
