import path from 'path';
import fs from 'fs/promises';
import fg from 'fast-glob';

import { AssistantSource } from './source';
import { Cobertura } from '../cobertura';
import { File } from '../file';
import { Spec } from '../spec';

import env from '../../env';

/* Generated by @n1k1t/unit-generator */
it('should initialize with a generated uuid if no id is provided', () => {
  const source = new AssistantSource({
    code: {} as File,
    spec: {} as Spec,
    cobertura: {} as Cobertura,
    temp: '/tmp',
    tree: [],
    ignore: []
  } as any);
  expect(source.id).toBeDefined();
});

/* Generated by @n1k1t/unit-generator */
it('should return true when coverage rate is equal to target', () => {
  const source = new AssistantSource({
    code: {} as File,
    spec: {} as Spec,
    cobertura: { rate: 80 } as Cobertura,
    temp: '/tmp',
    tree: [],
    ignore: [],
    target: 80
  } as any);
  expect(source.checkHasReachedCoverage()).toBe(true);
});

/* Generated by @n1k1t/unit-generator */
it('should return false when coverage rate is less than target', () => {
  const source = new AssistantSource({
    code: {} as File,
    spec: {} as Spec,
    cobertura: { rate: 70 } as Cobertura,
    temp: '/tmp',
    tree: [],
    ignore: [],
    target: 80
  } as any);
  expect(source.checkHasReachedCoverage()).toBe(false);
});

/* Generated by @n1k1t/unit-generator */
it('should compile a snapshot with current cobertura and spec state', () => {
  const source = new AssistantSource({
    code: {} as File,
    spec: { content: 'test content' } as Spec,
    cobertura: { uncovered: [1, 2], rate: 50 } as Cobertura,
    temp: '/tmp',
    tree: [],
    ignore: []
  } as any);
  const snapshot = source.compileSnapshot();
  expect(snapshot).toEqual({
    cobertura: { uncovered: [1, 2], rate: 50 },
    spec: { content: 'test content' }
  });
});

/* Generated by @n1k1t/unit-generator */
it('should update the saved property when save is called', () => {
  const source = new AssistantSource({
    code: {} as File,
    spec: { content: 'initial' } as Spec,
    cobertura: { uncovered: [], rate: 100 } as any,
    temp: '/tmp',
    tree: [],
    ignore: []
  } as any);
  source.save();
  expect((source as any).saved).toEqual(source.compileSnapshot());
});

/* Generated by @n1k1t/unit-generator */
it('should restore state from the saved snapshot when no argument is provided to restore', async () => {
  const mockSpec = { content: 'old', write: jest.fn() } as unknown as Spec;
  const mockCobertura = { rate: 0, assign: jest.fn() } as unknown as Cobertura;
  const source = new AssistantSource({
    code: {} as File,
    spec: mockSpec,
    cobertura: mockCobertura,
    temp: '/tmp',
    tree: [],
    ignore: []
  } as any);
  const snapshot = { cobertura: { rate: 100, uncovered: [] }, spec: { content: 'new' } };
  (source as any).saved = snapshot;
  await source.restore();
  expect(mockCobertura.assign).toHaveBeenCalledWith(snapshot.cobertura);
});

/* Generated by @n1k1t/unit-generator */
it('should call spec.write with snapshot content during restore', async () => {
  const mockSpec = { content: 'old', write: jest.fn() } as unknown as Spec;
  const mockCobertura = { rate: 0, assign: jest.fn() } as unknown as Cobertura;
  const source = new AssistantSource({
    code: {} as File,
    spec: mockSpec,
    cobertura: mockCobertura,
    temp: '/tmp',
    tree: [],
    ignore: []
  } as any);
  const snapshot = { cobertura: { rate: 100, uncovered: [] }, spec: { content: 'restored content' } };
  await source.restore(snapshot);
  expect(mockSpec.write).toHaveBeenCalledWith('restored content');
});

/* Generated by @n1k1t/unit-generator */
it('should return this instance from restore even if no snapshot exists', async () => {
  const source = new AssistantSource({
    code: {} as File,
    spec: {} as Spec,
    cobertura: {} as Cobertura,
    temp: '/tmp',
    tree: [],
    ignore: []
  } as any);
  const result = await source.restore();
  expect(result).toBe(source);
});

/* Generated by @n1k1t/unit-generator */
it('should return true when coverage rate is greater than or equal to target', () => {
  const cobertura = { rate: 0.8 } as Cobertura;
  const assistant = new AssistantSource({ cobertura, target: 0.7 } as any);
  expect(assistant.checkHasReachedCoverage()).toBe(true);
})

/* Generated by @n1k1t/unit-generator */
it('should return false when coverage rate is less than target', () => {
  const cobertura = { rate: 0.5 } as Cobertura;
  const assistant = new AssistantSource({ cobertura, target: 0.7 } as any);
  expect(assistant.checkHasReachedCoverage()).toBe(false);
})

/* Generated by @n1k1t/unit-generator */
it('should return true when coverage rate equals target', () => {
  const cobertura = { rate: 0.7 } as Cobertura;
  const assistant = new AssistantSource({ cobertura, target: 0.7 } as any);
  expect(assistant.checkHasReachedCoverage()).toBe(true);
})

/* Generated by @n1k1t/unit-generator */
it('should use default target from env if not provided in constructor', () => {
  const cobertura = { rate: env.target - 0.1 } as Cobertura;
  const assistant = new AssistantSource({ cobertura } as any);
  expect(assistant.checkHasReachedCoverage()).toBe(false);
})

/* Generated by @n1k1t/unit-generator */
it('should compile a snapshot of the current state', () => {
  const cobertura = { uncovered: [1, 2, 3], rate: 0.5 } as Cobertura;
  const spec = { content: 'test content' } as Spec;
  const assistant = new AssistantSource({ cobertura, spec } as any);
  const snapshot = assistant.compileSnapshot();
  expect(snapshot).toEqual({
    cobertura: { uncovered: [1, 2, 3], rate: 0.5 },
    spec: { content: 'test content' }
  });
})

/* Generated by @n1k1t/unit-generator */
it('should save the current state snapshot to the saved property', () => {
  const cobertura = { uncovered: [10], rate: 0.9 } as Cobertura;
  const spec = { content: 'saved spec' } as Spec;
  const assistant = new AssistantSource({ cobertura, spec } as any);
  assistant.save();
  expect((assistant as any).saved).toEqual({
    cobertura: { uncovered: [10], rate: 0.9 },
    spec: { content: 'saved spec' }
  });
})

/* Generated by @n1k1t/unit-generator */
it('should restore state from the provided snapshot', async () => {
  const cobertura = { assign: jest.fn() } as any;
  const spec = { write: jest.fn().mockResolvedValue(undefined) } as any;
  const assistant = new AssistantSource({ cobertura, spec } as any);
  const snapshot = { cobertura: { rate: 1, uncovered: [] }, spec: { content: 'restored' } };
  await assistant.restore(snapshot);
  expect(cobertura.assign).toHaveBeenCalledWith(snapshot.cobertura);
})

/* Generated by @n1k1t/unit-generator */
it('should restore state from the saved snapshot if none provided', async () => {
  const cobertura = { assign: jest.fn(), rate: 0.5, uncovered: [1] } as any;
  const spec = { content: 'old', write: jest.fn().mockResolvedValue(undefined) } as any;
  const assistant = new AssistantSource({ cobertura, spec } as any);
  assistant.save();
  cobertura.rate = 0.1;
  await assistant.restore();
  expect(cobertura.assign).toHaveBeenCalledWith({ rate: 0.5, uncovered: [1] });
})

/* Generated by @n1k1t/unit-generator */
it('should return self and do nothing if restore is called without snapshot and no saved state exists', async () => {
  const assistant = new AssistantSource({} as any);
  const result = await assistant.restore();
  expect(result).toBe(assistant);
})

/* Generated by @n1k1t/unit-generator */
it('should call spec.write with snapshot content during restore', async () => {
  const spec = { write: jest.fn().mockResolvedValue(undefined) } as any;
  const assistant = new AssistantSource({ cobertura: { assign: jest.fn() }, spec } as any);
  const snapshot = { cobertura: { rate: 1, uncovered: [] }, spec: { content: 'new content' } };
  await assistant.restore(snapshot);
  expect(spec.write).toHaveBeenCalledWith('new content');
})

/* Generated by @n1k1t/unit-generator */
it('should return FAILED status and stderr message when test process fails', async () => {
  const mockSpawn = jest.spyOn(require('child_process'), 'spawn').mockReturnValue({
    stderr: { on: (event: string, cb: Function) => event === 'data' && cb(Buffer.from('error message')) },
    once: (event: string, cb: Function) => event === 'exit' && cb(1)
  } as any);
  const assistant = new AssistantSource({ spec: { path: 's' }, code: { path: 'c' }, temp: 't', cobertura: { refresh: jest.fn() } } as any);
  const result = await assistant.test();
  expect(result).toEqual({ status: 'FAILED', message: 'error message' });
  mockSpawn.mockRestore();
})

/* Generated by @n1k1t/unit-generator */
it('should return PASSED status when test process exits with code 0', async () => {
  const mockSpawn = jest.spyOn(require('child_process'), 'spawn').mockReturnValue({
    stderr: { on: jest.fn() },
    once: (event: string, cb: Function) => event === 'exit' && cb(0)
  } as any);
  const assistant = new AssistantSource({ spec: { path: 's' }, code: { path: 'c' }, temp: 't', cobertura: { refresh: jest.fn() } } as any);
  const result = await assistant.test();
  expect(result).toEqual({ status: 'PASSED' });
  mockSpawn.mockRestore();
})

/* Generated by @n1k1t/unit-generator */
it('should refresh cobertura after test execution', async () => {
  const cobertura = { refresh: jest.fn().mockResolvedValue(undefined) } as any;
  jest.spyOn(require('child_process'), 'spawn').mockReturnValue({
    stderr: { on: jest.fn() },
    once: (event: string, cb: Function) => event === 'exit' && cb(0)
  } as any);
  const assistant = new AssistantSource({ spec: { path: 's' }, code: { path: 'c' }, temp: 't', cobertura } as any);
  await assistant.test();
  expect(cobertura.refresh).toHaveBeenCalled();
})

/* Generated by @n1k1t/unit-generator */
it('should create temp directory in build if it does not exist', async () => {
  jest.spyOn(fs, 'stat').mockRejectedValue(new Error());
  const mkdirSpy = jest.spyOn(fs, 'mkdir').mockResolvedValue(undefined);
  jest.spyOn(File, 'build').mockResolvedValue({} as any);
  jest.spyOn(Spec, 'build').mockResolvedValue({} as any);
  jest.spyOn(Cobertura, 'build').mockResolvedValue({ assign: jest.fn() } as any);
  jest.spyOn(fs, 'readFile').mockResolvedValue('');
  jest.spyOn(fg, 'sync' as any).mockReturnValue([]);
  await AssistantSource.build('test.ts');
  expect(mkdirSpy).toHaveBeenCalled();
})

/* Generated by @n1k1t/unit-generator */
it('should assign rate to cobertura in build if provided in options', async () => {
  const mockCobertura = { assign: jest.fn() } as any;
  jest.spyOn(fs, 'stat').mockResolvedValue({} as any);
  jest.spyOn(File, 'build').mockResolvedValue({} as any);
  jest.spyOn(Spec, 'build').mockResolvedValue({} as any);
  jest.spyOn(Cobertura, 'build').mockResolvedValue(mockCobertura);
  jest.spyOn(fs, 'readFile').mockResolvedValue('');
  await AssistantSource.build('test.ts', { rate: 0.85 });
  expect(mockCobertura.assign).toHaveBeenCalledWith({ rate: 0.85 });
})

/* Generated by @n1k1t/unit-generator */
it('should return this when restore is called without a snapshot and no saved state exists', async () => {
  const cobertura = new Cobertura(new File({ path: 'coverage.xml', content: '', lang: 'xml' }));
  const spec = new Spec(new File({ path: 'test.spec.ts', content: '', lang: 'ts' }));
  const source = new AssistantSource({
    id: 'test-id',
    code: new File({ path: 'code.ts', content: '', lang: 'ts' }),
    spec,
    cobertura,
    temp: 'temp',
    tree: [],
    ignore: []
  });

  const result = await source.restore();

  expect(result).toBe(source);
});

/* Generated by @n1k1t/unit-generator */
it('should create a directory for the assistant source if it does not exist during build', async () => {
  const location = 'src/example.ts';
  const id = 'unique-id';
  const tempPath = path.join('generated', id);

  jest.spyOn(fs, 'stat').mockRejectedValueOnce(new Error('Not found'));
  const mkdirSpy = jest.spyOn(fs, 'mkdir').mockResolvedValueOnce(undefined);
  jest.spyOn(fs, 'readFile').mockResolvedValue('');
  jest.spyOn(fs, 'writeFile').mockResolvedValue();

  await AssistantSource.build(location, { cwd: process.cwd() });

  expect(mkdirSpy).toHaveBeenCalled();
});
