import { AttachmentContent } from './attachment';

/* Generated by @n1k1t/unit-generator */
it('should build AttachmentContent with object content and default extension/path/isVirtual', () => {
  const attachment = AttachmentContent.build({
    title: 'My Title',
    content: { foo: 'bar' }
  });
  expect(attachment.payload).toEqual({
    title: 'My Title',
    content: { foo: 'bar' },
    extension: '.json',
    path: 'my-title.json',
    isVirtual: true
  });
});

/* Generated by @n1k1t/unit-generator */
it('should build AttachmentContent with string content and default extension/path/isVirtual', () => {
  const attachment = AttachmentContent.build({
    title: 'Another Title',
    content: 'some text content'
  });
  expect(attachment.payload).toEqual({
    title: 'Another Title',
    content: 'some text content',
    extension: '.txt',
    path: 'another-title.txt',
    isVirtual: true
  });
});

/* Generated by @n1k1t/unit-generator */
it('should build AttachmentContent with path provided and extract extension from path', () => {
  const attachment = AttachmentContent.build({
    title: 'Custom Path',
    content: 'text',
    path: 'src/custom.md'
  });
  expect(attachment.payload).toEqual({
    title: 'Custom Path',
    content: 'text',
    extension: '.md',
    path: 'src/custom.md',
    isVirtual: false
  });
});

/* Generated by @n1k1t/unit-generator */
it('should build AttachmentContent with explicit extension', () => {
  const attachment = AttachmentContent.build({
    title: 'Custom Ext',
    content: 'text',
    extension: '.custom'
  });
  expect(attachment.payload.extension).toEqual('.custom');
});

/* Generated by @n1k1t/unit-generator */
it('should build AttachmentContent with explicit isVirtual', () => {
  const attachment = AttachmentContent.build({
    title: 'Virtual Test',
    content: 'text',
    isVirtual: false
  });
  expect(attachment.payload.isVirtual).toEqual(false);
});

/* Generated by @n1k1t/unit-generator */
it('should render markdown title for object content', () => {
  const attachment = AttachmentContent.build({
    title: 'JSON Data',
    content: { a: 1 }
  });
  expect(attachment.render()).toContain('### JSON Data');
});

/* Generated by @n1k1t/unit-generator */
it('should render markdown with json code block for object content', () => {
  const attachment = AttachmentContent.build({
    title: 'JSON Data',
    content: { a: 1 }
  });
  expect(attachment.render()).toContain('```json\n{\n  "a": 1\n}\n```');
});

/* Generated by @n1k1t/unit-generator */
it('should render markdown with txt code block for string content', () => {
  const attachment = AttachmentContent.build({
    title: 'Text Data',
    content: 'hello world'
  });
  expect(attachment.render()).toContain('```txt\nhello world\n```');
});
