import { GroupContent } from './group';
import { PlainContent } from './plain';

/* Generated by @n1k1t/unit-generator */
it('should build a GroupContent instance with correct type', () => {
  const payload = [PlainContent.build('hello')];
  const group = GroupContent.build(payload);
  expect(group.type).toBe('group');
});

/* Generated by @n1k1t/unit-generator */
it('should build a GroupContent instance with correct payload', () => {
  const payload = [PlainContent.build('hello')];
  const group = GroupContent.build(payload);
  expect(group.payload).toBe(payload);
});

/* Generated by @n1k1t/unit-generator */
it('should render empty payload as empty string', () => {
  const group = GroupContent.build([]);
  expect(group.render()).toBe('');
});

/* Generated by @n1k1t/unit-generator */
it('should render single content item', () => {
  const group = GroupContent.build([PlainContent.build('hello')]);
  expect(group.render()).toBe('hello');
});

/* Generated by @n1k1t/unit-generator */
it('should render multiple content items joined by double newlines', () => {
  const group = GroupContent.build([
    PlainContent.build('hello'),
    PlainContent.build('world')
  ]);
  expect(group.render()).toBe('hello\n\nworld');
});

/* Generated by @n1k1t/unit-generator */
it('should return empty array for flat on empty payload', () => {
  const group = GroupContent.build([]);
  expect(group.flat()).toEqual([]);
});

/* Generated by @n1k1t/unit-generator */
it('should return flat array of non-group content items', () => {
  const item1 = PlainContent.build('hello');
  const item2 = PlainContent.build('world');
  const group = GroupContent.build([item1, item2]);
  expect(group.flat()).toEqual([item1, item2]);
});

/* Generated by @n1k1t/unit-generator */
it('should flatten nested GroupContent instances', () => {
  const item1 = PlainContent.build('hello');
  const item2 = PlainContent.build('world');
  const nestedGroup = GroupContent.build([item2]);
  const group = GroupContent.build([item1, nestedGroup]);
  expect(group.flat()).toEqual([item1, item2]);
});
