import { PlainContent } from './plain';

/* Generated by @n1k1t/unit-generator */
it('should build a PlainContent instance with correct type', () => {
  const content = PlainContent.build('hello');
  expect(content.type).toBe('plain');
});

/* Generated by @n1k1t/unit-generator */
it('should build a PlainContent instance with correct payload', () => {
  const content = PlainContent.build('hello');
  expect(content.payload).toBe('hello');
});

/* Generated by @n1k1t/unit-generator */
it('should render simple string without changes', () => {
  const content = PlainContent.build('hello');
  expect(content.render()).toBe('hello');
});

/* Generated by @n1k1t/unit-generator */
it('should strip common leading spaces from all lines', () => {
  const content = PlainContent.build('  hello\n  world');
  expect(content.render()).toBe('hello\nworld');
});

/* Generated by @n1k1t/unit-generator */
it('should render empty string as empty string', () => {
  const content = PlainContent.build('');
  expect(content.render()).toBe('');
});

/* Generated by @n1k1t/unit-generator */
it('should render whitespace-only string as is', () => {
  const content = PlainContent.build('   ');
  expect(content.render()).toBe('   ');
});

/* Generated by @n1k1t/unit-generator */
it('should handle leading newline and strip spaces correctly', () => {
  const content = PlainContent.build('\n  hello');
  expect(content.render()).toBe('\nhello');
});

/* Generated by @n1k1t/unit-generator */
it('should handle multiple newlines and strip spaces correctly', () => {
  const content = PlainContent.build('\n\n  hello');
  expect(content.render()).toBe('\n\nello');
});

/* Generated by @n1k1t/unit-generator */
it('should handle string with only newlines', () => {
  const content = PlainContent.build('\n\n');
  expect(content.render()).toBe('\n\n');
});
