import '../../../setup';
import { SourcesContent } from './sources';

/* Generated by @n1k1t/unit-generator */
it('should build an instance of SourcesContent with correct type', () => {
  const payload = [{ location: 'src/index.ts', title: 'Index File' }];
  const content = SourcesContent.build(payload);
  expect(content.type).toEqual('sources');
});

/* Generated by @n1k1t/unit-generator */
it('should build an instance of SourcesContent with correct payload', () => {
  const payload = [{ location: 'src/index.ts', title: 'Index File' }];
  const content = SourcesContent.build(payload);
  expect(content.payload).toEqual(payload);
});

/* Generated by @n1k1t/unit-generator */
it('should serialize payload with title correctly', () => {
  const payload = [{ location: 'src/index.ts', title: 'Index File' }];
  const content = SourcesContent.build(payload);
  expect(content.serialize()).toEqual(['`src/index.ts`: Index File']);
});

/* Generated by @n1k1t/unit-generator */
it('should serialize payload without title correctly', () => {
  const payload = [{ location: 'src/index.ts' }];
  const content = SourcesContent.build(payload);
  expect(content.serialize()).toEqual(['`src/index.ts`']);
});
