import analyze from './analyze';
import * as utils from './utils';
import env from '../env';

/* Generated by @n1k1t/unit-generator */
it('should pass parameters to extractCoberturaItems', async () => {
  const cwd = '/cwd';
  jest.spyOn(process, 'cwd').mockReturnValue(cwd);
  const ignored = [] as any;
  jest.spyOn(utils, 'extractIgnoredPaths').mockResolvedValue(ignored);
  const extracted = [] as any;
  const extractCoberturaItemsSpy = jest.spyOn(utils, 'extractCoberturaItems').mockResolvedValue(extracted);
  jest.spyOn(console, 'table').mockImplementation(() => {});
  env.cobertura = 'cov.xml';
  await analyze({ target: 50, limit: 5, paths: ['p1'] });
  expect(extractCoberturaItemsSpy).toHaveBeenCalledWith(env.cobertura, expect.objectContaining({ target: 50, limit: 5, paths: ['p1'] }));
});

/* Generated by @n1k1t/unit-generator */
it('should use env.target when parameters.target is not provided', async () => {
  const cwd = '/cwd';
  jest.spyOn(process, 'cwd').mockReturnValue(cwd);
  const ignored = [] as any;
  jest.spyOn(utils, 'extractIgnoredPaths').mockResolvedValue(ignored);
  const extracted = [] as any;
  const extractCoberturaItemsSpy = jest.spyOn(utils, 'extractCoberturaItems').mockResolvedValue(extracted);
  jest.spyOn(console, 'table').mockImplementation(() => {});
  env.cobertura = 'cov.xml';
  env.target = 75;
  await analyze();
  expect(extractCoberturaItemsSpy).toHaveBeenCalledWith(env.cobertura, expect.objectContaining({ target: 75 }));
});
