import calculate from './calculate'
import child_process from 'child_process'
import { Cobertura } from '../models'
import env from '../env'
import { TFunction } from '../../types';

/* Generated by @n1k1t/unit-generator */
it('should reject when test command fails', async () => {
  jest.resetModules();
  const execMock = jest.fn((cmd, cb) => cb(new Error('fail')));
  const buildMock = jest.fn(async () => ({ rate: 0.9, timestamp: 1 }));
  jest.doMock('child_process', () => ({ exec: execMock }));
  jest.doMock('../models', () => ({ Cobertura: { build: buildMock } }));
  jest.doMock('../env', () => ({ default: { command: 'jest', cobertura: 'cob.xml' } }));
  const mod = await import('./calculate');
  await expect(mod.default()).rejects.toThrow('fail');
});

/* Generated by @n1k1t/unit-generator */
it('calls exec with env.command and args', async () => {
  const execSpy = jest.spyOn(child_process, 'exec').mockImplementation((cmd, cb) => {
    typeof cb === 'function' && (<TFunction>cb)(null);
    return {} as any;
  });
  env.command = 'mycmd';
  jest.spyOn(Cobertura, 'build').mockResolvedValue({ rate: 0.5, timestamp: 0 } as any);
  await calculate();
  expect(execSpy).toHaveBeenCalledWith('mycmd -- --coverage --forceExit --silent --workerThreads', expect.any(Function));
  execSpy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('prints cobertura rate and formatted timestamp', async () => {
  const now = 1600000000000;
  jest.spyOn(child_process, 'exec').mockImplementation((cmd, cb) => {
    typeof cb === 'function' && (<TFunction>cb)(null);
    return {} as any;
  });
  jest.spyOn(Cobertura, 'build').mockResolvedValue({ rate: 0.75, timestamp: now } as any);
  const tableSpy = jest.spyOn(console, 'table').mockImplementation(() => {});
  await calculate();
  expect(tableSpy).toHaveBeenCalledWith([{ rate: 0.75, updated: new Date(now).toLocaleString() }]);
  tableSpy.mockRestore();
});
