import { Assistant } from '../models';

import * as utils from './utils';
import path from 'path';
import fix from './fix';
import env from '../env';

/* Generated by @n1k1t/unit-generator */
it('should call extractIgnoredPaths with current working directory', async () => {
  const extractIgnoredPathsSpy = jest.spyOn(utils, 'extractIgnoredPaths').mockResolvedValue([]);
  jest.spyOn(utils, 'extractCoberturaItems').mockResolvedValue([]);
  jest.spyOn(utils, 'buildRenderer').mockReturnValue(jest.fn());
  await fix();
  expect(extractIgnoredPathsSpy).toHaveBeenCalledWith(process.cwd());
})

/* Generated by @n1k1t/unit-generator */
it('should call extractCoberturaItems with correct arguments including env cobertura path', async () => {
  const extractCoberturaItemsSpy = jest.spyOn(utils, 'extractCoberturaItems').mockResolvedValue([]);
  jest.spyOn(utils, 'extractIgnoredPaths').mockResolvedValue(['node_modules']);
  jest.spyOn(utils, 'buildRenderer').mockReturnValue(jest.fn());
  const cwd = process.cwd();
  await fix({ limit: 5, all: true, paths: ['src/file.ts'] });
  expect(extractCoberturaItemsSpy).toHaveBeenCalledWith(path.join(cwd, env.cobertura), {
    ignore: ['node_modules'],
    target: Infinity,
    cwd,
    paths: ['src/file.ts'],
    limit: 5,
    all: true
  });
})

/* Generated by @n1k1t/unit-generator */
it('should build assistants for each extracted item with FIX strategy', async () => {
  const items = [{ path: 'file1.ts' }, { path: 'file2.ts' }];
  jest.spyOn(utils, 'extractCoberturaItems').mockResolvedValue(items as any);
  jest.spyOn(utils, 'extractIgnoredPaths').mockResolvedValue([]);
  jest.spyOn(utils, 'buildRenderer').mockReturnValue(jest.fn());
  const assistantBuildSpy = jest.spyOn(Assistant, 'build').mockResolvedValue({ run: jest.fn() } as any);
  await fix({ iterations: 3, model: 'gpt-4' });
  expect(assistantBuildSpy).toHaveBeenCalledWith('file1.ts', expect.objectContaining({
    iterations: 3,
    model: 'gpt-4',
    strategies: ['FIX']
  }));
})

/* Generated by @n1k1t/unit-generator */
it('should call run on each assistant', async () => {
  const runMock = jest.fn().mockResolvedValue(undefined);
  jest.spyOn(utils, 'extractCoberturaItems').mockResolvedValue([{ path: 'file1.ts' }] as any);
  jest.spyOn(utils, 'extractIgnoredPaths').mockResolvedValue([]);
  jest.spyOn(utils, 'buildRenderer').mockReturnValue(jest.fn());
  jest.spyOn(Assistant, 'build').mockResolvedValue({ run: runMock } as any);
  await fix();
  expect(runMock).toHaveBeenCalled();
})

/* Generated by @n1k1t/unit-generator */
it('should call renderer one last time after all assistants finish', async () => {
  const renderMock = jest.fn();
  jest.spyOn(utils, 'buildRenderer').mockReturnValue(renderMock);
  jest.spyOn(utils, 'extractCoberturaItems').mockResolvedValue([]);
  jest.spyOn(utils, 'extractIgnoredPaths').mockResolvedValue([]);
  await fix();
  expect(renderMock).toHaveBeenLastCalledWith([]);
})
