import { Assistant } from '../models';
import generate from './generate';

/* Generated by @n1k1t/unit-generator */
it('should initialize renderer and set interval for rendering', async () => {
  const renderMock = jest.fn();
  jest.spyOn(require('./utils'), 'buildRenderer').mockReturnValue(renderMock);
  jest.spyOn(require('./utils'), 'extractIgnoredPaths').mockResolvedValue([]);
  jest.spyOn(require('./utils'), 'extractCoberturaItems').mockResolvedValue([{ path: 'f.ts', rate: 0 }]);
  jest.spyOn(Assistant, 'build').mockResolvedValue({ run: jest.fn() } as any);
  const setIntervalSpy = jest.spyOn(global, 'setInterval');
  await generate();
  expect(setIntervalSpy).toHaveBeenCalledWith(expect.any(Function), 100);
})

/* Generated by @n1k1t/unit-generator */
it('should call render one last time after all assistants finished', async () => {
  const renderMock = jest.fn();
  jest.spyOn(require('./utils'), 'buildRenderer').mockReturnValue(renderMock);
  jest.spyOn(require('./utils'), 'extractIgnoredPaths').mockResolvedValue([]);
  jest.spyOn(require('./utils'), 'extractCoberturaItems').mockResolvedValue([{ path: 'f.ts', rate: 0 }]);
  const assistant = { run: jest.fn().mockResolvedValue(undefined) };
  jest.spyOn(Assistant, 'build').mockResolvedValue(assistant as any);
  await generate();
  expect(renderMock).toHaveBeenLastCalledWith([assistant]);
})

/* Generated by @n1k1t/unit-generator */
it('should pass model and iterations parameters to Assistant.build', async () => {
  jest.spyOn(require('./utils'), 'extractIgnoredPaths').mockResolvedValue([]);
  jest.spyOn(require('./utils'), 'extractCoberturaItems').mockResolvedValue([{ path: 'f.ts', rate: 0.1 }]);
  const spy = jest.spyOn(Assistant, 'build').mockResolvedValue({ run: jest.fn() } as any);
  await generate({ model: 'test-model', iterations: 10 });
  expect(spy).toHaveBeenCalledWith('f.ts', expect.objectContaining({
    model: 'test-model',
    iterations: 10
  }));
})
