import { calculate, generate, analyze, summary } from './index'

/* Generated by @n1k1t/unit-generator */
it('should export calculate function', () => {
  expect(calculate).toBeDefined();
});

/* Generated by @n1k1t/unit-generator */
it('should export generate function', () => {
  expect(generate).toBeDefined();
});

/* Generated by @n1k1t/unit-generator */
it('should export analyze function', () => {
  expect(analyze).toBeDefined();
});

/* Generated by @n1k1t/unit-generator */
it('should export summary function', () => {
  expect(summary).toBeDefined();
});

/* Generated by @n1k1t/unit-generator */
it('should export exactly 4 functions', () => {
  const exports = { calculate, generate, analyze, summary };
  expect(Object.keys(exports).length).toBe(4);
});
