import summary from './summary';
import path from 'path';
import { Cobertura } from '../models';
import env from '../env';

/* Generated by @n1k1t/unit-generator */
it('should log a table when format is "table"', async () => {
  const mockRate = 0.85;
  const mockTimestamp = Date.now();
  const mockCoberturaInstance = {
    rate: mockRate,
    timestamp: mockTimestamp,
  };

  const consoleTableSpy = jest.spyOn(console, 'table').mockImplementation(() => {});
  const consoleLogSpy = jest.spyOn(console, 'log').mockImplementation(() => {});
  const processCwdSpy = jest.spyOn(process, 'cwd').mockReturnValue('/mock/cwd');
  const coberturaBuildSpy = jest.spyOn(Cobertura, 'build').mockResolvedValue(<any>mockCoberturaInstance);
  const pathJoinSpy = jest.spyOn(path, 'join').mockReturnValue('/mock/cwd/mock-cobertura.xml');

  const originalEnvCobertura = env.cobertura;
  Object.defineProperty(env, 'cobertura', {
    value: 'mock-cobertura.xml',
    writable: true,
    configurable: true,
  });

  await summary({ format: 'table' });

  expect(consoleTableSpy).toHaveBeenCalledTimes(1);
  expect(consoleTableSpy).toHaveBeenCalledWith([{
    rate: mockRate,
    updated: new Date(mockTimestamp).toLocaleString(),
  }]);

  consoleTableSpy.mockRestore();
  consoleLogSpy.mockRestore();
  processCwdSpy.mockRestore();
  coberturaBuildSpy.mockRestore();
  pathJoinSpy.mockRestore();
  Object.defineProperty(env, 'cobertura', {
    value: originalEnvCobertura,
    writable: true,
    configurable: true,
  });
});

/* Generated by @n1k1t/unit-generator */
it('should log the rate when format is not "table"', async () => {
  const mockRate = 0.92;
  const mockTimestamp = Date.now();
  const mockCoberturaInstance = {
    rate: mockRate,
    timestamp: mockTimestamp,
  };

  const consoleTableSpy = jest.spyOn(console, 'table').mockImplementation(() => {});
  const consoleLogSpy = jest.spyOn(console, 'log').mockImplementation(() => {});
  const processCwdSpy = jest.spyOn(process, 'cwd').mockReturnValue('/mock/cwd');
  const coberturaBuildSpy = jest.spyOn(Cobertura, 'build').mockResolvedValue(<any>mockCoberturaInstance);
  const pathJoinSpy = jest.spyOn(path, 'join').mockReturnValue('/mock/cwd/mock-cobertura.xml');

  const originalEnvCobertura = env.cobertura;
  Object.defineProperty(env, 'cobertura', {
    value: 'mock-cobertura.xml',
    writable: true,
    configurable: true,
  });

  await summary({});

  expect(consoleLogSpy).toHaveBeenCalledTimes(1);
  expect(consoleLogSpy).toHaveBeenCalledWith(String(mockRate));

  consoleTableSpy.mockRestore();
  consoleLogSpy.mockRestore();
  processCwdSpy.mockRestore();
  coberturaBuildSpy.mockRestore();
  pathJoinSpy.mockRestore();
  Object.defineProperty(env, 'cobertura', {
    value: originalEnvCobertura,
    writable: true,
    configurable: true,
  });
});

/* Generated by @n1k1t/unit-generator */
it('should throw when Cobertura.build rejects', async () => {
  const error = new Error('build error');
  const coberturaBuildSpy = jest.spyOn(Cobertura, 'build').mockRejectedValue(error);
  const processCwdSpy = jest.spyOn(process, 'cwd').mockReturnValue('/mock/cwd');
  const pathJoinSpy = jest.spyOn(path, 'join').mockReturnValue('/mock/cwd/mock-cobertura.xml');
  const originalEnvCobertura = env.cobertura;
  Object.defineProperty(env, 'cobertura', {
    value: 'mock-cobertura.xml',
    writable: true,
    configurable: true,
  });

  await expect(summary({})).rejects.toThrow('build error');

  coberturaBuildSpy.mockRestore();
  processCwdSpy.mockRestore();
  pathJoinSpy.mockRestore();
  Object.defineProperty(env, 'cobertura', {
    value: originalEnvCobertura,
    writable: true,
    configurable: true,
  });
});
