import fs from 'fs/promises';

import { extractCoberturaItems, extractIgnoredPaths } from './utils';
import { Cobertura, CoberturaItem } from '../models';

/* Generated by @n1k1t/unit-generator */
it('should extract ignored paths from .unitignore when file exists', async () => {
  jest.spyOn(fs, 'readFile').mockResolvedValueOnce('node_modules\ndist\nsrc/**/*.spec.ts');
  const result = await extractIgnoredPaths('/dummy/cwd');
  expect(result).toEqual(['node_modules', 'dist', 'src/**/*.spec.ts']);
});

/* Generated by @n1k1t/unit-generator */
it('should return empty array when .unitignore does not exist', async () => {
  jest.spyOn(fs, 'readFile').mockRejectedValueOnce(new Error('File not found'));
  const result = await extractIgnoredPaths('/dummy/cwd');
  expect(result).toEqual([]);
});

/* Generated by @n1k1t/unit-generator */
it('should extract and filter Cobertura items correctly with default options', async () => {
  const mockItems = [
    new CoberturaItem('/cwd/src/foo.ts', 0.5, [1, 2]),
    new CoberturaItem('/cwd/src/bar.spec.ts', 0.2, [3]),
    new CoberturaItem('/cwd/src/baz.js', 1.0, []),
    new CoberturaItem('/cwd/src/qux.txt', 0.1, [])
  ];
  jest.spyOn(Cobertura, 'build').mockResolvedValueOnce({ items: mockItems } as any);
  const result = await extractCoberturaItems('cobertura.xml', { cwd: '/cwd' });
  expect(result.map(item => item.path)).toEqual(['src/foo.ts']);
});

/* Generated by @n1k1t/unit-generator */
it('should filter out items matching ignore patterns', async () => {
  const mockItems = [
    new CoberturaItem('/cwd/src/foo.ts', 0.5, [1, 2]),
    new CoberturaItem('/cwd/src/bar.ts', 0.5, [1, 2])
  ];
  jest.spyOn(Cobertura, 'build').mockResolvedValueOnce({ items: mockItems } as any);
  const result = await extractCoberturaItems('cobertura.xml', {
    cwd: '/cwd',
    ignore: ['**/bar.ts']
  });
  expect(result.map(item => item.path)).toEqual(['src/foo.ts']);
});

/* Generated by @n1k1t/unit-generator */
it('should limit the number of returned items', async () => {
  const mockItems = [
    new CoberturaItem('/cwd/src/foo.ts', 0.5, [1, 2]),
    new CoberturaItem('/cwd/src/bar.ts', 0.5, [1, 2])
  ];
  jest.spyOn(Cobertura, 'build').mockResolvedValueOnce({ items: mockItems } as any);
  const result = await extractCoberturaItems('cobertura.xml', {
    cwd: '/cwd',
    limit: 1
  });
  expect(result.map(item => item.path)).toEqual(['src/bar.ts']);
});
