import { CoberturaItem } from '../models';
import { extractCoberturaItems, extractIgnoredPaths } from './utils';
import fs from 'fs/promises';
import { Cobertura } from '../models';

/* Generated by @n1k1t/unit-generator */
it('should return an empty array if .unitignore does not exist', async () => {
  jest.spyOn(fs, 'readFile').mockRejectedValueOnce(new Error('File not found'));
  const result = await extractIgnoredPaths('/test-cwd');
  expect(result).toEqual([]);
});

/* Generated by @n1k1t/unit-generator */
it('should read .unitignore and return trimmed, non-empty lines', async () => {
  jest.spyOn(fs, 'readFile').mockResolvedValueOnce('  line1  \nline2\n\n  line3  ');
  const result = await extractIgnoredPaths('/test-cwd');
  expect(result).toEqual(['line1', 'line2', 'line3']);
});

/* Generated by @n1k1t/unit-generator */
it('should assign relative paths to items', async () => {
  const mockAssign = jest.fn();
  jest.spyOn(Cobertura, 'build').mockResolvedValueOnce(<any>{
    items: [
      { path: '/cwd/src/file1.ts', rate: 0.5, assign: mockAssign },
    ],
  });
  await extractCoberturaItems('/coverage.xml', { cwd: '/cwd' });
  expect(mockAssign).toHaveBeenCalledWith({ path: 'src/file1.ts' });
});


/* Generated by @n1k1t/unit-generator */
it('should filter out items with rate >= target', async () => {
  jest.spyOn(Cobertura, 'build').mockResolvedValueOnce(<any>{
    items: [
      { path: '/cwd/file1.ts', rate: 0.9, assign: jest.fn() },
    ],
  });

  const result = await extractCoberturaItems('/coverage.xml', { cwd: '/cwd', target: 0.8 });
  expect(result).toEqual([]);
});

/* Generated by @n1k1t/unit-generator */
it('should filter out .spec files', async () => {
  jest.spyOn(Cobertura, 'build').mockResolvedValueOnce(<any>{
    items: [
      { path: '/cwd/file.spec.ts', rate: 0.5, assign: jest.fn() },
    ],
  });

  const result = await extractCoberturaItems('/coverage.xml', { cwd: '/cwd' });
  expect(result).toEqual([]);
});

/* Generated by @n1k1t/unit-generator */
it('should filter out items not in provided paths when paths option is set', async () => {
  jest.spyOn(Cobertura, 'build').mockResolvedValueOnce(<any>{
    items: [
      { path: '/cwd/src/other.ts', rate: 0.5, assign: jest.fn() },
    ],
  });

  const result = await extractCoberturaItems('/coverage.xml', { cwd: '/cwd', paths: ['src/only.ts'] });
  expect(result).toEqual([]);
});

/* Generated by @n1k1t/unit-generator */
it('should filter out items matching ignore patterns', async () => {
  jest.spyOn(Cobertura, 'build').mockResolvedValueOnce(<any>{
    items: [
      { path: '/cwd/src/file3.ts', rate: 0.5, assign: jest.fn() },
    ],
  });

  const result = await extractCoberturaItems('/coverage.xml', { cwd: '/cwd', ignore: ['**/file3.ts'] });
  expect(result).toEqual([]);
});

/* Generated by @n1k1t/unit-generator */
it('should add missing paths when all option is true using CoberturaItem.build', async () => {
  jest.spyOn(Cobertura, 'build').mockResolvedValueOnce(<any>{
    items: [],
  });

  const buildSpy = jest.spyOn(CoberturaItem, 'build').mockReturnValueOnce(<any>{ path: '/cwd/src/new.ts', rate: 0.2, assign: jest.fn() });

  await extractCoberturaItems('/coverage.xml', { cwd: '/cwd', paths: ['src/new.ts'], all: true });
  expect(buildSpy).toHaveBeenCalledWith('/cwd/src/new.ts');
});

/* Generated by @n1k1t/unit-generator */
it('should sort modules then indexes by rate and apply limit', async () => {
  jest.spyOn(Cobertura, 'build').mockResolvedValueOnce(<any>{
    items: [
      { path: '/cwd/b.ts', rate: 0.1, assign: jest.fn() },
      { path: '/cwd/a.ts', rate: 0.3, assign: jest.fn() },
      { path: '/cwd/index.ts', rate: 0.2, assign: jest.fn() },
    ],
  });

  const result = await extractCoberturaItems('/coverage.xml', { cwd: '/cwd', limit: 2 });
  expect(result.map((r) => r.rate)).toEqual([0.1, 0.3]);
});
