import json2md, { DataObject } from 'json2md';

import { generateObject, NoObjectGeneratedError } from 'ai';
import { createOpenAI } from '@ai-sdk/openai';
import { z } from 'zod';

import { TAssistantSourceTestResult, TAssistantStrategyRunStatus } from '../types';
import { AssistantStrategy } from './model';
import { cast } from '../../../utils';

import env from '../../../env';

const openai = createOpenAI({ apiKey: env.key, baseURL: env.url });

export class AssistantAddStrategy extends AssistantStrategy<'ADD'> {
  public model = openai(this.provided.model ?? env.model, { user: this.source.id });

  public schema = z.object({
    imports: z.array(
      z.string({ description: 'Code of ONLY one import statement, for example: `import ...`' }),
      {
        description: 'List of required entity imports for unit tests',
      }
    ),

    specs: z.array(
      z.object({
        code: z.string({ description: 'Code of ONLY one unit test function, for example: `it(...)`' }),
      }),
      {
        description: 'List of unit tests',
      }
    ).min(1),
  });

  public async run(): Promise<TAssistantStrategyRunStatus> {
    if (!this.source.spec.content.length) {
      return 'SKIPPED';
    }

    const tested = await this.source.test();
    if (tested.status === 'FAILED') {
      return 'SKIPPED';
    }

    const snapshot = this.source.compileSnapshot();

    const generated = await this.generate();
    if (!generated?.specs.length) {
      this.differ();
      return 'EMPTY';
    }

    const imported = await this.injectImports(generated);
    if (imported === 'FAILED') {
      this.differ();
      return imported;
    }

    const result = await this.injectSpecs(generated);
    if (result !== 'DONE') {
      this.differ();
      await this.source.restore(snapshot);
    }

    return result;
  }

  private async injectImports(generated: AssistantAddStrategy['schema']['_type']): Promise<TAssistantStrategyRunStatus> {
    this.source.save();

    const imports = generated.imports.filter((row) => row.includes('import') || row.includes('require'));
    if (!imports.length) {
      return 'EMPTY';
    }

    await this.source.spec.prepend(imports.join('\n')).write();
    const tested = await this.source.test();

    if (tested.status === 'FAILED') {
      await this.source.restore();
      return 'FAILED';
    }

    return 'DONE';
  }

  private async injectSpecs(
    generated: AssistantAddStrategy['schema']['_type'],
    results: TAssistantSourceTestResult[] = []
  ): Promise<TAssistantStrategyRunStatus> {
    if (!generated.specs.length) {
      return 'EMPTY';
    }

    this.source.save();

    await this.source.spec
      .append(`\n/* Generated by @n1k1t/unit-generator */\n${generated.specs[results.length].code.trim()}`)
      .write();

    const tested = await this.source.test();
    if (tested.status === 'FAILED') {
      await this.source.restore();
    }

    return results.length === generated.specs.length - 1
      ? results.concat([tested]).some((result) => result.status === 'PASSED') ? 'DONE' : 'FAILED'
      : this.injectSpecs(generated, results.concat([tested]));
  }

  private async generate(): Promise<AssistantAddStrategy['schema']['_type'] | null> {
    const offset = (this.differation.attempt - 1) * 5;
    const uncovered = offset >= this.source.cobertura.uncovered.length
      ? this.source.cobertura.uncovered.slice(0, 5)
      : this.source.cobertura.uncovered.slice(offset, offset + 5);

    const response = await generateObject({
      prompt: json2md(
        cast<DataObject[]>([
          ...this.context.overview,
          ...this.context.project.concat([
            { h2: '7. Line numbers of code not covered by tests, separated by commas' },
            { p: uncovered.join(', ') },

            { h2: '8. Import declarations already existing in unit tests code' },
            {
              code: {
                language: this.source.spec.lang,
                content: this.source.spec.imports.join('\n'),
              },
            },

            { h2: '9. Helpers and utils already declared in unit tests code' },
            {
              code: {
                language: this.source.spec.lang,
                content: this.source.spec.helpers.join('\n'),
              },
            },
          ]),

          { hr: '' },
          { h1: 'Task' },

          {
            ul: [
              'Analyze the task context described above',
              'Analyze the lines of code that need to be covered by tests',
              'Write additional unit tests only for the uncovered lines of code',
              'Add imports for unit tests only for the uncovered lines of code',
              'DO NOT duplicate import declarations',
            ],
          },
        ])
      ),

      temperature: this.differation.temperature,
      seed: this.differation.seed,

      schema: this.schema,
      model: this.model,
    }).catch((error) => {
      if (error instanceof NoObjectGeneratedError) {
        return null;
      }

      throw error;
    });

    return response?.object ?? null;
  }

  static build(
    source: AssistantStrategy['source'],
    provided: AssistantStrategy['provided'] = {}
  ): AssistantAddStrategy {
    return new AssistantAddStrategy('ADD', source, provided);
  }
}
