import * as ai from 'ai';
import { z } from 'zod';

import { IAssistantModelProvider } from '../router';
import { AssistantAddStrategy } from './add';
import { AssistantSource } from '../source';

/* Generated by @n1k1t/unit-generator */
it('injectImports returns EMPTY when no import lines', async () => {
  const strategy = Object.create((AssistantAddStrategy as any).prototype) as any;
  strategy.source = {
    save: jest.fn(),
    spec: { prepend: jest.fn().mockReturnThis(), write: jest.fn() },
    test: jest.fn().mockResolvedValue({ status: 'PASSED' }),
    restore: jest.fn(),
  };
  const generated = { imports: ['const a = 1'], specs: [] } as any;
  const result = await strategy.injectImports(generated);
  expect(result).toEqual('EMPTY');
});

/* Generated by @n1k1t/unit-generator */
it('injectImports returns FAILED when imports present but tests fail', async () => {
  const strategy = Object.create((AssistantAddStrategy as any).prototype) as any;
  const restore = jest.fn();
  strategy.source = {
    save: jest.fn(),
    spec: { prepend: jest.fn().mockReturnThis(), write: jest.fn() },
    test: jest.fn().mockResolvedValue({ status: 'FAILED' }),
    restore,
  };
  const generated = { imports: ['import x from "y"'], specs: [] } as any;
  const result = await strategy.injectImports(generated);
  expect(result).toEqual('FAILED');
});

/* Generated by @n1k1t/unit-generator */
it('injectSpecs returns EMPTY when no specs provided', async () => {
  const strategy = Object.create((AssistantAddStrategy as any).prototype) as any;
  strategy.source = {
    save: jest.fn(),
    spec: { append: jest.fn().mockReturnThis(), write: jest.fn() },
    test: jest.fn().mockResolvedValue({ status: 'PASSED' }),
    restore: jest.fn(),
  };
  const generated = { imports: [], specs: [] } as any;
  const result = await strategy.injectSpecs(generated);
  expect(result).toEqual('EMPTY');
});

/* Generated by @n1k1t/unit-generator */
it('injectSpecs returns FAILED for single spec when test fails', async () => {
  const strategy = Object.create((AssistantAddStrategy as any).prototype) as any;
  strategy.source = {
    save: jest.fn(),
    spec: { append: jest.fn().mockReturnThis(), write: jest.fn() },
    test: jest.fn().mockResolvedValue({ status: 'FAILED', message: 'error' }),
    restore: jest.fn(),
  };
  strategy.history = { add: jest.fn() };
  const generated = { imports: [], specs: [{ code: "it('a', () => {})" }] } as any;
  const result = await strategy.injectSpecs(generated);
  expect(result).toEqual('FAILED');
});

/* Generated by @n1k1t/unit-generator */
it('injectSpecs returns DONE when at least one of multiple specs passes', async () => {
  const strategy = Object.create((AssistantAddStrategy as any).prototype) as any;
  const testMock = jest.fn()
    .mockResolvedValueOnce({ status: 'FAILED', message: 'error' })
    .mockResolvedValueOnce({ status: 'PASSED' });
  strategy.source = {
    save: jest.fn(),
    spec: { append: jest.fn().mockReturnThis(), write: jest.fn() },
    test: testMock,
    restore: jest.fn(),
  };
  strategy.history = { add: jest.fn() };
  const generated = { imports: [], specs: [{ code: "it('a', () => {})" }, { code: "it('b', () => {})" }] } as any;
  const result = await strategy.injectSpecs(generated);
  expect(result).toEqual('DONE');
});

/* Generated by @n1k1t/unit-generator */
it('run returns SKIPPED when spec content is empty', async () => {
  const strategy = Object.create((AssistantAddStrategy as any).prototype) as any;
  strategy.source = {
    spec: { content: '' },
  };
  const result = await (AssistantAddStrategy as any).prototype.run.call(strategy);
  expect(result).toEqual('SKIPPED');
});

/* Generated by @n1k1t/unit-generator */
it('run returns SKIPPED when initial test fails', async () => {
  const strategy = Object.create((AssistantAddStrategy as any).prototype) as any;
  strategy.source = {
    spec: { content: 'x' },
    test: jest.fn().mockResolvedValue({ status: 'FAILED' }),
  };
  const result = await (AssistantAddStrategy as any).prototype.run.call(strategy);
  expect(result).toEqual('SKIPPED');
});

/* Generated by @n1k1t/unit-generator */
it('injectImports returns DONE when imports present and tests pass', async () => {
  const strategy = Object.create((AssistantAddStrategy as any).prototype) as any;
  strategy.source = {
    save: jest.fn(),
    spec: { prepend: jest.fn().mockReturnThis(), write: jest.fn() },
    test: jest.fn().mockResolvedValue({ status: 'PASSED' }),
    restore: jest.fn(),
  };
  const generated = { imports: ['import x from "y"'], specs: [] } as any;
  const result = await strategy.injectImports(generated);
  expect(result).toEqual('DONE');
});

/* Generated by @n1k1t/unit-generator */
it('run returns EMPTY when generated.specs is empty', async () => {
  const strategy = Object.create((AssistantAddStrategy as any).prototype) as any;
  strategy.source = {
    spec: { content: 'x' },
    test: jest.fn().mockResolvedValue({ status: 'PASSED' }),
    compileSnapshot: jest.fn().mockReturnValue('snap'),
  };
  strategy.differation = { temperature: 0.5, seed: 123, attempt: 1 };
  strategy.generate = jest.fn().mockResolvedValue({ imports: [], specs: [] });
  const result = await (AssistantAddStrategy as any).prototype.run.call(strategy);
  expect(result).toEqual('EMPTY');
});

/* Generated by @n1k1t/unit-generator */
it('run returns FAILED when injectImports returns FAILED', async () => {
  const strategy = Object.create((AssistantAddStrategy as any).prototype) as any;
  strategy.source = {
    spec: { content: 'x' },
    test: jest.fn().mockResolvedValue({ status: 'PASSED' }),
    compileSnapshot: jest.fn().mockReturnValue('snap'),
  };
  strategy.generate = jest.fn().mockResolvedValue({ imports: [], specs: [{ code: "it('a', () => {})" }] });
  strategy.differation = { temperature: 0.5, seed: 123, attempt: 1 };
  strategy.injectImports = jest.fn().mockResolvedValue('FAILED');
  const result = await (AssistantAddStrategy as any).prototype.run.call(strategy);
  expect(result).toEqual('FAILED');
});

/* Generated by @n1k1t/unit-generator */
it('run restores snapshot when injectSpecs returns not DONE', async () => {
  const strategy = Object.create((AssistantAddStrategy as any).prototype) as any;
  const restore = jest.fn();
  strategy.source = {
    spec: { content: 'x' },
    test: jest.fn().mockResolvedValue({ status: 'PASSED' }),
    compileSnapshot: jest.fn().mockReturnValue('snap'),
    restore,
  };
  strategy.differation = { temperature: 0.5, seed: 123, attempt: 1 };
  strategy.generate = jest.fn().mockResolvedValue({ imports: [], specs: [{ code: "it('a', () => {})" }] });
  strategy.injectImports = jest.fn().mockResolvedValue('DONE');
  strategy.injectSpecs = jest.fn().mockResolvedValue('FAILED');
  await (AssistantAddStrategy as any).prototype.run.call(strategy);
  expect(restore).toHaveBeenCalledWith('snap');
});

/* Generated by @n1k1t/unit-generator */
it('should return the correct schema with imports and specs', () => {
  const strategy = AssistantAddStrategy.build({} as AssistantSource, { provider: {} as IAssistantModelProvider });
  expect(strategy.schema).toBeInstanceOf(z.ZodObject);
})

/* Generated by @n1k1t/unit-generator */
it('should have imports property in schema', () => {
  const strategy = AssistantAddStrategy.build({} as AssistantSource, { provider: {} as IAssistantModelProvider });
  expect(strategy.schema.shape).toHaveProperty('imports');
})

/* Generated by @n1k1t/unit-generator */
it('should have specs property in schema', () => {
  const strategy = AssistantAddStrategy.build({} as AssistantSource, { provider: {} as IAssistantModelProvider });
  expect(strategy.schema.shape).toHaveProperty('specs');
})

/* Generated by @n1k1t/unit-generator */
it('should return SKIPPED if source spec content is empty', async () => {
  const source = { spec: { content: '' } } as AssistantSource;
  const strategy = AssistantAddStrategy.build(source, { provider: {} as IAssistantModelProvider });
  const result = await strategy.run();
  expect(result).toBe('SKIPPED');
})

/* Generated by @n1k1t/unit-generator */
it('should return SKIPPED if source test fails', async () => {
  const source = { spec: { content: 'some content' }, test: jest.fn().mockResolvedValue({ status: 'FAILED' }) } as unknown as AssistantSource;
  const strategy = AssistantAddStrategy.build(source, { provider: {} as IAssistantModelProvider });
  const result = await strategy.run();
  expect(result).toBe('SKIPPED');
})

/* Generated by @n1k1t/unit-generator */
it('should return EMPTY if no specs are generated', async () => {
  const source = { spec: { content: 'some content' }, test: jest.fn().mockResolvedValue({ status: 'PASSED' }), compileSnapshot: jest.fn() } as unknown as AssistantSource;
  const strategy = AssistantAddStrategy.build(source, { provider: {} as IAssistantModelProvider });
  jest.spyOn(strategy as any, 'generate').mockResolvedValue({ specs: [] });
  const result = await strategy.run();
  expect(result).toBe('EMPTY');
})

/* Generated by @n1k1t/unit-generator */
it('should return FAILED if injectImports fails', async () => {
  const source = { spec: { content: 'some content' }, test: jest.fn().mockResolvedValue({ status: 'PASSED' }), compileSnapshot: jest.fn() } as unknown as AssistantSource;
  const strategy = AssistantAddStrategy.build(source, { provider: {} as IAssistantModelProvider });
  jest.spyOn(strategy as any, 'generate').mockResolvedValue({ specs: [{ code: 'it()' }], imports: [] });
  jest.spyOn(strategy as any, 'injectImports').mockResolvedValue('FAILED');
  const result = await strategy.run();
  expect(result).toBe('FAILED');
})

/* Generated by @n1k1t/unit-generator */
it('should restore snapshot if injectSpecs does not return DONE', async () => {
  const source = { spec: { content: 'some content' }, test: jest.fn().mockResolvedValue({ status: 'PASSED' }), compileSnapshot: jest.fn().mockReturnValue('snapshot'), restore: jest.fn() } as unknown as AssistantSource;
  const strategy = AssistantAddStrategy.build(source, { provider: {} as IAssistantModelProvider });
  jest.spyOn(strategy as any, 'generate').mockResolvedValue({ specs: [{ code: 'it()' }], imports: ['import x'] });
  jest.spyOn(strategy as any, 'injectImports').mockResolvedValue('DONE');
  jest.spyOn(strategy as any, 'injectSpecs').mockResolvedValue('FAILED');
  await strategy.run();
  expect(source.restore).toHaveBeenCalledWith('snapshot');
})

/* Generated by @n1k1t/unit-generator */
it('should restore source if test fails after prepending imports', async () => {
  const source = { save: jest.fn(), spec: { prepend: jest.fn().mockReturnThis(), write: jest.fn().mockResolvedValue(undefined) }, test: jest.fn().mockResolvedValue({ status: 'FAILED' }), restore: jest.fn().mockResolvedValue(undefined) } as unknown as AssistantSource;
  const strategy = AssistantAddStrategy.build(source, { provider: {} as IAssistantModelProvider });
  const result = await (strategy as any).injectImports({ imports: ['import { x } from "y"'], specs: [] });
  expect(source.restore).toHaveBeenCalled();
})

/* Generated by @n1k1t/unit-generator */
it('should return FAILED if test fails after prepending imports', async () => {
  const source = { save: jest.fn(), spec: { prepend: jest.fn().mockReturnThis(), write: jest.fn().mockResolvedValue(undefined) }, test: jest.fn().mockResolvedValue({ status: 'FAILED' }), restore: jest.fn().mockResolvedValue(undefined) } as unknown as AssistantSource;
  const strategy = AssistantAddStrategy.build(source, { provider: {} as IAssistantModelProvider });
  const result = await (strategy as any).injectImports({ imports: ['import { x } from "y"'], specs: [] });
  expect(result).toBe('FAILED');
})

/* Generated by @n1k1t/unit-generator */
it('should return EMPTY if specs array is empty in injectSpecs', async () => {
  const strategy = AssistantAddStrategy.build({} as AssistantSource, { provider: {} as IAssistantModelProvider });
  const result = await (strategy as any).injectSpecs({ specs: [] });
  expect(result).toBe('EMPTY');
})

/* Generated by @n1k1t/unit-generator */
it('should add to history and restore if test fails in injectSpecs', async () => {
  const source = { save: jest.fn(), spec: { append: jest.fn().mockReturnThis(), write: jest.fn().mockResolvedValue(undefined) }, test: jest.fn().mockResolvedValue({ status: 'FAILED', message: 'error' }), restore: jest.fn().mockResolvedValue(undefined) } as unknown as AssistantSource;
  const strategy = AssistantAddStrategy.build(source, { provider: {} as IAssistantModelProvider });
  await (strategy as any).injectSpecs({ specs: [{ code: 'it()' }] });
  expect(strategy.history.size).toBe(1);
})

/* Generated by @n1k1t/unit-generator */
it('should return DONE if at least one spec passed', async () => {
  const source = { save: jest.fn(), spec: { append: jest.fn().mockReturnThis(), write: jest.fn().mockResolvedValue(undefined) }, test: jest.fn().mockResolvedValue({ status: 'PASSED' }) } as unknown as AssistantSource;
  const strategy = AssistantAddStrategy.build(source, { provider: {} as IAssistantModelProvider });
  const result = await (strategy as any).injectSpecs({ specs: [{ code: 'it()' }] });
  expect(result).toBe('DONE');
})

/* Generated by @n1k1t/unit-generator */
it('should return EMPTY if generated imports list is empty in injectImports', async () => {
  const source = { save: jest.fn() } as any;
  const strategy = AssistantAddStrategy.build(source, { provider: {} as IAssistantModelProvider });
  const result = await (strategy as any).injectImports({ imports: [], specs: [] });
  expect(result).toBe('EMPTY');
})

/* Generated by @n1k1t/unit-generator */
it('should return EMPTY if no imports contain import or require keywords in injectImports', async () => {
  const source = { save: jest.fn() } as any;
  const strategy = AssistantAddStrategy.build(source, { provider: {} as IAssistantModelProvider });
  const result = await (strategy as any).injectImports({ imports: ['const x = 1;'], specs: [] });
  expect(result).toBe('EMPTY');
})

/* Generated by @n1k1t/unit-generator */
it('should return FAILED if testing after injecting imports fails', async () => {
  const source = {
    save: jest.fn(),
    restore: jest.fn(),
    test: jest.fn().mockResolvedValue({ status: 'FAILED' }),
    spec: { prepend: () => ({ write: jest.fn().mockResolvedValue(undefined) }) }
  } as any;
  const strategy = AssistantAddStrategy.build(source, { provider: {} as IAssistantModelProvider });
  const result = await (strategy as any).injectImports({ imports: ["import { x } from 'y'"], specs: [] });
  expect(result).toBe('FAILED');
})
