import { AssistantAddStrategy } from './add';

/* Generated by @n1k1t/unit-generator */
it('should build an instance of AssistantAddStrategy', () => {
  const mockSource = {} as any;
  const mockProvided = {} as any;
  const strategy = AssistantAddStrategy.build(mockSource, mockProvided);
  expect(strategy).toBeInstanceOf(AssistantAddStrategy);
});

/* Generated by @n1k1t/unit-generator */
it('should return a zod schema with imports and specs', () => {
  const mockSource = {} as any;
  const mockProvided = {} as any;
  const strategy = AssistantAddStrategy.build(mockSource, mockProvided);
  const schema = strategy.schema;
  expect(schema.shape).toHaveProperty('imports');
});

/* Generated by @n1k1t/unit-generator */
it('should return SKIPPED if spec content is empty', async () => {
  const mockSource = {
    spec: {
      content: '',
    },
  } as any;
  const mockProvided = {} as any;
  const strategy = AssistantAddStrategy.build(mockSource, mockProvided);
  const result = await strategy.run();
  expect(result).toBe('SKIPPED');
});

/* Generated by @n1k1t/unit-generator */
it('should return SKIPPED if initial test fails', async () => {
  const mockSource = {
    spec: {
      content: 'some content',
    },
    test: jest.fn().mockResolvedValue({ status: 'FAILED' }),
  } as any;
  const mockProvided = {} as any;
  const strategy = AssistantAddStrategy.build(mockSource, mockProvided);
  const result = await strategy.run();
  expect(result).toBe('SKIPPED');
});

/* Generated by @n1k1t/unit-generator */
it('should return EMPTY if injectSpecs is called with no specs', async () => {
  const mockSource = {} as any;
  const mockProvided = {} as any;
  const strategy = AssistantAddStrategy.build(mockSource, mockProvided);
  const result = await strategy['injectSpecs']({ imports: [], specs: [] });
  expect(result).toBe('EMPTY');
});
