import { AssistantAddStrategy } from './add';

/* Generated by @n1k1t/unit-generator */
it('injectImports returns EMPTY when no import lines', async () => {
  const strategy = Object.create((AssistantAddStrategy as any).prototype) as any;
  strategy.source = {
    save: jest.fn(),
    spec: { prepend: jest.fn().mockReturnThis(), write: jest.fn() },
    test: jest.fn().mockResolvedValue({ status: 'PASSED' }),
    restore: jest.fn(),
  };
  const generated = { imports: ['const a = 1'], specs: [] } as any;
  const result = await strategy.injectImports(generated);
  expect(result).toEqual('EMPTY');
});

/* Generated by @n1k1t/unit-generator */
it('injectImports returns FAILED when imports present but tests fail', async () => {
  const strategy = Object.create((AssistantAddStrategy as any).prototype) as any;
  const restore = jest.fn();
  strategy.source = {
    save: jest.fn(),
    spec: { prepend: jest.fn().mockReturnThis(), write: jest.fn() },
    test: jest.fn().mockResolvedValue({ status: 'FAILED' }),
    restore,
  };
  const generated = { imports: ['import x from "y"'], specs: [] } as any;
  const result = await strategy.injectImports(generated);
  expect(result).toEqual('FAILED');
});

/* Generated by @n1k1t/unit-generator */
it('injectSpecs returns EMPTY when no specs provided', async () => {
  const strategy = Object.create((AssistantAddStrategy as any).prototype) as any;
  strategy.source = {
    save: jest.fn(),
    spec: { append: jest.fn().mockReturnThis(), write: jest.fn() },
    test: jest.fn().mockResolvedValue({ status: 'PASSED' }),
    restore: jest.fn(),
  };
  const generated = { imports: [], specs: [] } as any;
  const result = await strategy.injectSpecs(generated);
  expect(result).toEqual('EMPTY');
});

/* Generated by @n1k1t/unit-generator */
it('injectSpecs returns FAILED for single spec when test fails', async () => {
  const strategy = Object.create((AssistantAddStrategy as any).prototype) as any;
  strategy.source = {
    save: jest.fn(),
    spec: { append: jest.fn().mockReturnThis(), write: jest.fn() },
    test: jest.fn().mockResolvedValue({ status: 'FAILED' }),
    restore: jest.fn(),
  };
  const generated = { imports: [], specs: [{ code: "it('a', () => {})" }] } as any;
  const result = await strategy.injectSpecs(generated);
  expect(result).toEqual('FAILED');
});

/* Generated by @n1k1t/unit-generator */
it('injectSpecs returns DONE when at least one of multiple specs passes', async () => {
  const strategy = Object.create((AssistantAddStrategy as any).prototype) as any;
  const testMock = jest.fn()
    .mockResolvedValueOnce({ status: 'FAILED' })
    .mockResolvedValueOnce({ status: 'PASSED' });
  strategy.source = {
    save: jest.fn(),
    spec: { append: jest.fn().mockReturnThis(), write: jest.fn() },
    test: testMock,
    restore: jest.fn(),
  };
  const generated = { imports: [], specs: [{ code: "it('a', () => {})" }, { code: "it('b', () => {})" }] } as any;
  const result = await strategy.injectSpecs(generated);
  expect(result).toEqual('DONE');
});

/* Generated by @n1k1t/unit-generator */
it('run returns SKIPPED when spec content is empty', async () => {
  const strategy = Object.create((AssistantAddStrategy as any).prototype) as any;
  strategy.source = {
    spec: { content: '' },
  };
  const result = await (AssistantAddStrategy as any).prototype.run.call(strategy);
  expect(result).toEqual('SKIPPED');
});

/* Generated by @n1k1t/unit-generator */
it('run returns SKIPPED when initial test fails', async () => {
  const strategy = Object.create((AssistantAddStrategy as any).prototype) as any;
  strategy.source = {
    spec: { content: 'x' },
    test: jest.fn().mockResolvedValue({ status: 'FAILED' }),
  };
  const result = await (AssistantAddStrategy as any).prototype.run.call(strategy);
  expect(result).toEqual('SKIPPED');
});

/* Generated by @n1k1t/unit-generator */
it('injectImports returns DONE when imports present and tests pass', async () => {
  const strategy = Object.create((AssistantAddStrategy as any).prototype) as any;
  strategy.source = {
    save: jest.fn(),
    spec: { prepend: jest.fn().mockReturnThis(), write: jest.fn() },
    test: jest.fn().mockResolvedValue({ status: 'PASSED' }),
    restore: jest.fn(),
  };
  const generated = { imports: ['import x from "y"'], specs: [] } as any;
  const result = await strategy.injectImports(generated);
  expect(result).toEqual('DONE');
});

/* Generated by @n1k1t/unit-generator */
it('run returns EMPTY when generated.specs is empty', async () => {
  const strategy = Object.create((AssistantAddStrategy as any).prototype) as any;
  strategy.source = {
    spec: { content: 'x' },
    test: jest.fn().mockResolvedValue({ status: 'PASSED' }),
    compileSnapshot: jest.fn().mockReturnValue('snap'),
  };
  strategy.differation = { temperature: 0.5, seed: 123, attempt: 1 };
  strategy.generate = jest.fn().mockResolvedValue({ imports: [], specs: [] });
  const result = await (AssistantAddStrategy as any).prototype.run.call(strategy);
  expect(result).toEqual('EMPTY');
});

/* Generated by @n1k1t/unit-generator */
it('run returns FAILED when injectImports returns FAILED', async () => {
  const strategy = Object.create((AssistantAddStrategy as any).prototype) as any;
  strategy.source = {
    spec: { content: 'x' },
    test: jest.fn().mockResolvedValue({ status: 'PASSED' }),
    compileSnapshot: jest.fn().mockReturnValue('snap'),
  };
  strategy.generate = jest.fn().mockResolvedValue({ imports: [], specs: [{ code: "it('a', () => {})" }] });
  strategy.differation = { temperature: 0.5, seed: 123, attempt: 1 };
  strategy.injectImports = jest.fn().mockResolvedValue('FAILED');
  const result = await (AssistantAddStrategy as any).prototype.run.call(strategy);
  expect(result).toEqual('FAILED');
});

/* Generated by @n1k1t/unit-generator */
it('run restores snapshot when injectSpecs returns not DONE', async () => {
  const strategy = Object.create((AssistantAddStrategy as any).prototype) as any;
  const restore = jest.fn();
  strategy.source = {
    spec: { content: 'x' },
    test: jest.fn().mockResolvedValue({ status: 'PASSED' }),
    compileSnapshot: jest.fn().mockReturnValue('snap'),
    restore,
  };
  strategy.differation = { temperature: 0.5, seed: 123, attempt: 1 };
  strategy.generate = jest.fn().mockResolvedValue({ imports: [], specs: [{ code: "it('a', () => {})" }] });
  strategy.injectImports = jest.fn().mockResolvedValue('DONE');
  strategy.injectSpecs = jest.fn().mockResolvedValue('FAILED');
  await (AssistantAddStrategy as any).prototype.run.call(strategy);
  expect(restore).toHaveBeenCalledWith('snap');
});
