import { AssistantFixStrategy } from './fix';

/* Generated by @n1k1t/unit-generator */
it('injectImports returns EMPTY when no import lines', async () => {
  const inst: any = Object.create((AssistantFixStrategy as any).prototype);
  inst.source = { spec: { prepend: jest.fn(), write: jest.fn(), content: '' } };
  const generated = { imports: ['something'], fixes: [] };
  const result = await (AssistantFixStrategy as any).prototype.injectImports.call(inst, generated);
  expect(result).toEqual('EMPTY');
});

/* Generated by @n1k1t/unit-generator */
it('injectImports returns DONE when import lines present', async () => {
  const writeMock = jest.fn().mockResolvedValue(undefined);
  const prependMock = jest.fn().mockReturnValue({ write: writeMock });
  const inst: any = Object.create((AssistantFixStrategy as any).prototype);
  inst.source = { spec: { prepend: prependMock, write: jest.fn(), content: '' } };
  const generated = { imports: ["import foo from 'bar';"], fixes: [] };
  const result = await (AssistantFixStrategy as any).prototype.injectImports.call(inst, generated);
  expect(result).toEqual('DONE');
});

/* Generated by @n1k1t/unit-generator */
it('injectFixes writes modified content and returns DONE when tests pass', async () => {
  const writeMock = jest.fn().mockResolvedValue(undefined);
  const content = 'line1\nline2\nline3';
  const inst: any = Object.create((AssistantFixStrategy as any).prototype);
  inst.source = { spec: { content, write: writeMock }, test: jest.fn().mockResolvedValue({ status: 'PASSED' }) };
  const generated = { fixes: [{ code: 'new1\nnew2', start: 2, end: 3 }], imports: [] };
  const result = await (AssistantFixStrategy as any).prototype.injectFixes.call(inst, generated);
  expect(result).toEqual('DONE');
});

/* Generated by @n1k1t/unit-generator */
it('injectFixes returns FAILED when tests still fail', async () => {
  const writeMock = jest.fn().mockResolvedValue(undefined);
  const content = 'a\nb\nc';
  const inst: any = Object.create((AssistantFixStrategy as any).prototype);
  inst.source = { spec: { content, write: writeMock }, test: jest.fn().mockResolvedValue({ status: 'FAILED' }) };
  const generated = { fixes: [{ code: 'x', start: 1, end: 2 }], imports: [] };
  const result = await (AssistantFixStrategy as any).prototype.injectFixes.call(inst, generated);
  expect(result).toEqual('FAILED');
});


/* Generated by @n1k1t/unit-generator */
it('run returns SKIPPED when spec content is empty', async () => {
  const inst: any = Object.create((AssistantFixStrategy as any).prototype);
  inst.source = { spec: { content: '' } };
  const result = await (AssistantFixStrategy as any).prototype.run.call(inst);
  expect(result).toEqual('SKIPPED');
});

/* Generated by @n1k1t/unit-generator */
it('run returns SKIPPED when tests did not fail', async () => {
  const inst: any = Object.create((AssistantFixStrategy as any).prototype);
  inst.source = {
    spec: { content: 'x' },
    test: jest.fn().mockResolvedValue({ status: 'PASSED' }),
  };
  inst.generate = jest.fn();
  inst.injectImports = jest.fn();
  inst.injectFixes = jest.fn();
  const result = await (AssistantFixStrategy as any).prototype.run.call(inst);
  expect(inst.source.test).toHaveBeenCalled();
  expect(result).toEqual('SKIPPED');
});

/* Generated by @n1k1t/unit-generator */
it('run calls restore when injectFixes not DONE and returns its result', async () => {
  const inst: any = Object.create((AssistantFixStrategy as any).prototype);
  inst.parameters = { temperature: 0.5, seed: 0 };
  const snapshot = { s: true };
  const generated = { imports: [], fixes: [{ code: 'x', start: 1, end: 2 }] };
  inst.source = {
    spec: { content: 'x', prepend: jest.fn(), write: jest.fn() },
    test: jest.fn().mockResolvedValue({ status: 'FAILED', message: 'err' }),
    compileSnapshot: jest.fn().mockReturnValue(snapshot),
    restore: jest.fn().mockResolvedValue(undefined),
    id: 'user-id',
  };
  inst.generate = jest.fn().mockResolvedValue(generated);
  inst.injectImports = jest.fn().mockResolvedValue('DONE');
  inst.injectFixes = jest.fn().mockResolvedValue('FAILED');
  const result = await (AssistantFixStrategy as any).prototype.run.call(inst);
  expect(inst.generate).toHaveBeenCalledWith('err');
  expect(inst.source.restore).toHaveBeenCalledWith(snapshot);
  expect(result).toEqual('FAILED');
});


/* Generated by @n1k1t/unit-generator */
it('run returns EMPTY when generate returns no fixes', async () => {
  const inst: any = Object.create((AssistantFixStrategy as any).prototype);
  inst.source = {
    spec: { content: 'x' },
    test: jest.fn().mockResolvedValue({ status: 'FAILED', message: 'err' }),
    compileSnapshot: jest.fn(),
  };
  inst.generate = jest.fn().mockResolvedValue({ imports: [], fixes: [] });
  inst.differ = jest.fn();
  const result = await (AssistantFixStrategy as any).prototype.run.call(inst);
  expect(result).toEqual('EMPTY');
});

/* Generated by @n1k1t/unit-generator */
it('run calls differ when no fixes generated', async () => {
  const inst: any = Object.create((AssistantFixStrategy as any).prototype);
  inst.source = {
    spec: { content: 'content' },
    test: jest.fn().mockResolvedValue({ status: 'FAILED', message: 'msg' }),
    compileSnapshot: jest.fn(),
  };
  inst.generate = jest.fn().mockResolvedValue({ imports: [], fixes: [] });
  inst.differ = jest.fn();
  await (AssistantFixStrategy as any).prototype.run.call(inst);
  expect(inst.differ).toHaveBeenCalled();
});

/* Generated by @n1k1t/unit-generator */
it('generate returns null when generateObject throws NoObjectGeneratedError', async () => {
  jest.resetModules();
  jest.mock('ai', () => {
    class NoObjectGeneratedError extends Error {}
    return {
      generateObject: jest.fn().mockRejectedValue(new NoObjectGeneratedError()),
      NoObjectGeneratedError,
    };
  });
  const { AssistantFixStrategy } = require('./fix');
  const inst: any = Object.create((AssistantFixStrategy as any).prototype);
  inst.context = { overview: [], project: [] };
  inst.source = { spec: { lang: 'ts', content: 'x' } };
  inst.parameters = { temperature: 0, seed: 0 };
  const result = await (AssistantFixStrategy as any).prototype.generate.call(inst, 'msg');
  expect(result).toBeNull();
});

/* Generated by @n1k1t/unit-generator */
it('generate returns object when generateObject resolves', async () => {
  jest.resetModules();
  const expected = { imports: ['import a'], fixes: [{ code: 'c', start: 1, end: 2 }] };
  jest.mock('ai', () => ({
    generateObject: jest.fn().mockResolvedValue({ object: expected }),
    NoObjectGeneratedError: class NoObjectGeneratedError extends Error {},
  }));
  const { AssistantFixStrategy } = require('./fix');
  const inst: any = Object.create((AssistantFixStrategy as any).prototype);
  inst.context = { overview: [], project: [] };
  inst.source = { spec: { lang: 'ts', content: 'x' } };
  inst.parameters = { temperature: 0, seed: 0 };
  const result = await (AssistantFixStrategy as any).prototype.generate.call(inst, 'msg');
  expect(result).toEqual(expected);
});
