import { AssistantFixStrategy } from './fix';
import { z } from 'zod';

/* Generated by @n1k1t/unit-generator */
it('should return SKIPPED if spec content is empty', async () => {
  const source = {
    tree: [],
    code: { path: 'path', lang: 'ts', content: '' },
    spec: { content: '' }
  } as any;
  const strategy = new AssistantFixStrategy('FIX', source, { provider: {} as any });
  const result = await strategy.run();
  expect(result).toBe('SKIPPED');
})

/* Generated by @n1k1t/unit-generator */
it('should return SKIPPED if source test status is not FAILED', async () => {
  const source = {
    tree: [],
    code: { path: 'path', lang: 'ts', content: '' },
    spec: { content: 'some content' },
    test: jest.fn().mockResolvedValue({ status: 'PASSED' })
  } as any;
  const strategy = new AssistantFixStrategy('FIX', source, { provider: {} as any });
  const result = await strategy.run();
  expect(result).toBe('SKIPPED');
})

/* Generated by @n1k1t/unit-generator */
it('should return EMPTY if no tests are generated', async () => {
  const source = {
    tree: [],
    code: { path: 'path', lang: 'ts', content: '' },
    spec: { content: 'some content' },
    test: jest.fn().mockResolvedValue({ status: 'FAILED', message: 'error' }),
    compileSnapshot: jest.fn()
  } as any;
  const strategy = new AssistantFixStrategy('FIX', source, { provider: {} as any });
  jest.spyOn(strategy as any, 'generate').mockResolvedValue(null);
  const result = await strategy.run();
  expect(result).toBe('EMPTY');
})

/* Generated by @n1k1t/unit-generator */
it('should return EMPTY if generated tests array is empty', async () => {
  const source = {
    tree: [],
    code: { path: 'path', lang: 'ts', content: '' },
    spec: { content: 'some content' },
    test: jest.fn().mockResolvedValue({ status: 'FAILED', message: 'error' }),
    compileSnapshot: jest.fn()
  } as any;
  const strategy = new AssistantFixStrategy('FIX', source, { provider: {} as any });
  jest.spyOn(strategy as any, 'generate').mockResolvedValue({ tests: [] });
  const result = await strategy.run();
  expect(result).toBe('EMPTY');
})

/* Generated by @n1k1t/unit-generator */
it('should call prepend and write when injecting imports', async () => {
  const source = {
    tree: [],
    code: { path: 'path', lang: 'ts', content: '' },
    spec: {
      prepend: jest.fn().mockReturnThis(),
      write: jest.fn().mockResolvedValue(undefined)
    }
  } as any;
  const strategy = new AssistantFixStrategy('FIX', source, { provider: {} as any });
  const generated = { imports: ["import { a } from 'b'"], tests: [] };
  await (strategy as any).injectImports(generated);
  expect(source.spec.prepend).toHaveBeenCalledWith("import { a } from 'b'");
})

/* Generated by @n1k1t/unit-generator */
it('should return EMPTY from injectImports if no valid imports are provided', async () => {
  const source = {
    tree: [],
    code: { path: 'path', lang: 'ts', content: '' }
  } as any;
  const strategy = new AssistantFixStrategy('FIX', source, { provider: {} as any });
  const result = await (strategy as any).injectImports({ imports: ['invalid'], tests: [] });
  expect(result).toBe('EMPTY');
})

/* Generated by @n1k1t/unit-generator */
it('should call restore if injectFixes does not return DONE', async () => {
  const source = {
    tree: [],
    code: { path: 'path', lang: 'ts', content: '' },
    spec: { content: 'some content', tests: [{ title: 't' }] },
    test: jest.fn().mockResolvedValue({ status: 'FAILED', message: 'error' }),
    compileSnapshot: jest.fn().mockReturnValue('snapshot'),
    restore: jest.fn().mockResolvedValue(undefined)
  } as any;
  const strategy = new AssistantFixStrategy('FIX', source, { provider: {} as any });
  jest.spyOn(strategy as any, 'generate').mockResolvedValue({ tests: [{ title: 't', content: 'c' }], imports: ["import 'a'"] });
  jest.spyOn(strategy as any, 'injectImports').mockResolvedValue('DONE');
  jest.spyOn(strategy as any, 'injectFixes').mockResolvedValue('FAILED');
  await strategy.run();
  expect(source.restore).toHaveBeenCalledWith('snapshot');
})

/* Generated by @n1k1t/unit-generator */
it('should return DONE from injectFixes if at least one test passed', async () => {
  const source = {
    tree: [],
    code: { path: 'path', lang: 'ts', content: '' },
    save: jest.fn(),
    spec: {
      tests: [{ title: 'test1', content: 'old' }],
      replace: jest.fn(),
      write: jest.fn()
    },
    test: jest.fn().mockResolvedValue({ status: 'PASSED' })
  } as any;
  const strategy = new AssistantFixStrategy('FIX', source, { provider: {} as any });
  const result = await (strategy as any).injectFixes({ tests: [{ title: 'test1', content: 'new' }] });
  expect(result).toBe('DONE');
})

/* Generated by @n1k1t/unit-generator */
it('should return FAILED from injectFixes if all tests failed', async () => {
  const source = {
    tree: [],
    code: { path: 'path', lang: 'ts', content: '' },
    save: jest.fn(),
    restore: jest.fn(),
    spec: {
      tests: [{ title: 'test1', content: 'old' }],
      replace: jest.fn(),
      write: jest.fn()
    },
    test: jest.fn().mockResolvedValue({ status: 'FAILED' })
  } as any;
  const strategy = new AssistantFixStrategy('FIX', source, { provider: {} as any });
  const result = await (strategy as any).injectFixes({ tests: [{ title: 'test1', content: 'new' }] });
  expect(result).toBe('FAILED');
})

/* Generated by @n1k1t/unit-generator */
it('should skip test if title is not found in spec during injectFixes', async () => {
  const source = {
    tree: [],
    code: { path: 'path', lang: 'ts', content: '' },
    save: jest.fn(),
    spec: { tests: [] }
  } as any;
  const strategy = new AssistantFixStrategy('FIX', source, { provider: {} as any });
  const result = await (strategy as any).injectFixes({ tests: [{ title: 'missing', content: 'new' }] });
  expect(result).toBe('FAILED');
})

/* Generated by @n1k1t/unit-generator */
it('should define a schema with imports and tests', () => {
  const source = {
    tree: [],
    code: { path: 'path', lang: 'ts', content: '' },
    spec: { tests: [{ title: 't1' }] }
  } as any;
  const strategy = new AssistantFixStrategy('FIX', source, { provider: {} as any });
  expect(strategy.schema.shape).toHaveProperty('imports');
})

/* Generated by @n1k1t/unit-generator */
it('should define a schema where tests is an array', () => {
  const source = {
    tree: [],
    code: { path: 'path', lang: 'ts', content: '' },
    spec: { tests: [{ title: 't1' }] }
  } as any;
  const strategy = new AssistantFixStrategy('FIX', source, { provider: {} as any });
  expect(strategy.schema.shape.tests).toBeInstanceOf(z.ZodArray);
})

/* Generated by @n1k1t/unit-generator */
it('should build an instance using static build method', () => {
  const source = {
    tree: [],
    code: { path: 'path', lang: 'ts', content: '' }
  } as any;
  const provider = {} as any;
  const instance = AssistantFixStrategy.build(source, { provider });
  expect(instance).toBeInstanceOf(AssistantFixStrategy);
})

/* Generated by @n1k1t/unit-generator */
it('should have name FIX when built', () => {
  const source = {
    tree: [],
    code: { path: 'path', lang: 'ts', content: '' }
  } as any;
  const instance = AssistantFixStrategy.build(source, { provider: {} as any });
  expect(instance.name).toBe('FIX');
})

/* Generated by @n1k1t/unit-generator */
it('should return SKIPPED in run if spec content is empty', async () => {
  const mockSource = { spec: { content: '' } };
  const mockProvided = { provider: { model: {}, options: {} } };
  const strategy = AssistantFixStrategy.build(mockSource as any, mockProvided as any);
  const result = await strategy.run();
  expect(result).toBe('SKIPPED');
});

/* Generated by @n1k1t/unit-generator */
it('should return SKIPPED in run if test status is not FAILED', async () => {
  const mockSource = { spec: { content: 'some' }, test: jest.fn().mockResolvedValue({ status: 'PASSED' }) };
  const mockProvided = { provider: { model: {}, options: {} } };
  const strategy = AssistantFixStrategy.build(mockSource as any, mockProvided as any);
  const result = await strategy.run();
  expect(result).toBe('SKIPPED');
});

/* Generated by @n1k1t/unit-generator */
it('should return EMPTY in run if generated tests are empty', async () => {
  const mockSource = { spec: { content: 'some' }, test: jest.fn().mockResolvedValue({ status: 'FAILED', message: 'err' }), compileSnapshot: jest.fn() };
  const mockProvided = { provider: { model: {}, options: {} } };
  const strategy = AssistantFixStrategy.build(mockSource as any, mockProvided as any);
  jest.spyOn(strategy as any, 'generate').mockResolvedValue({ tests: [] });
  const result = await strategy.run();
  expect(result).toBe('EMPTY');
});

/* Generated by @n1k1t/unit-generator */
it('should return EMPTY in injectImports if no imports found', async () => {
  const strategy = AssistantFixStrategy.build({} as any, {} as any);
  const result = await (strategy as any).injectImports({ imports: ['const x = 1;'] });
  expect(result).toBe('EMPTY');
});

/* Generated by @n1k1t/unit-generator */
it('should continue in injectFixes if test is not found', async () => {
  const mockSource = { spec: { tests: [] }, save: jest.fn() };
  const strategy = AssistantFixStrategy.build(mockSource as any, {} as any);
  const result = await (strategy as any).injectFixes({ tests: [{ title: 'missing', content: '' }] });
  expect(result).toBe('FAILED');
});

/* Generated by @n1k1t/unit-generator */
it('should restore source in run if result is not DONE', async () => {
  const mockSource = { spec: { content: 'some' }, test: jest.fn().mockResolvedValue({ status: 'FAILED' }), compileSnapshot: jest.fn().mockReturnValue('snap'), restore: jest.fn() };
  const strategy = AssistantFixStrategy.build(mockSource as any, { provider: {} } as any);
  jest.spyOn(strategy as any, 'generate').mockResolvedValue({ tests: [{ title: 't', content: 'c' }], imports: [] });
  jest.spyOn(strategy as any, 'injectImports').mockResolvedValue('DONE');
  jest.spyOn(strategy as any, 'injectFixes').mockResolvedValue('FAILED');
  await strategy.run();
  expect(mockSource.restore).toHaveBeenCalledWith('snap');
});

/* Generated by @n1k1t/unit-generator */
it('should return EMPTY if generated tests list is empty', async () => {
  const mockSource = {
    spec: { content: 'some content' },
    test: jest.fn().mockResolvedValue({ status: 'FAILED', message: 'fail' }),
    compileSnapshot: jest.fn()
  };
  const strategy = AssistantFixStrategy.build(mockSource as any, {} as any);
  jest.spyOn(strategy as any, 'generate').mockResolvedValue({ tests: [] });

  const result = await strategy.run();

  expect(result).toBe('EMPTY');
})
