const index = require('./index');

/* Generated by @n1k1t/unit-generator */
it('should import the main module successfully', () => {
  expect(index).toBeDefined();
});

/* Generated by @n1k1t/unit-generator */
it('should re-export content from other modules', () => {
  expect(Object.keys(index).length).toBeGreaterThan(0);
});
