import { jest } from '@jest/globals';
import { AssistantInitStrategy } from './init';

/* Generated by @n1k1t/unit-generator */
it('should return SKIPPED when spec already has content', async () => {
  const fake = { source: { spec: { content: 'existing' } } } as any;
  const result = await AssistantInitStrategy.prototype.run.call(fake);
  expect(result).toEqual('SKIPPED');
});

/* Generated by @n1k1t/unit-generator */
it('should return FAILED when injectSpecs returns FAILED after imports DONE', async () => {
  const fake = {
    source: {
      spec: { content: '' },
      compileSnapshot: () => 'snap',
      restore: async () => {},
    },
    generate: async () => ({
      imports: ["import a from 'b'"],
      specs: [{ code: 'it(\'p\',()=>{})' }, { code: 'it(\'q\',()=>{})' }],
    }),
    injectImports: async () => 'DONE',
    injectSpecs: async () => 'FAILED',
    differ: () => {},
  } as any;
  const result = await AssistantInitStrategy.prototype.run.call(fake);
  expect(result).toEqual('FAILED');
});

/* Generated by @n1k1t/unit-generator */
it('should return EMPTY when generate returns null', async () => {
  const fake = {
    source: {
      spec: { content: '' },
      compileSnapshot: () => 'snap',
      restore: async () => {},
      save: () => {},
      test: async () => ({ status: 'PASSED' }),
    },
    generate: async () => null,
    differ: () => {},
  } as any;
  const result = await AssistantInitStrategy.prototype.run.call(fake);
  expect(result).toEqual('EMPTY');
})

/* Generated by @n1k1t/unit-generator */
it('should return EMPTY when injectImports returns not DONE', async () => {
  const fake = {
    source: {
      spec: { content: '' },
      compileSnapshot: () => 'snap',
      restore: async () => {},
    },
    generate: async () => ({
      imports: ["import a from 'b'"],
      specs: [{ code: "it('p',()=>{})" }],
    }),
    injectImports: async () => 'EMPTY',
    differ: jest.fn(),
  } as any;
  const result = await AssistantInitStrategy.prototype.run.call(fake);
  expect(result).toEqual('EMPTY');
});

/* Generated by @n1k1t/unit-generator */
it('should call differ when injectImports returns not DONE', async () => {
  const fake = {
    source: {
      spec: { content: '' },
      compileSnapshot: () => 'snap',
      restore: async () => {},
    },
    generate: async () => ({
      imports: ["import a from 'b'"],
      specs: [{ code: "it('p',()=>{})" }],
    }),
    injectImports: async () => 'FAILED',
    differ: jest.fn(),
  } as any;
  await AssistantInitStrategy.prototype.run.call(fake);
  expect(fake.differ).toHaveBeenCalled();
});

/* Generated by @n1k1t/unit-generator */
it('should call save when injectImports has no valid imports', async () => {
  const { AssistantInitStrategy } = require('./init');
  const fakeSource = { save: jest.fn() } as any;
  const generated = { imports: ['nope'], specs: [] } as any;
  await AssistantInitStrategy.prototype.injectImports.call({ source: fakeSource }, generated);
  expect(fakeSource.save).toHaveBeenCalled();
});

/* Generated by @n1k1t/unit-generator */
it('should return EMPTY when injectSpecs is called with only one spec', async () => {
  const fakeSource = {} as any;
  const generated = { specs: [{ code: "it('p',()=>{})" }] } as any;
  const result = await AssistantInitStrategy.prototype['injectSpecs'].call({ source: fakeSource } as any, generated);
  expect(result).toEqual('EMPTY');
});

/* Generated by @n1k1t/unit-generator */
it('should return DONE when second spec test passes', async () => {
  const fakeSource = {
    save: jest.fn(),
    spec: {
      append: jest.fn().mockReturnThis(),
      write: jest.fn().mockResolvedValue(<never>undefined),
    },
    test: async () => ({ status: 'PASSED' }),
  } as any;

  const generated = {
    specs: [{ code: "it('p',()=>{})" }, { code: "it('q',()=>{})" }],
  } as any;

  const result = await AssistantInitStrategy.prototype['injectSpecs'].call({ source: fakeSource } as any, generated);
  expect(result).toEqual('DONE');
});

/* Generated by @n1k1t/unit-generator */
it('should call restore when tested status is FAILED in injectSpecs', async () => {
  const fakeSource = {
    save: jest.fn(),
    spec: {
      append: jest.fn().mockReturnThis(),
      write: jest.fn().mockResolvedValue(<never>undefined),
    },
    test: async () => ({ status: 'FAILED' }),
    restore: jest.fn(),
  } as any;

  const generated = {
    specs: [{ code: "it('p',()=>{})" }, { code: "it('q',()=>{})" }],
  } as any;

  await AssistantInitStrategy.prototype['injectSpecs'].call({ source: fakeSource } as any, generated);
  expect(fakeSource.restore).toHaveBeenCalled();
});

/* Generated by @n1k1t/unit-generator */
it('should call write when injectImports has valid imports', async () => {
  const fakeSource = {
    save: jest.fn(),
    spec: {
      prepend: jest.fn().mockReturnThis(),
      append: jest.fn().mockReturnThis(),
      write: jest.fn().mockResolvedValue(<never>undefined),
    },
    test: async () => ({ status: 'PASSED' }),
    restore: jest.fn(),
  } as any;

  const generated = { imports: ["import a from 'b'"], specs: [{ code: "it('p',()=>{})" }] } as any;

  await AssistantInitStrategy.prototype['injectImports'].call({ source: fakeSource } as any, generated);
  expect(fakeSource.spec.write).toHaveBeenCalled();
});

/* Generated by @n1k1t/unit-generator */
it('should call test when injectImports has valid imports', async () => {
  const fakeSource = {
    save: jest.fn(),
    spec: {
      prepend: jest.fn().mockReturnThis(),
      append: jest.fn().mockReturnThis(),
      write: jest.fn().mockResolvedValue(<never>undefined),
    },
    test: jest.fn().mockResolvedValue(<never>{ status: 'PASSED' }),
    restore: jest.fn(),
  } as any;

  const generated = { imports: ["import a from 'b'"], specs: [{ code: "it('p',()=>{})" }] } as any;

  await AssistantInitStrategy.prototype['injectImports'].call({ source: fakeSource } as any, generated);
  expect(fakeSource.test).toHaveBeenCalled();
});

/* Generated by @n1k1t/unit-generator */
it('should return FAILED when tested status is FAILED in injectImports', async () => {
  const fakeSource = {
    save: jest.fn(),
    spec: {
      prepend: jest.fn().mockReturnThis(),
      append: jest.fn().mockReturnThis(),
      write: jest.fn().mockResolvedValue(<never>undefined),
    },
    test: jest.fn().mockResolvedValue(<never>{ status: 'FAILED' }),
    restore: jest.fn(),
  } as any;

  const generated = { imports: ["import a from 'b'"], specs: [{ code: "it('p',()=>{})" }] } as any;

  const result = await AssistantInitStrategy.prototype['injectImports'].call({ source: fakeSource } as any, generated);
  expect(result).toEqual('FAILED');
});

/* Generated by @n1k1t/unit-generator */
it('sets model using provided.model and source id', async () => {
  jest.resetModules();
  jest.doMock('../../../env', () => ({ default: { key: 'k', url: 'u', model: 'env-model' } }));
  jest.doMock('@ai-sdk/openai', () => ({
    createOpenAI: (opts: any) => (modelArg: any, opts2: any) => ({ modelArg, opts2 })
  }));
  jest.doMock('./model', () => ({
    AssistantStrategy: class { constructor(public type: any, public source: any, public provided: any) {} }
  }));

  const { AssistantInitStrategy } = require('./init');
  const source = { id: 'src-id' };
  const instance = AssistantInitStrategy.build(source, { model: 'provided-model' });
  expect(instance.model.modelArg).toEqual('provided-model');
});

/* Generated by @n1k1t/unit-generator */
it('injectImports returns EMPTY when no import statements present', async () => {
  jest.resetModules();
  jest.doMock('../../../env', () => ({ default: { key: 'k', url: 'u', model: 'env-model' } }));
  jest.doMock('./model', () => ({
    AssistantStrategy: class { constructor(public type: any, public source: any, public provided: any) {} }
  }));
  jest.doMock('@ai-sdk/openai', () => ({ createOpenAI: () => () => {} }));
  const { AssistantInitStrategy } = require('./init');
  const source = {
    save: jest.fn(),
    spec: {
      prepend: jest.fn().mockReturnThis(),
      append: jest.fn().mockReturnThis(),
      write: jest.fn()
    },
    id: 'src'
  };
  const instance = AssistantInitStrategy.build(source, {});
  const result = await instance['injectImports']({ imports: ['const a = 1'], specs: [{ code: 'it()' }] });
  expect(result).toEqual('EMPTY');
});
