import { z } from 'zod';
import { AssistantInitStrategy } from './init';

/* Generated by @n1k1t/unit-generator */
it('should return SKIPPED if source spec content is not empty', async () => {
  const source = { spec: { content: 'existing tests' } } as any;
  const strategy = new AssistantInitStrategy('INIT', source, { provider: {} as any });
  const result = await strategy.run();
  expect(result).toBe('SKIPPED');
})

/* Generated by @n1k1t/unit-generator */
it('should return EMPTY if no specs are generated', async () => {
  const source = { spec: { content: '' }, compileSnapshot: jest.fn() } as any;
  const strategy = new AssistantInitStrategy('INIT', source, { provider: {} as any });
  jest.spyOn(strategy as any, 'generate').mockResolvedValue(null);
  const result = await strategy.run();
  expect(result).toBe('EMPTY');
})

/* Generated by @n1k1t/unit-generator */
it('should return EMPTY if generated specs array is empty', async () => {
  const source = { spec: { content: '' }, compileSnapshot: jest.fn() } as any;
  const strategy = new AssistantInitStrategy('INIT', source, { provider: {} as any });
  jest.spyOn(strategy as any, 'generate').mockResolvedValue({ imports: [], specs: [] });
  const result = await strategy.run();
  expect(result).toBe('EMPTY');
})

/* Generated by @n1k1t/unit-generator */
it('should define a schema with imports and specs', () => {
  const strategy = new AssistantInitStrategy('INIT', {} as any, { provider: {} as any });
  expect(strategy.schema).toBeInstanceOf(z.ZodObject);
})

/* Generated by @n1k1t/unit-generator */
it('should have INIT as the strategy name', () => {
  const strategy = new AssistantInitStrategy('INIT', {} as any, { provider: {} as any });
  expect(strategy.name).toBe('INIT');
})

/* Generated by @n1k1t/unit-generator */
it('should return FAILED if injectImports fails', async () => {
  const source = { spec: { content: '' }, compileSnapshot: jest.fn() } as any;
  const strategy = new AssistantInitStrategy('INIT', source, { provider: {} as any });
  jest.spyOn(strategy as any, 'generate').mockResolvedValue({ imports: ['import X'], specs: [{ code: 'it()' }] });
  jest.spyOn(strategy as any, 'injectImports').mockResolvedValue('FAILED');
  const result = await strategy.run();
  expect(result).toBe('FAILED');
})

/* Generated by @n1k1t/unit-generator */
it('should restore snapshot if injectSpecs fails', async () => {
  const snapshot = { spec: { content: '' } };
  const source = { spec: { content: '' }, compileSnapshot: jest.fn().mockReturnValue(snapshot), restore: jest.fn() } as any;
  const strategy = new AssistantInitStrategy('INIT', source, { provider: {} as any });
  jest.spyOn(strategy as any, 'generate').mockResolvedValue({ imports: ['import X'], specs: [{ code: 'it()' }] });
  jest.spyOn(strategy as any, 'injectImports').mockResolvedValue('DONE');
  jest.spyOn(strategy as any, 'injectSpecs').mockResolvedValue('FAILED');
  await strategy.run();
  expect(source.restore).toHaveBeenCalledWith(snapshot);
})

/* Generated by @n1k1t/unit-generator */
it('should return EMPTY in injectImports if no valid imports found', async () => {
  const strategy = new AssistantInitStrategy('INIT', { save: jest.fn() } as any, { provider: {} as any });
  const result = await (strategy as any).injectImports({ imports: ['invalid'], specs: [] });
  expect(result).toBe('EMPTY');
})

/* Generated by @n1k1t/unit-generator */
it('should return FAILED in injectImports if test fails', async () => {
  const source = {
    save: jest.fn(),
    spec: { prepend: jest.fn().mockReturnThis(), append: jest.fn().mockReturnThis(), write: jest.fn() },
    test: jest.fn().mockResolvedValue({ status: 'FAILED' }),
    restore: jest.fn()
  } as any;
  const strategy = new AssistantInitStrategy('INIT', source, { provider: {} as any });
  const result = await (strategy as any).injectImports({ imports: ['import X'], specs: [{ code: 'it()' }] });
  expect(result).toBe('FAILED');
})

/* Generated by @n1k1t/unit-generator */
it('should return EMPTY in injectSpecs if only one spec exists', async () => {
  const strategy = new AssistantInitStrategy('INIT', {} as any, { provider: {} as any });
  const result = await (strategy as any).injectSpecs({ specs: [{ code: 'it()' }] });
  expect(result).toBe('EMPTY');
})

/* Generated by @n1k1t/unit-generator */
it('should add to history if spec test fails in injectSpecs', async () => {
  const source = {
    save: jest.fn(),
    spec: { append: jest.fn().mockReturnThis(), write: jest.fn() },
    test: jest.fn().mockResolvedValue({ status: 'FAILED', message: 'error' }),
    restore: jest.fn()
  } as any;
  const strategy = new AssistantInitStrategy('INIT', source, { provider: {} as any });
  strategy.history.add = jest.fn();
  await (strategy as any).injectSpecs({ specs: [{ code: 'it1' }, { code: 'it2' }] });
  expect(strategy.history.add).toHaveBeenCalledWith({ generated: 'it2', message: 'error' });
})

/* Generated by @n1k1t/unit-generator */
it('should return DONE in injectSpecs if at least one spec passed', async () => {
  const source = {
    save: jest.fn(),
    spec: { append: jest.fn().mockReturnThis(), write: jest.fn() },
    test: jest.fn().mockResolvedValue({ status: 'PASSED' })
  } as any;
  const strategy = new AssistantInitStrategy('INIT', source, { provider: {} as any });
  const result = await (strategy as any).injectSpecs({ specs: [{ code: 'it1' }, { code: 'it2' }] });
  expect(result).toBe('DONE');
})

/* Generated by @n1k1t/unit-generator */
it('should return FAILED in injectSpecs if no specs passed', async () => {
  const source = {
    save: jest.fn(),
    spec: { append: jest.fn().mockReturnThis(), write: jest.fn() },
    test: jest.fn().mockResolvedValue({ status: 'FAILED' }),
    restore: jest.fn()
  } as any;
  const strategy = new AssistantInitStrategy('INIT', source, { provider: {} as any });
  const result = await (strategy as any).injectSpecs({ specs: [{ code: 'it1' }, { code: 'it2' }] });
  expect(result).toBe('FAILED');
})

/* Generated by @n1k1t/unit-generator */
it('should build an instance of AssistantInitStrategy', () => {
  const source = {} as any;
  const provider = {} as any;
  const strategy = AssistantInitStrategy.build(source, { provider });
  expect(strategy).toBeInstanceOf(AssistantInitStrategy);
})

/* Generated by @n1k1t/unit-generator */
it('should return SKIPPED if source spec content is not empty', async () => {
  const source = { spec: { content: 'existing test' } } as any;
  const strategy = AssistantInitStrategy.build(source, { provider: {} as any });
  const result = await strategy.run();
  expect(result).toBe('SKIPPED');
})

/* Generated by @n1k1t/unit-generator */
it('should return EMPTY if no specs are generated', async () => {
  const source = { spec: { content: '' }, compileSnapshot: jest.fn() } as any;
  const strategy = AssistantInitStrategy.build(source, { provider: {} as any });
  jest.spyOn(strategy as any, 'generate').mockResolvedValue({ specs: [] });
  const result = await strategy.run();
  expect(result).toBe('EMPTY');
})

/* Generated by @n1k1t/unit-generator */
it('should return EMPTY if generated imports are empty', async () => {
  const source = { spec: { content: '' }, compileSnapshot: jest.fn(), save: jest.fn() } as any;
  const strategy = AssistantInitStrategy.build(source, { provider: {} as any });
  const generated = { imports: ['invalid'], specs: [{ code: 'it()' }] };
  const result = await (strategy as any).injectImports(generated);
  expect(result).toBe('EMPTY');
})

/* Generated by @n1k1t/unit-generator */
it('should return FAILED if injected imports test fails', async () => {
  const source = {
    spec: { content: '', prepend: jest.fn().mockReturnThis(), append: jest.fn().mockReturnThis(), write: jest.fn() },
    save: jest.fn(),
    test: jest.fn().mockResolvedValue({ status: 'FAILED' }),
    restore: jest.fn()
  } as any;
  const strategy = AssistantInitStrategy.build(source, { provider: {} as any });
  const generated = { imports: ["import { x } from 'y'"], specs: [{ code: 'it()' }] };
  const result = await (strategy as any).injectImports(generated);
  expect(result).toBe('FAILED');
})

/* Generated by @n1k1t/unit-generator */
it('should return EMPTY in injectSpecs if specs length is 1 or less', async () => {
  const strategy = AssistantInitStrategy.build({} as any, { provider: {} as any });
  const result = await (strategy as any).injectSpecs({ specs: [{ code: 'it()' }] });
  expect(result).toBe('EMPTY');
})

/* Generated by @n1k1t/unit-generator */
it('should return FAILED in injectImports if the first spec test fails', async () => {
  const source = {
    save: jest.fn(),
    restore: jest.fn(),
    test: jest.fn().mockResolvedValue({ status: 'FAILED' }),
    spec: {
      prepend: jest.fn().mockReturnThis(),
      append: jest.fn().mockReturnThis(),
      write: jest.fn().mockResolvedValue(undefined)
    }
  } as any;
  const strategy = AssistantInitStrategy.build(source, {} as any);
  const generated = { imports: ['import { x } from "y"'], specs: [{ code: 'it("pass")' }] };
  const result = await (strategy as any).injectImports(generated);
  expect(result).toBe('FAILED');
})

/* Generated by @n1k1t/unit-generator */
it('should return EMPTY in injectSpecs if there is only one spec', async () => {
  const strategy = AssistantInitStrategy.build({} as any, {} as any);
  const generated = { specs: [{ code: 'it("pass")' }] };
  const result = await (strategy as any).injectSpecs(generated);
  expect(result).toBe('EMPTY');
})

/* Generated by @n1k1t/unit-generator */
it('should restore source and add to history in injectSpecs if test fails', async () => {
  const source = {
    save: jest.fn(),
    restore: jest.fn(),
    test: jest.fn().mockResolvedValue({ status: 'FAILED', message: 'error' }),
    spec: {
      append: jest.fn().mockReturnThis(),
      write: jest.fn().mockResolvedValue(undefined)
    }
  } as any;
  const history = { add: jest.fn() };
  const strategy = AssistantInitStrategy.build(source, {} as any);
  (strategy as any).history = history;
  const generated = { specs: [{ code: 'it("pass")' }, { code: 'it("fail")' }] };
  await (strategy as any).injectSpecs(generated);
  expect(source.restore).toHaveBeenCalled();
})

/* Generated by @n1k1t/unit-generator */
it('should return EMPTY in injectImports if no imports are found in generated data', async () => {
  const strategy = AssistantInitStrategy.build({ save: jest.fn() } as any, {} as any);
  const result = await (strategy as any).injectImports({ imports: ['const x = 1;'], specs: [] });
  expect(result).toBe('EMPTY');
})

/* Generated by @n1k1t/unit-generator */
it('should return FAILED in injectImports if source test fails', async () => {
  const source = {
    save: jest.fn(),
    restore: jest.fn(),
    test: jest.fn().mockResolvedValue({ status: 'FAILED' }),
    spec: { prepend: jest.fn().mockReturnThis(), append: jest.fn().mockReturnThis(), write: jest.fn().mockResolvedValue(undefined) }
  };
  const strategy = AssistantInitStrategy.build(source as any, {} as any);
  const result = await (strategy as any).injectImports({ imports: ['import { x } from "y"'], specs: [{ code: 'it()' }] });
  expect(result).toBe('FAILED');
})
