import json2md, { DataObject } from 'json2md';

import { generateObject, NoObjectGeneratedError } from 'ai';
import { createOpenAI } from '@ai-sdk/openai';
import { z } from 'zod';

import { TAssistantSourceTestResult, TAssistantStrategyRunStatus } from '../types';
import { AssistantStrategy } from './model';
import { cast } from '../../../utils';

import env from '../../../env';

const openai = createOpenAI({ apiKey: env.key, baseURL: env.url });

export class AssistantInitStrategy extends AssistantStrategy<'INIT'> {
  public model = openai(this.provided.model ?? env.model, { user: this.source.id });

  public schema = z.object({
    imports: z.array(
      z.string({ description: 'Code of ONLY one import statement, for example: `import ...`' }),
      {
        description: 'List of required entity imports for unit tests',
      }
    ).min(1),

    specs: z.array(
      z.object({
        code: z.string({ description: 'Code of ONLY one unit test function, for example: `it(...)`' }),
      }),
      {
        description: 'List of unit tests',
      }
    ).min(1),
  });

  public async run(): Promise<TAssistantStrategyRunStatus> {
    if (this.source.spec.content.length) {
      return 'SKIPPED';
    }

    const snapshot = this.source.compileSnapshot();

    const generated = await this.generate();
    if (!generated?.specs.length) {
      this.differ();
      return 'EMPTY';
    }

    const imported = await this.injectImports(generated);
    if (imported !== 'DONE') {
      this.differ();
      return imported;
    }

    const result = await this.injectSpecs(generated);
    if (result !== 'DONE') {
      this.differ();
      await this.source.restore(snapshot);
    }

    return result;
  }

  private async injectImports(generated: AssistantInitStrategy['schema']['_type']): Promise<TAssistantStrategyRunStatus> {
    this.source.save();

    const imports = generated.imports.filter((row) => row.includes('import') || row.includes('require'));
    if (!imports.length) {
      return 'EMPTY';
    }

    await this.source.spec
      .prepend(imports.join('\n'))
      .append(generated.specs[0].code)
      .write();

    const tested = await this.source.test();
    await this.source.restore();

    if (tested.status === 'FAILED') {
      return 'FAILED';
    }

    await this.source.spec.prepend(imports.join('\n')).write();
    return 'DONE';
  }

  private async injectSpecs(
    generated: AssistantInitStrategy['schema']['_type'],
    results: TAssistantSourceTestResult[] = []
  ): Promise<TAssistantStrategyRunStatus> {
    if (generated.specs.length <= 1) {
      return 'EMPTY';
    }

    /** Skip the first spec that is always passing */
    const index = results.length + 1;
    this.source.save();

    await this.source.spec
      .append(`\n/* Generated by @n1k1t/unit-generator */\n${generated.specs[index].code.trim()}`)
      .write();

    const tested = await this.source.test();
    if (tested.status === 'FAILED') {
      await this.source.restore();
    }

    return index === generated.specs.length - 1
      ? results.concat([tested]).some((result) => result.status === 'PASSED') ? 'DONE' : 'FAILED'
      : this.injectSpecs(generated, results.concat([tested]));
  }

  private async generate(): Promise<AssistantInitStrategy['schema']['_type'] | null> {
    const response = await generateObject({
      prompt: json2md(
        cast<DataObject[]>([
          ...this.context.overview,
          ...this.context.project,

          { hr: '' },
          { h1: 'Task' },

          {
            ul: [
              'Analyze the task context described above',
              'Write unit tests based on the task context described above',
              'The first unit test must always pass, for example: `it(\'should pass\', () => expect(1).toEqual(1))`',
            ],
          },
        ])
      ),

      temperature: this.differation.temperature,
      seed: this.differation.seed,

      schema: this.schema,
      model: this.model,
    }).catch((error) => {
      if (error instanceof NoObjectGeneratedError) {
        return null;
      }

      throw error;
    });

    return response?.object ?? null;
  }

  static build(
    source: AssistantStrategy['source'],
    provided: AssistantStrategy['provided'] = {}
  ): AssistantInitStrategy {
    return new AssistantInitStrategy('INIT', source, provided);
  }
}
