import { AssistantStrategy } from './model';
import { AssistantSource } from '../source';
import { TAssistantStrategyRunStatus } from '../types';


/* Generated by @n1k1t/unit-generator */
it('should initialize with the provided provider', () => {
  const mockSource = {} as AssistantSource;
  const mockProvider = {} as any;
  class TestStrategy extends AssistantStrategy {
    async run(): Promise<TAssistantStrategyRunStatus> { return 'DONE'; }
  }
  const strategy = new TestStrategy('test', mockSource, { provider: mockProvider });
  expect(strategy.provider).toBe(mockProvider);
});

/* Generated by @n1k1t/unit-generator */
it('should initialize with default tools grep and read', () => {
  const mockSource = {} as AssistantSource;
  class TestStrategy extends AssistantStrategy {
    async run(): Promise<TAssistantStrategyRunStatus> { return 'DONE'; }
  }
  const strategy = new TestStrategy('test', mockSource, { provider: {} as any });
  expect(Object.keys(strategy.tools)).toEqual(['grep', 'read']);
});

/* Generated by @n1k1t/unit-generator */
it('should compile context with overview requirements', () => {
  const mockSource = { code: { path: 'src/test.ts', lang: 'ts', content: '' }, tree: [], spec: { lang: 'ts' } } as any;
  class TestStrategy extends AssistantStrategy {
    async run(): Promise<TAssistantStrategyRunStatus> { return 'DONE'; }
  }
  const strategy = new TestStrategy('test', mockSource, { provider: {} as any });
  const context = strategy.compileContext();
  expect(context.overview[1]).toEqual({ h3: 'Requirements for writing unit tests' });
});

/* Generated by @n1k1t/unit-generator */
it('should include the source code path in the project context', () => {
  const mockSource = { code: { path: 'src/my-file.ts', lang: 'ts', content: 'const x = 1;' }, tree: [], spec: { lang: 'ts' } } as any;
  class TestStrategy extends AssistantStrategy {
    async run(): Promise<TAssistantStrategyRunStatus> { return 'DONE'; }
  }
  const strategy = new TestStrategy('test', mockSource, { provider: {} as any });
  const context = strategy.compileContext();
  expect(context.project).toContainEqual({ p: '`src/my-file.ts`' });
});

/* Generated by @n1k1t/unit-generator */
it('should format dependencies correctly in the project context', () => {
  const mockSource = { code: { path: '', lang: '', content: '' }, tree: [], spec: { lang: '' } } as any;
  const dependencies = { 'lodash': '4.17.21', 'zod': '3.0.0' };
  class TestStrategy extends AssistantStrategy {
    async run(): Promise<TAssistantStrategyRunStatus> { return 'DONE'; }
  }
  const strategy = new TestStrategy('test', mockSource, { provider: {} as any, dependencies });
  const context = strategy.compileContext();
  const depsCode = (context.project[3] as any).code.content;
  expect(depsCode).toBe('lodash: 4.17.21\nzod: 3.0.0');
});

/* Generated by @n1k1t/unit-generator */
it('should generate a file tree string in the project context', () => {
  const mockSource = { code: { path: '', lang: '', content: '' }, tree: ['src/index.ts', 'src/utils.ts'], spec: { lang: '' } } as any;
  class TestStrategy extends AssistantStrategy {
    async run(): Promise<TAssistantStrategyRunStatus> { return 'DONE'; }
  }
  const strategy = new TestStrategy('test', mockSource, { provider: {} as any });
  const context = strategy.compileContext();
  const treeContent = (context.project[5] as any).code.content;
  expect(treeContent).toContain('src\n  index.ts\n  utils.ts');
});

/* Generated by @n1k1t/unit-generator */
it('should include history items in the history context', () => {
  const mockSource = { code: { path: '', lang: '', content: '' }, tree: [], spec: { lang: 'ts' } } as any;
  class TestStrategy extends AssistantStrategy {
    async run(): Promise<TAssistantStrategyRunStatus> { return 'DONE'; }
  }
  const strategy = new TestStrategy('test', mockSource, { provider: {} as any });
  strategy.history.add({ generated: 'test spec', message: 'error message' });
  const context = strategy.compileContext();
  expect(context.history).toContainEqual({ code: { language: 'bash', content: 'error message' } });
});
