import { AssistantStrategy } from './model';
import { AssistantSource } from '../source';
import { LanguageModel } from 'ai';

/* Generated by @n1k1t/unit-generator */
it('should create instance with correct source', () => {
  class TestStrategy extends AssistantStrategy {
    public model: LanguageModel = {} as LanguageModel;
    public async run() {
      return 'DONE' as const;
    }
  }
  const source = { code: { path: 'test.ts' } } as AssistantSource;
  const strategy = new TestStrategy('test', source, {});
  expect(strategy.source).toEqual(source);
});

/* Generated by @n1k1t/unit-generator */
it('should set default parameters with temperature 0 and current timestamp seed', () => {
  class TestStrategy extends AssistantStrategy {
    public model: LanguageModel = {} as LanguageModel;
    public async run() {
      return 'DONE' as const;
    }
  }
  const source = { code: { path: 'test.ts' } } as AssistantSource;
  const strategy = new TestStrategy('test', source, {});
  expect(strategy.parameters.temperature).toBe(0);
  expect(typeof strategy.parameters.seed).toBe('number');
});

/* Generated by @n1k1t/unit-generator */
it('should increase temperature by 0.1 when differ is called and temperature is less than 1', () => {
  class TestStrategy extends AssistantStrategy {
    public model: LanguageModel = {} as LanguageModel;
    public async run() {
      return 'DONE' as const;
    }
  }
  const source = { code: { path: 'test.ts' } } as AssistantSource;
  const strategy = new TestStrategy('test', source, {});
  strategy.parameters.temperature = 0.5;
  strategy.differ();
  expect(strategy.parameters.temperature).toBe(0.6);
});

/* Generated by @n1k1t/unit-generator */
it('should not increase temperature when differ is called and temperature is 1', () => {
  class TestStrategy extends AssistantStrategy {
    public model: LanguageModel = {} as LanguageModel;
    public async run() {
      return 'DONE' as const;
    }
  }
  const source = { code: { path: 'test.ts' } } as AssistantSource;
  const strategy = new TestStrategy('test', source, {});
  strategy.parameters.temperature = 1;
  strategy.differ();
  expect(strategy.parameters.temperature).toBe(1);
});

/* Generated by @n1k1t/unit-generator */
it('should return this when differ is called', () => {
  class TestStrategy extends AssistantStrategy {
    public model: LanguageModel = {} as LanguageModel;
    public async run() {
      return 'DONE' as const;
    }
  }
  const source = { code: { path: 'test.ts' } } as AssistantSource;
  const strategy = new TestStrategy('test', source, {});
  const result = strategy.differ();
  expect(result).toBe(strategy);
});
