import { execSync } from 'child_process';
import { AssistantStrategy } from '../strategies';
import grep from './grep';

/* Generated by @n1k1t/unit-generator */
it('should call execSync with default arguments when no optional parameters are provided', async () => {
  const mockExecSync = jest.spyOn(require('child_process'), 'execSync').mockReturnValue('match');
  const strategy = { source: { ignore: [] } } as unknown as AssistantStrategy;
  const tool = grep(strategy);

  await tool.execute?.({ pattern: 'test-pattern' }, {} as any);

  expect(mockExecSync).toHaveBeenCalledWith('grep -rnE "test-pattern" .', { encoding: 'utf-8' });

  mockExecSync.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should include before and after context lines in grep command', async () => {
  const mockExecSync = jest.spyOn(require('child_process'), 'execSync').mockReturnValue('match');
  const strategy = { source: { ignore: [] } } as unknown as AssistantStrategy;
  const tool = grep(strategy);

  await tool.execute?.({ pattern: 'test', before: 2, after: 3 }, {} as any);

  expect(mockExecSync).toHaveBeenCalledWith('grep -rnE -B 2 -A 3 "test" .', { encoding: 'utf-8' });

  mockExecSync.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should include exclude patterns from strategy in grep command', async () => {
  const mockExecSync = jest.spyOn(require('child_process'), 'execSync').mockReturnValue('match');
  const strategy = { source: { ignore: ['node_modules/**', 'dist/**'] } } as unknown as AssistantStrategy;
  const tool = grep(strategy);

  await tool.execute?.({ pattern: 'test' }, {} as any);

  expect(mockExecSync).toHaveBeenCalledWith('grep -rnE --exclude-dir={node_modules,dist} "test" .', { encoding: 'utf-8' });

  mockExecSync.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should use provided path in grep command', async () => {
  const mockExecSync = jest.spyOn(require('child_process'), 'execSync').mockReturnValue('match');
  const strategy = { source: { ignore: [] } } as unknown as AssistantStrategy;
  const tool = grep(strategy);

  await tool.execute?.({ pattern: 'test', path: 'src/utils' }, {} as any);

  expect(mockExecSync).toHaveBeenCalledWith('grep -rnE "test" src/utils', { encoding: 'utf-8' });

  mockExecSync.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should return error message when execSync throws an error', async () => {
  const mockExecSync = jest.spyOn(require('child_process'), 'execSync').mockImplementation(() => {
    throw new Error('grep failed');
  });
  const strategy = { source: { ignore: [] } } as unknown as AssistantStrategy;
  const tool = grep(strategy);

  const result = await tool.execute?.({ pattern: 'test' }, {} as any);

  expect(result).toEqual({ error: 'grep failed' });

  mockExecSync.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should return formatted error message when execSync throws a non-Error object', async () => {
  const mockExecSync = jest.spyOn(require('child_process'), 'execSync').mockImplementation(() => {
    throw 'string error';
  });
  const strategy = { source: { ignore: [] } } as unknown as AssistantStrategy;
  const tool = grep(strategy);

  const result = await tool.execute?.({ pattern: 'test' }, {} as any);

  expect(result).toEqual({ error: 'string error' });

  mockExecSync.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('parses grep output and respects ignore patterns', async () => {
  const strategy: AssistantStrategy = {
    source: {
      ignore: ['node_modules/**', 'dist/**'],
    },
  } as unknown as AssistantStrategy;

  const mockedOutput = 'src/file.ts:10: matched\nsrc/file.ts-11- context\n';
  const spy = jest.spyOn(require('child_process'), 'execSync').mockReturnValue(mockedOutput);

  const result = await grep(strategy).execute?.({ pattern: 'foo', path: '.' }, {} as any);

  expect((result as any).output?.[0].content).toBe('10: matched\n11: context');
  spy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('returns error message when grep fails', async () => {
  const strategy: AssistantStrategy = {
    source: {
      ignore: [],
    },
  } as unknown as AssistantStrategy;

  const spy = jest.spyOn(require('child_process'), 'execSync').mockImplementation(() => {
    throw new Error('grep failed');
  });

  const result = await grep(strategy).execute?.({ pattern: 'foo', path: '.' }, {} as any);

  expect((result as any).error).toBe('grep failed');
  spy.mockRestore();
});
