import { z } from 'zod';

import { AssistantToolCompiler, AssistantToolCompilationError } from './model';
import { AssistantSource } from '../source';

/* Generated by @n1k1t/unit-generator */
it('should initialize with a description', () => {
  const compiler = new AssistantToolCompiler('test description');
  expect(compiler.description).toBe('test description');
})

/* Generated by @n1k1t/unit-generator */
it('should set input schema and return the compiler instance', () => {
  const compiler = new AssistantToolCompiler('test');
  const schema = z.object({ foo: z.string() });
  const result = compiler.input(schema);
  expect(result).toBe(compiler);
})

/* Generated by @n1k1t/unit-generator */
it('should set output schema and return the compiler instance', () => {
  const compiler = new AssistantToolCompiler('test');
  const schema = z.object({ bar: z.number() });
  const result = compiler.output(schema);
  expect(result).toBe(compiler);
})

/* Generated by @n1k1t/unit-generator */
it('should set executor and return the compiler instance', () => {
  const compiler = new AssistantToolCompiler('test');
  const executor = () => async () => 'result';
  const result = compiler.execute(executor);
  expect(result).toBe(compiler);
})

/* Generated by @n1k1t/unit-generator */
it('should throw AssistantToolCompilationError if executor is not set during compile', () => {
  const compiler = new AssistantToolCompiler('test');
  const source = {} as AssistantSource;
  expect(() => compiler.compile(source)).toThrow(AssistantToolCompilationError);
})

/* Generated by @n1k1t/unit-generator */
it('should throw error with correct property name when executor is missing', () => {
  const compiler = new AssistantToolCompiler('test');
  const source = {} as AssistantSource;
  try {
    compiler.compile(source);
  } catch (error) {
    expect((error as AssistantToolCompilationError).property).toBe('executor');
  }
})

/* Generated by @n1k1t/unit-generator */
it('should compile into a tool with correct properties', () => {
  const compiler = new AssistantToolCompiler('test description');
  const inputSchema = z.object({ input: z.string() });
  const outputSchema = z.object({ output: z.string() });
  const executor = (source: AssistantSource) => async (input: any) => 'executed';
  const source = {} as AssistantSource;

  compiler.input(inputSchema).output(outputSchema).execute(<any>executor);
  const compiledTool = compiler.compile(source);

  expect(compiledTool.description).toBe('test description');
  expect(compiledTool.execute).toBeDefined();
})

/* Generated by @n1k1t/unit-generator */
it('should call the executor factory with the provided source during compilation', () => {
  const compiler = new AssistantToolCompiler('test');
  const source = { id: 'test-source' } as unknown as AssistantSource;
  const executorFactory = jest.fn().mockReturnValue(async () => {});

  compiler.execute(executorFactory);
  compiler.compile(source);

  expect(executorFactory).toHaveBeenCalledWith(source);
})

/* Generated by @n1k1t/unit-generator */
it('should create a compiler instance using the static build method', () => {
  const compiler = AssistantToolCompiler.build('static build test');
  expect(compiler).toBeInstanceOf(AssistantToolCompiler);
  expect(compiler.description).toBe('static build test');
})
