import fs from 'fs/promises';

import { AssistantSource } from '../source';
import read from './read';

/* Generated by @n1k1t/unit-generator */
it('should return the full content of a file when no start or end lines are provided', async () => {
  const source = {} as AssistantSource;
  const tool = read.compile(source);
  jest.spyOn(fs, 'readFile').mockResolvedValue('line 1\nline 2\nline 3');

  const result = await tool.execute?.({ path: 'test.txt' }, {} as any);

  expect(result).toEqual({ content: 'line 1\nline 2\nline 3' });
});

/* Generated by @n1k1t/unit-generator */
it('should return a sliced content when start line is provided', async () => {
  const source = {} as AssistantSource;
  const tool = read.compile(source);
  jest.spyOn(fs, 'readFile').mockResolvedValue('line 1\nline 2\nline 3');

  const result = await tool.execute?.({ path: 'test.txt', start: 2 }, {} as any);

  expect(result).toEqual({ content: 'line 2\nline 3' });
});

/* Generated by @n1k1t/unit-generator */
it('should return a sliced content when end line is provided', async () => {
  const source = {} as AssistantSource;
  const tool = read.compile(source);
  jest.spyOn(fs, 'readFile').mockResolvedValue('line 1\nline 2\nline 3');

  const result = await tool.execute?.({ path: 'test.txt', end: 2 }, {} as any);

  expect(result).toEqual({ content: 'line 1\nline 2' });
});

/* Generated by @n1k1t/unit-generator */
it('should return a sliced content when both start and end lines are provided', async () => {
  const source = {} as AssistantSource;
  const tool = read.compile(source);
  jest.spyOn(fs, 'readFile').mockResolvedValue('line 1\nline 2\nline 3\nline 4');

  const result = await tool.execute?.({ path: 'test.txt', start: 2, end: 3 }, {} as any);

  expect(result).toEqual({ content: 'line 2\nline 3' });
});

/* Generated by @n1k1t/unit-generator */
it('should return an error message when file reading fails', async () => {
  const source = {} as AssistantSource;
  const tool = read.compile(source);
  jest.spyOn(fs, 'readFile').mockRejectedValue(new Error('File not found'));

  const result = await tool.execute?.({ path: 'non-existent.txt' }, {} as any);

  expect(result).toEqual({ error: 'File not found' });
});

/* Generated by @n1k1t/unit-generator */
it('should return a formatted error message when a non-Error object is thrown', async () => {
  const source = {} as AssistantSource;
  const tool = read.compile(source);
  jest.spyOn(fs, 'readFile').mockRejectedValue('Unknown error');

  const result = await tool.execute?.({ path: 'test.txt' }, {} as any);

  expect(result).toEqual({ error: 'Unknown error' });
});
