import { checkPatternIsRestricted } from './utils';

/* Generated by @n1k1t/unit-generator */
it('should return false if pattern contains double dots', () => {
  expect(checkPatternIsRestricted('../../etc/passwd')).toBe(false);
})

/* Generated by @n1k1t/unit-generator */
it('should return false if pattern starts with a forward slash', () => {
  expect(checkPatternIsRestricted('/absolute/path')).toBe(false);
})

/* Generated by @n1k1t/unit-generator */
it('should return false if pattern starts with a tilde', () => {
  expect(checkPatternIsRestricted('~/home')).toBe(false);
})

/* Generated by @n1k1t/unit-generator */
it('should return false if pattern ends with .env', () => {
  expect(checkPatternIsRestricted('config/.env')).toBe(false);
})

/* Generated by @n1k1t/unit-generator */
it('should return true for a safe relative path pattern', () => {
  expect(checkPatternIsRestricted('src/models/user.ts')).toBe(true);
})

/* Generated by @n1k1t/unit-generator */
it('should return true for a simple filename pattern', () => {
  expect(checkPatternIsRestricted('index.ts')).toBe(true);
})
