import { LlmGoogleProvider } from './google';

/* Generated by @n1k1t/unit-generator */
it('should have the name google', () => {
  const provider = new LlmGoogleProvider('gemini-1.5-pro', {
    connection: { key: 'test-key' },
    options: {},
  });
  expect(provider.name).toBe('google');
});

/* Generated by @n1k1t/unit-generator */
it('should have a tag defined', () => {
  const provider = new LlmGoogleProvider('gemini-1.5-pro', {
    connection: { key: 'test-key' },
    options: {},
  });
  expect(provider.tag).toBeDefined();
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same model', () => {
  const provider = new LlmGoogleProvider('gemini-1.5-pro', {
    connection: { key: 'test-key' },
    options: {},
  });
  const clone = provider.clone();
  expect(clone.model).toBe('gemini-1.5-pro');
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same connection key', () => {
  const provider = new LlmGoogleProvider('gemini-1.5-pro', {
    connection: { key: 'test-key' },
    options: {},
  });
  const clone = provider.clone();
  expect(clone.connection.key).toBe('test-key');
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with a different options object reference', () => {
  const provider = new LlmGoogleProvider('gemini-1.5-pro', {
    connection: { key: 'test-key' },
    options: { thinkingConfig: { thinkingBudget: 1024 } },
  });
  const clone = provider.clone();
  expect(clone.options).not.toBe(provider.options);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same options values', () => {
  const provider = new LlmGoogleProvider('gemini-1.5-pro', {
    connection: { key: 'test-key' },
    options: { thinkingConfig: { thinkingBudget: 1024 } },
  });
  const clone = provider.clone();
  expect(clone.options).toEqual({ thinkingConfig: { thinkingBudget: 1024 } });
});

/* Generated by @n1k1t/unit-generator */
it('should build a provider with the correct model', () => {
  const provider = LlmGoogleProvider.build('gemini-1.5-pro', {
    connection: { key: 'test-key' },
  });
  expect(provider.model).toBe('gemini-1.5-pro');
});

/* Generated by @n1k1t/unit-generator */
it('should build a provider with the default thinking budget option', () => {
  const provider = LlmGoogleProvider.build('gemini-1.5-pro', {
    connection: { key: 'test-key' },
  });
  expect(provider.options.thinkingConfig?.thinkingBudget).toBe(2048);
});

/* Generated by @n1k1t/unit-generator */
it('should build a provider with includeThoughts option set to true', () => {
  const provider = LlmGoogleProvider.build('gemini-1.5-pro', {
    connection: { key: 'test-key' },
  });
  expect(provider.options.thinkingConfig?.includeThoughts).toBe(true);
});

/* Generated by @n1k1t/unit-generator */
it('should assign a new temperature and return a clone', () => {
  const provider = new LlmGoogleProvider('gemini-1.5-pro', {
    connection: { key: 'test-key' },
    options: {},
  });
  const assigned = provider.assign({ temperature: 0.5 });
  expect(assigned.temperature).toBe(0.5);
});

/* Generated by @n1k1t/unit-generator */
it('should assign new options and return a clone', () => {
  const provider = new LlmGoogleProvider('gemini-1.5-pro', {
    connection: { key: 'test-key' },
    options: {},
  });
  const assigned = provider.assign({ options: { thinkingConfig: { thinkingBudget: 512 } } });
  expect(assigned.options.thinkingConfig?.thinkingBudget).toBe(512);
});

/* Generated by @n1k1t/unit-generator */
it('should assign new tools and return a clone', () => {
  const provider = new LlmGoogleProvider('gemini-1.5-pro', {
    connection: { key: 'test-key' },
    options: {},
  });
  const dummyTool = {} as any;
  const assigned = provider.assign({ tools: { myTool: dummyTool } });
  expect(assigned.tools.myTool).toBe(dummyTool);
});

/* Generated by @n1k1t/unit-generator */
it('should assign a new limit and return a clone', () => {
  const provider = new LlmGoogleProvider('gemini-1.5-pro', {
    connection: { key: 'test-key' },
    options: {},
  });
  const assigned = provider.assign({ limit: 50 });
  expect(assigned.limit).toBe(50);
});
