import { LlmMistralProvider } from './mistral';

/* Generated by @n1k1t/unit-generator */
it('should have the name mistral', () => {
  const provider = new LlmMistralProvider('mistral-large', {
    connection: { key: 'test-key', url: 'https://api.mistral.ai' },
    options: {},
  });
  expect(provider.name).toBe('mistral');
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider correctly', () => {
  const provider = new LlmMistralProvider('mistral-large', {
    connection: { key: 'test-key', url: 'https://api.mistral.ai' },
    options: { foo: 'bar' },
    temperature: 0.7,
  });
  const clone = provider.clone();
  expect(clone).toBeInstanceOf(LlmMistralProvider);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same model', () => {
  const provider = new LlmMistralProvider('mistral-large', {
    connection: { key: 'test-key', url: 'https://api.mistral.ai' },
    options: { foo: 'bar' },
  });
  const clone = provider.clone();
  expect(clone.model).toBe('mistral-large');
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same temperature', () => {
  const provider = new LlmMistralProvider('mistral-large', {
    connection: { key: 'test-key', url: 'https://api.mistral.ai' },
    options: { foo: 'bar' },
    temperature: 0.7,
  });
  const clone = provider.clone();
  expect(clone.temperature).toBe(0.7);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same connection', () => {
  const provider = new LlmMistralProvider('mistral-large', {
    connection: { key: 'test-key', url: 'https://api.mistral.ai' },
    options: { foo: 'bar' },
  });
  const clone = provider.clone();
  expect(clone.connection).toEqual({ key: 'test-key', url: 'https://api.mistral.ai' });
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with cloned options', () => {
  const provider = new LlmMistralProvider('mistral-large', {
    connection: { key: 'test-key', url: 'https://api.mistral.ai' },
    options: { foo: 'bar' },
  });
  const clone = provider.clone();
  expect(clone.options).toEqual({ foo: 'bar' });
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with a different options object reference', () => {
  const provider = new LlmMistralProvider('mistral-large', {
    connection: { key: 'test-key', url: 'https://api.mistral.ai' },
    options: { foo: 'bar' },
  });
  const clone = provider.clone();
  expect(clone.options).not.toBe(provider.options);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with cloned tools', () => {
  const provider = new LlmMistralProvider('mistral-large', {
    connection: { key: 'test-key', url: 'https://api.mistral.ai' },
    options: {},
    tools: { myTool: {} as any },
  });
  const clone = provider.clone();
  expect(clone.tools).toEqual({ myTool: {} });
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with a different tools object reference', () => {
  const provider = new LlmMistralProvider('mistral-large', {
    connection: { key: 'test-key', url: 'https://api.mistral.ai' },
    options: {},
    tools: { myTool: {} as any },
  });
  const clone = provider.clone();
  expect(clone.tools).not.toBe(provider.tools);
});

/* Generated by @n1k1t/unit-generator */
it('should build a provider using the static build method', () => {
  const provider = LlmMistralProvider.build('mistral-large', {
    connection: { key: 'test-key', url: 'https://api.mistral.ai' },
  });
  expect(provider).toBeInstanceOf(LlmMistralProvider);
});

/* Generated by @n1k1t/unit-generator */
it('should build a provider with default options if not provided', () => {
  const provider = LlmMistralProvider.build('mistral-large', {
    connection: { key: 'test-key', url: 'https://api.mistral.ai' },
  });
  expect(provider.options).toEqual({});
});

/* Generated by @n1k1t/unit-generator */
it('should build a provider with the specified options', () => {
  const provider = LlmMistralProvider.build('mistral-large', {
    connection: { key: 'test-key', url: 'https://api.mistral.ai' },
    options: { foo: 'bar' },
  });
  expect(provider.options).toEqual({ foo: 'bar' });
});
