import { LlmToolCompiler } from '../tools/model';
import { LanguageModel } from 'ai';
import { LlmProvider } from './model';

/* Generated by @n1k1t/unit-generator */
it('should initialize with model name', () => {
  class TestLlmProvider extends LlmProvider<{ apiKey?: string }> {
    public name = 'test-provider';
    public tag = {} as LanguageModel;
    public clone(): this {
      const clone = new TestLlmProvider(this.model, {
        connection: this.connection,
        options: this.options,
        temperature: this.temperature,
        limit: this.limit,
        tools: this.tools,
      });
      return clone as this;
    }
  }
  const provider = new TestLlmProvider('test-model', {
    connection: { key: 'test-key' },
    options: {},
  });
  expect(provider.model).toBe('test-model');
});

/* Generated by @n1k1t/unit-generator */
it('should initialize with default temperature when not provided', () => {
  class TestLlmProvider extends LlmProvider<{ apiKey?: string }> {
    public name = 'test-provider';
    public tag = {} as LanguageModel;
    public clone(): this {
      const clone = new TestLlmProvider(this.model, {
        connection: this.connection,
        options: this.options,
        temperature: this.temperature,
        limit: this.limit,
        tools: this.tools,
      });
      return clone as this;
    }
  }
  const provider = new TestLlmProvider('test-model', {
    connection: { key: 'test-key' },
    options: {},
  });
  expect(provider.temperature).toBe(0.1);
});

/* Generated by @n1k1t/unit-generator */
it('should initialize with default limit when not provided', () => {
  class TestLlmProvider extends LlmProvider<{ apiKey?: string }> {
    public name = 'test-provider';
    public tag = {} as LanguageModel;
    public clone(): this {
      const clone = new TestLlmProvider(this.model, {
        connection: this.connection,
        options: this.options,
        temperature: this.temperature,
        limit: this.limit,
        tools: this.tools,
      });
      return clone as this;
    }
  }
  const provider = new TestLlmProvider('test-model', {
    connection: { key: 'test-key' },
    options: {},
  });
  expect(provider.limit).toBe(30);
});

/* Generated by @n1k1t/unit-generator */
it('should initialize with custom temperature when provided', () => {
  class TestLlmProvider extends LlmProvider<{ apiKey?: string }> {
    public name = 'test-provider';
    public tag = {} as LanguageModel;
    public clone(): this {
      const clone = new TestLlmProvider(this.model, {
        connection: this.connection,
        options: this.options,
        temperature: this.temperature,
        limit: this.limit,
        tools: this.tools,
      });
      return clone as this;
    }
  }
  const provider = new TestLlmProvider('test-model', {
    connection: { key: 'test-key' },
    options: {},
    temperature: 0.5,
  });
  expect(provider.temperature).toBe(0.5);
});

/* Generated by @n1k1t/unit-generator */
it('should initialize with custom limit when provided', () => {
  class TestLlmProvider extends LlmProvider<{ apiKey?: string }> {
    public name = 'test-provider';
    public tag = {} as LanguageModel;
    public clone(): this {
      const clone = new TestLlmProvider(this.model, {
        connection: this.connection,
        options: this.options,
        temperature: this.temperature,
        limit: this.limit,
        tools: this.tools,
      });
      return clone as this;
    }
  }
  const provider = new TestLlmProvider('test-model', {
    connection: { key: 'test-key' },
    options: {},
    limit: 50,
  });
  expect(provider.limit).toBe(50);
});

/* Generated by @n1k1t/unit-generator */
it('should initialize with options', () => {
  class TestLlmProvider extends LlmProvider<{ apiKey?: string }> {
    public name = 'test-provider';
    public tag = {} as LanguageModel;
    public clone(): this {
      const clone = new TestLlmProvider(this.model, {
        connection: this.connection,
        options: this.options,
        temperature: this.temperature,
        limit: this.limit,
        tools: this.tools,
      });
      return clone as this;
    }
  }
  const provider = new TestLlmProvider('test-model', {
    connection: { key: 'test-key' },
    options: { apiKey: 'secret' },
  });
  expect(provider.options).toEqual({ apiKey: 'secret' });
});

/* Generated by @n1k1t/unit-generator */
it('should initialize with connection details', () => {
  class TestLlmProvider extends LlmProvider<{ apiKey?: string }> {
    public name = 'test-provider';
    public tag = {} as LanguageModel;
    public clone(): this {
      const clone = new TestLlmProvider(this.model, {
        connection: this.connection,
        options: this.options,
        temperature: this.temperature,
        limit: this.limit,
        tools: this.tools,
      });
      return clone as this;
    }
  }
  const provider = new TestLlmProvider('test-model', {
    connection: { key: 'test-key', url: 'http://localhost' },
    options: {},
  });
  expect(provider.connection).toEqual({ key: 'test-key', url: 'http://localhost' });
});

/* Generated by @n1k1t/unit-generator */
it('should initialize with empty tools by default', () => {
  class TestLlmProvider extends LlmProvider<{ apiKey?: string }> {
    public name = 'test-provider';
    public tag = {} as LanguageModel;
    public clone(): this {
      const clone = new TestLlmProvider(this.model, {
        connection: this.connection,
        options: this.options,
        temperature: this.temperature,
        limit: this.limit,
        tools: this.tools,
      });
      return clone as this;
    }
  }
  const provider = new TestLlmProvider('test-model', {
    connection: { key: 'test-key' },
    options: {},
  });
  expect(provider.tools).toEqual({});
});

/* Generated by @n1k1t/unit-generator */
it('should initialize with custom tools when provided', () => {
  class TestLlmProvider extends LlmProvider<{ apiKey?: string }> {
    public name = 'test-provider';
    public tag = {} as LanguageModel;
    public clone(): this {
      const clone = new TestLlmProvider(this.model, {
        connection: this.connection,
        options: this.options,
        temperature: this.temperature,
        limit: this.limit,
        tools: this.tools,
      });
      return clone as this;
    }
  }
  const dummyTool = {} as LlmToolCompiler;
  const provider = new TestLlmProvider('test-model', {
    connection: { key: 'test-key' },
    options: {},
    tools: { dummy: dummyTool },
  });
  expect(provider.tools).toEqual({ dummy: dummyTool });
});

/* Generated by @n1k1t/unit-generator */
it('should assign new temperature and return a cloned instance', () => {
  class TestLlmProvider extends LlmProvider<{ apiKey?: string }> {
    public name = 'test-provider';
    public tag = {} as LanguageModel;
    public clone(): this {
      const clone = new TestLlmProvider(this.model, {
        connection: this.connection,
        options: this.options,
        temperature: this.temperature,
        limit: this.limit,
        tools: this.tools,
      });
      return clone as this;
    }
  }
  const provider = new TestLlmProvider('test-model', {
    connection: { key: 'test-key' },
    options: {},
  });
  const assigned = provider.assign({ temperature: 0.8 });
  expect(assigned.temperature).toBe(0.8);
});

/* Generated by @n1k1t/unit-generator */
it('should not mutate the original instance when assigning temperature', () => {
  class TestLlmProvider extends LlmProvider<{ apiKey?: string }> {
    public name = 'test-provider';
    public tag = {} as LanguageModel;
    public clone(): this {
      const clone = new TestLlmProvider(this.model, {
        connection: this.connection,
        options: this.options,
        temperature: this.temperature,
        limit: this.limit,
        tools: this.tools,
      });
      return clone as this;
    }
  }
  const provider = new TestLlmProvider('test-model', {
    connection: { key: 'test-key' },
    options: {},
  });
  provider.assign({ temperature: 0.8 });
  expect(provider.temperature).toBe(0.1);
});

/* Generated by @n1k1t/unit-generator */
it('should assign new options and return a cloned instance', () => {
  class TestLlmProvider extends LlmProvider<{ apiKey?: string }> {
    public name = 'test-provider';
    public tag = {} as LanguageModel;
    public clone(): this {
      const clone = new TestLlmProvider(this.model, {
        connection: this.connection,
        options: this.options,
        temperature: this.temperature,
        limit: this.limit,
        tools: this.tools,
      });
      return clone as this;
    }
  }
  const provider = new TestLlmProvider('test-model', {
    connection: { key: 'test-key' },
    options: { apiKey: 'old' },
  });
  const assigned = provider.assign({ options: { apiKey: 'new' } });
  expect(assigned.options).toEqual({ apiKey: 'new' });
});

/* Generated by @n1k1t/unit-generator */
it('should assign new tools and return a cloned instance', () => {
  class TestLlmProvider extends LlmProvider<{ apiKey?: string }> {
    public name = 'test-provider';
    public tag = {} as LanguageModel;
    public clone(): this {
      const clone = new TestLlmProvider(this.model, {
        connection: this.connection,
        options: this.options,
        temperature: this.temperature,
        limit: this.limit,
        tools: this.tools,
      });
      return clone as this;
    }
  }
  const provider = new TestLlmProvider('test-model', {
    connection: { key: 'test-key' },
    options: {},
  });
  const dummyTool = {} as LlmToolCompiler;
  const assigned = provider.assign({ tools: { dummy: dummyTool } });
  expect(assigned.tools).toEqual({ dummy: dummyTool });
});

/* Generated by @n1k1t/unit-generator */
it('should assign new limit and return a cloned instance', () => {
  class TestLlmProvider extends LlmProvider<{ apiKey?: string }> {
    public name = 'test-provider';
    public tag = {} as LanguageModel;
    public clone(): this {
      const clone = new TestLlmProvider(this.model, {
        connection: this.connection,
        options: this.options,
        temperature: this.temperature,
        limit: this.limit,
        tools: this.tools,
      });
      return clone as this;
    }
  }
  const provider = new TestLlmProvider('test-model', {
    connection: { key: 'test-key' },
    options: {},
  });
  const assigned = provider.assign({ limit: 100 });
  expect(assigned.limit).toBe(100);
});
