import { LlmProxyProvider } from './proxy';

/* Generated by @n1k1t/unit-generator */
it('should initialize with correct name', () => {
  const provider = new LlmProxyProvider('gpt-4o', {
    connection: { key: 'test-key', url: 'https://api.openai.com/v1' },
    options: {}
  });
  expect(provider.name).toEqual('proxy');
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same model', () => {
  const provider = new LlmProxyProvider('gpt-4o', {
    connection: { key: 'test-key' },
    options: { opt: 1 }
  });
  const clone = provider.clone();
  expect(clone.model).toEqual('gpt-4o');
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same temperature', () => {
  const provider = new LlmProxyProvider('gpt-4o', {
    connection: { key: 'test-key' },
    options: {},
    temperature: 0.5
  });
  const clone = provider.clone();
  expect(clone.temperature).toEqual(0.5);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with the same connection', () => {
  const connection = { key: 'test-key', url: 'https://api.openai.com/v1' };
  const provider = new LlmProxyProvider('gpt-4o', {
    connection,
    options: {}
  });
  const clone = provider.clone();
  expect(clone.connection).toEqual(connection);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with a shallow copy of options', () => {
  const options = { opt: 1 };
  const provider = new LlmProxyProvider('gpt-4o', {
    connection: { key: 'test-key' },
    options
  });
  const clone = provider.clone();
  expect(clone.options).not.toBe(options);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with equal options values', () => {
  const options = { opt: 1 };
  const provider = new LlmProxyProvider('gpt-4o', {
    connection: { key: 'test-key' },
    options
  });
  const clone = provider.clone();
  expect(clone.options).toEqual(options);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with a shallow copy of tools', () => {
  const tools = { tool1: {} as any };
  const provider = new LlmProxyProvider('gpt-4o', {
    connection: { key: 'test-key' },
    options: {},
    tools
  });
  const clone = provider.clone();
  expect(clone.tools).not.toBe(tools);
});

/* Generated by @n1k1t/unit-generator */
it('should clone the provider with equal tools values', () => {
  const tools = { tool1: {} as any };
  const provider = new LlmProxyProvider('gpt-4o', {
    connection: { key: 'test-key' },
    options: {},
    tools
  });
  const clone = provider.clone();
  expect(clone.tools).toEqual(tools);
});

/* Generated by @n1k1t/unit-generator */
it('should build a provider with the correct model', () => {
  const provider = LlmProxyProvider.build('gpt-4o', {
    connection: { key: 'test-key' }
  });
  expect(provider.model).toEqual('gpt-4o');
});

/* Generated by @n1k1t/unit-generator */
it('should build a provider with the correct connection', () => {
  const connection = { key: 'test-key' };
  const provider = LlmProxyProvider.build('gpt-4o', {
    connection
  });
  expect(provider.connection).toEqual(connection);
});

/* Generated by @n1k1t/unit-generator */
it('should build a provider with empty options', () => {
  const provider = LlmProxyProvider.build('gpt-4o', {
    connection: { key: 'test-key' }
  });
  expect(provider.options).toEqual({});
});

/* Generated by @n1k1t/unit-generator */
it('should assign new temperature and return a clone', () => {
  const provider = new LlmProxyProvider('gpt-4o', {
    connection: { key: 'test-key' },
    options: {}
  });
  const assigned = provider.assign({ temperature: 0.8 });
  expect(assigned.temperature).toEqual(0.8);
});

/* Generated by @n1k1t/unit-generator */
it('should assign new options and return a clone', () => {
  const provider = new LlmProxyProvider('gpt-4o', {
    connection: { key: 'test-key' },
    options: { a: 1 }
  });
  const assigned = provider.assign({ options: { b: 2 } });
  expect(assigned.options).toEqual({ b: 2 });
});

/* Generated by @n1k1t/unit-generator */
it('should assign new tools and return a clone', () => {
  const provider = new LlmProxyProvider('gpt-4o', {
    connection: { key: 'test-key' },
    options: {}
  });
  const tools = { t: {} as any };
  const assigned = provider.assign({ tools });
  expect(assigned.tools).toEqual(tools);
});

/* Generated by @n1k1t/unit-generator */
it('should assign new limit and return a clone', () => {
  const provider = new LlmProxyProvider('gpt-4o', {
    connection: { key: 'test-key' },
    options: {}
  });
  const assigned = provider.assign({ limit: 50 });
  expect(assigned.limit).toEqual(50);
});
