import { File } from '../file';
import { Cobertura } from './index';
import { CoberturaItem } from './index';

/* Generated by @n1k1t/unit-generator */
it('CoberturaItem should initialize with path only', () => {
  const item = new CoberturaItem('path/to/file.ts');
  expect(item.path).toEqual('path/to/file.ts');
  expect(item.rate).toEqual(0);
  expect(item.uncovered).toEqual([]);
});

/* Generated by @n1k1t/unit-generator */
it('CoberturaItem should initialize with path, rate, and uncovered', () => {
  const item = new CoberturaItem('path/to/file.ts', 0.5, [10, 20]);
  expect(item.path).toEqual('path/to/file.ts');
  expect(item.rate).toEqual(0.5);
  expect(item.uncovered).toEqual([10, 20]);
});

/* Generated by @n1k1t/unit-generator */
it('CoberturaItem assign should update path', () => {
  const item = new CoberturaItem('old/path.ts');
  item.assign({ path: 'new/path.ts' });
  expect(item.path).toEqual('new/path.ts');
});

/* Generated by @n1k1t/unit-generator */
it('CoberturaItem assign should update rate', () => {
  const item = new CoberturaItem('path.ts', 0);
  item.assign({ rate: 0.75 });
  expect(item.rate).toEqual(0.75);
});

/* Generated by @n1k1t/unit-generator */
it('CoberturaItem assign should update uncovered lines', () => {
  const item = new CoberturaItem('path.ts', 0, []);
  item.assign({ uncovered: [5, 15] });
  expect(item.uncovered).toEqual([5, 15]);
});

/* Generated by @n1k1t/unit-generator */
it('CoberturaItem assign should update multiple properties', () => {
  const item = new CoberturaItem('old/path.ts', 0, []);
  item.assign({ path: 'new/path.ts', rate: 0.9, uncovered: [1, 2] });
  expect(item.path).toEqual('new/path.ts');
  expect(item.rate).toEqual(0.9);
  expect(item.uncovered).toEqual([1, 2]);
});

/* Generated by @n1k1t/unit-generator */
it('CoberturaItem static build should create an instance with path only', () => {
  const item = CoberturaItem.build('build/path.ts');
  expect(item.path).toEqual('build/path.ts');
  expect(item.rate).toEqual(0);
  expect(item.uncovered).toEqual([]);
});

/* Generated by @n1k1t/unit-generator */
it('CoberturaItem static build should create an instance with path and rate', () => {
  const item = CoberturaItem.build('build/path.ts', { rate: 0.6 });
  expect(item.path).toEqual('build/path.ts');
  expect(item.rate).toEqual(0.6);
  expect(item.uncovered).toEqual([]);
});

/* Generated by @n1k1t/unit-generator */
it('CoberturaItem static build should create an instance with path and uncovered', () => {
  const item = CoberturaItem.build('build/path.ts', { uncovered: [30, 40] });
  expect(item.path).toEqual('build/path.ts');
  expect(item.rate).toEqual(0);
  expect(item.uncovered).toEqual([30, 40]);
});

/* Generated by @n1k1t/unit-generator */
it('CoberturaItem static build should create an instance with path, rate, and uncovered', () => {
  const item = CoberturaItem.build('build/path.ts', { rate: 0.8, uncovered: [50, 60] });
  expect(item.path).toEqual('build/path.ts');
  expect(item.rate).toEqual(0.8);
  expect(item.uncovered).toEqual([50, 60]);
});

/* Generated by @n1k1t/unit-generator */
it('parse should default NaN item rate to zero', () => {
  const xml = '<?xml version="1.0"?>\n<coverage>\n  <sources>\n    <source>.</source>\n  </sources>\n  <packages>\n    <package>\n      <classes>\n        <class @_filename="file.ts">\n          <lines></lines>\n        </class>\n      </classes>\n    </package>\n  </packages>\n</coverage>';

  const context: any = { content: xml, items: [], rate: 0, uncovered: [], timestamp: 0 };
  Cobertura.prototype.parse.call(context);

  expect(context.items[0].rate).toEqual(0);
});

/* Generated by @n1k1t/unit-generator */
it('refresh should call File.refresh and then parse', async () => {
  const xml = '<?xml version="1.0"?>\n<coverage>\n  <sources>\n    <source>./src</source>\n  </sources>\n  <packages>\n    <package>\n      <classes>\n        <class @_filename="file.ts">\n          <lines>\n            <line @_number="1" @_hits="0"/>\n          </lines>\n        </class>\n      </classes>\n    </package>\n  </packages>\n</coverage>';
  const cobertura = new Cobertura({ lang: 'xml', path: 'test', content: '' });

  const spy = jest.spyOn(cobertura, 'refresh').mockImplementation(async () => {
    cobertura.content = xml;
    cobertura.parse();
  });

  await cobertura.refresh();

  spy.mockRestore();
  expect(cobertura.items.length).toEqual(1);
});

/* Generated by @n1k1t/unit-generator */
it('Cobertura assign should update rate', () => {
  const context: any = { rate: 0, uncovered: [] };
  Cobertura.prototype.assign.call(context, { rate: 0.85 });
  expect(context.rate).toEqual(0.85);
});

/* Generated by @n1k1t/unit-generator */
it('Cobertura assign should update uncovered', () => {
  const context: any = { rate: 0, uncovered: [] };
  Cobertura.prototype.assign.call(context, { uncovered: [3, 1] });
  expect(context.uncovered).toEqual([3, 1]);
});

/* Generated by @n1k1t/unit-generator */
it('parse should handle missing packages property', () => {
  const xml = '<?xml version="1.0"?>\n<coverage>\n  <sources>\n    <source>./src</source>\n  </sources>\n</coverage>';
  const context: any = { content: xml, items: [], rate: 0, uncovered: [], timestamp: 0 };
  Cobertura.prototype.parse.call(context);
  expect(context.items).toEqual([]);
});

/* Generated by @n1k1t/unit-generator */
it('parse should handle missing classes property', () => {
  const xml = '<?xml version="1.0"?>\n<coverage>\n  <sources>\n    <source>./src</source>\n  </sources>\n  <packages>\n    <package>\n    </package>\n  </packages>\n</coverage>';
  const context: any = { content: xml, items: [], rate: 0, uncovered: [], timestamp: 0 };
  Cobertura.prototype.parse.call(context);
  expect(context.items).toEqual([]);
});

/* Generated by @n1k1t/unit-generator */
it('parse should set rate to 0 when no items exist', () => {
  const xml = '<?xml version="1.0"?>\n<coverage>\n  <sources>\n    <source>./src</source>\n  </sources>\n  <packages>\n  </packages>\n</coverage>';
  const context: any = { content: xml, items: [], rate: 0, uncovered: [], timestamp: 0 };
  Cobertura.prototype.parse.call(context);
  expect(context.rate).toEqual(0);
});

/* Generated by @n1k1t/unit-generator */
it('static build should create Cobertura instance from file location', async () => {
  const mockFile = { lang: 'xml', path: 'test.xml', content: '<?xml version="1.0"?>\n<coverage>\n  <sources>\n    <source>./src</source>\n  </sources>\n  <packages>\n    <package>\n      <classes>\n        <class @_filename="file.ts" @_branch-rate="0.5" @_line-rate="0.3">\n          <lines></lines>\n        </class>\n      </classes>\n    </package>\n  </packages>\n</coverage>' };
  jest.spyOn(File, 'build').mockResolvedValue(mockFile as any);
  const cobertura = await Cobertura.build('test.xml');
  expect(cobertura.items.length).toEqual(1);
  jest.restoreAllMocks();
});
