import { Cobertura, CoberturaItem } from './index';
import { File } from '../file';

/* Generated by @n1k1t/unit-generator */
it('should create a CoberturaItem instance with default values', () => {
  const item = new CoberturaItem('path/to/file.ts');
  expect(item.rate).toEqual(0);
  expect(item.uncovered).toEqual([]);
});

/* Generated by @n1k1t/unit-generator */
it('should update CoberturaItem properties using assign', () => {
  const item = new CoberturaItem('path/to/file.ts');
  item.assign({ rate: 0.5, uncovered: [1, 2] });
  expect(item.rate).toEqual(0.5);
  expect(item.uncovered).toEqual([1, 2]);
});

/* Generated by @n1k1t/unit-generator */
it('should build a CoberturaItem using static build method', () => {
  const item = CoberturaItem.build('path/to/file.ts', {
    rate: 0.8,
    uncovered: [5],
  });
  expect(item.path).toEqual('path/to/file.ts');
  expect(item.rate).toEqual(0.8);
  expect(item.uncovered).toEqual([5]);
});

/* Generated by @n1k1t/unit-generator */
it('should create a CoberturaItem instance', () => {
  const item = new CoberturaItem('path/to/file', 0.5, [1, 2]);
  expect(item.path).toBe('path/to/file');
  expect(item.rate).toBe(0.5);
  expect(item.uncovered).toEqual([1, 2]);
});

/* Generated by @n1k1t/unit-generator */
it('should assign values to CoberturaItem', () => {
  const item = new CoberturaItem('path');
  item.assign({ rate: 0.8 });
  expect(item.rate).toBe(0.8);
});

/* Generated by @n1k1t/unit-generator */
it('should build a CoberturaItem using static method', () => {
  const item = CoberturaItem.build('path', { rate: 0.9 });
  expect(item.rate).toBe(0.9);
});

/* Generated by @n1k1t/unit-generator */
it('should parse cobertura content correctly', async () => {
  const content =
    '<coverage timestamp="123"><packages><package><classes><class filename="test.ts" line-rate="0.5" branch-rate="0.5"><lines><line number="1" hits="0" /></lines></class></classes></package></packages></coverage>';
  const file = new File({ cwd: '.', path: 'test.xml', content, lang: 'xml' });
  const cobertura = new Cobertura(file);
  cobertura.parse();
  expect(cobertura.timestamp).toBe(123);
  expect(cobertura.rate).toBe(0.5);
  expect(cobertura.uncovered).toEqual([1]);
});

/* Generated by @n1k1t/unit-generator */
it('should handle empty coverage', async () => {
  const content = '<coverage></coverage>';
  const file = new File({ cwd: '.', path: 'test.xml', content, lang: 'xml' });
  const cobertura = new Cobertura(file);
  cobertura.parse();
  expect(cobertura.rate).toBe(0);
  expect(cobertura.items).toEqual([]);
});

/* Generated by @n1k1t/unit-generator */
it('should build from location', async () => {
  const content = '<coverage timestamp="789"></coverage>';
  jest
    .spyOn(File, 'build')
    .mockResolvedValue(
      new File({ cwd: '.', path: 'test.xml', content, lang: 'xml' }),
    );
  const cobertura = await Cobertura.build('test.xml');
  expect(cobertura.timestamp).toBe(789);
});

/* Generated by @n1k1t/unit-generator */
it('should assign properties', async () => {
  const cobertura = new Cobertura(
    new File({ cwd: '.', path: 'test.xml', content: '', lang: 'xml' }),
  );
  cobertura.assign({ rate: 0.8 });
  expect(cobertura.rate).toBe(0.8);
});

/* Generated by @n1k1t/unit-generator */
it('should assign CoberturaItem properties', async () => {
  const item = new CoberturaItem('path');
  item.assign({ rate: 0.9 });
  expect(item.rate).toBe(0.9);
});
