import * as providers from './providers';
import env from '../../env';

import { LLlmModelProviderName } from './types';
import { LlmRouter } from './router';

/* Generated by @n1k1t/unit-generator */
it('should default to openai provider when model contains gpt', () => {
  const router = LlmRouter.build({ key: 'test-key', provider: undefined });
  const result = router.provide('gpt-4o');
  expect(result).toBeDefined();
});

/* Generated by @n1k1t/unit-generator */
it('should route claude model to anthropic when provider not explicitly configured', () => {
  const router = LlmRouter.build({ key: 'test-key', provider: undefined });
  const result = router.provide('claude-3-haiku');
  expect(result).toBeDefined();
});

/* Generated by @n1k1t/unit-generator */
it('should route gemini model to google when provider not explicitly configured', () => {
  const router = LlmRouter.build({ key: 'test-key', provider: undefined });
  const result = router.provide('gemini-1.5-flash');
  expect(result).toBeDefined();
});

/* Generated by @n1k1t/unit-generator */
it('should route mistral model to mistral when provider not explicitly configured', () => {
  const router = LlmRouter.build({ key: 'test-key', provider: undefined });
  const result = router.provide('mistral-small');
  expect(result).toBeDefined();
});

/* Generated by @n1k1t/unit-generator */
it('should fall back to openai provider when model hint does not match', () => {
  const router = LlmRouter.build({ key: 'test-key', provider: undefined });
  const result = router.provide('unknown-model');
  expect(result).toBeDefined();
});

/* Generated by @n1k1t/unit-generator */
it('should use explicit provider when it is valid', () => {
  const router = LlmRouter.build({ key: 'test-key', provider: 'anthropic' });
  const result = router.provide('some-model');
  expect(result).toBeDefined();
});

/* Generated by @n1k1t/unit-generator */
it('should fall back to define() when explicit provider name is invalid', () => {
  const router = LlmRouter.build({ key: 'test-key', provider: 'not-a-real-provider' });
  const result = router.provide('gpt-4o');
  expect(result).toBeDefined();
});

/* Generated by @n1k1t/unit-generator */
it('should pass url option through router configuration', () => {
  const router = LlmRouter.build({
    key: 'test-key',
    provider: 'openai',
    url: 'https://example.com',
  });
  const result = router.provide('gpt-4o');
  expect((result as any).connection?.url).toEqual('https://example.com');
});

/* Generated by @n1k1t/unit-generator */
it('should map provider directly when configuration provider is present in LLlmModelProviderName', () => {
  const openaiBuildSpy = jest.spyOn(providers.LlmOpenaiProvider, 'build').mockReturnValue({} as any);

  const router = new LlmRouter({ key: 'k', provider: 'openai', url: undefined });
  const result = router.provide('gpt-ignored');

  expect(result).toBeDefined();
  openaiBuildSpy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should define openai for gpt* models when provider is not set', () => {
  const buildSpy = jest.spyOn(providers.LlmOpenaiProvider, 'build').mockReturnValue({} as any);

  const router = new LlmRouter({ key: 'k', provider: undefined, url: undefined });
  router.provide('gpt-4');

  expect(buildSpy).toHaveBeenCalled();
  buildSpy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should define anthropic for claude* models when provider is not set', () => {
  const buildSpy = jest.spyOn(providers.LlmAnthropicProvider, 'build').mockReturnValue({} as any);

  const router = new LlmRouter({ key: 'k', provider: undefined, url: undefined });
  router.provide('claude-3-opus');

  expect(buildSpy).toHaveBeenCalled();
  buildSpy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should define google for gemini* models when provider is not set', () => {
  const buildSpy = jest.spyOn(providers.LlmGoogleProvider, 'build').mockReturnValue({} as any);

  const router = new LlmRouter({ key: 'k', provider: undefined, url: undefined });
  router.provide('gemini-pro');

  expect(buildSpy).toHaveBeenCalled();
  buildSpy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should define mistral for mistral* models when provider is not set', () => {
  const buildSpy = jest.spyOn(providers.LlmMistralProvider, 'build').mockReturnValue({} as any);

  const router = new LlmRouter({ key: 'k', provider: undefined, url: undefined });
  router.provide('mistral-small');

  expect(buildSpy).toHaveBeenCalled();
  buildSpy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should define mistral for pixtral* models when provider is not set', () => {
  const buildSpy = jest.spyOn(providers.LlmMistralProvider, 'build').mockReturnValue({} as any);

  const router = new LlmRouter({ key: 'k', provider: undefined, url: undefined });
  router.provide('pixtral-large');

  expect(buildSpy).toHaveBeenCalled();
  buildSpy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('should build router using env fallback values when options are not provided', () => {
  const router = LlmRouter.build();

  expect(router).toBeInstanceOf(LlmRouter);
  expect(env).toBeDefined();
});

/* Generated by @n1k1t/unit-generator */
it('static build should use provided options values over env', () => {
  const openaiBuildSpy = jest.spyOn(providers.LlmOpenaiProvider, 'build').mockReturnValue({} as any);

  const router = LlmRouter.build({ provider: 'openai', key: 'custom-key', url: 'http://example.com' });
  router.provide('gpt-4');

  expect(openaiBuildSpy).toHaveBeenCalled();
  openaiBuildSpy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('LLlmModelProviderName should contain the supported provider names', () => {
  const providersList = LLlmModelProviderName;

  expect(providersList.length).toBeGreaterThan(0);
});
