import { BashExecError } from './bash'
import { Bash } from './bash'

/* Generated by @n1k1t/unit-generator */
it('should execute a simple command successfully', async () => {
  const bash = Bash.build();
  const result = await bash.exec('echo hello');
  expect(result).toEqual({ status: 'OK', stdout: 'hello\n' });
})

/* Generated by @n1k1t/unit-generator */
it('should return an error for a non-existent command', async () => {
  const bash = Bash.build();
  const result = await bash.exec('non-existent-command-12345');
  expect(result.status).toEqual('ERROR');
})

/* Generated by @n1k1t/unit-generator */
it('should create BashExecError with default message when stderr is empty', () => {
  const error = new BashExecError('cmd', 1, '');
  expect(error.message).toBe('Bash execution error');
});

/* Generated by @n1k1t/unit-generator */
it('should create Bash instance using static build method', () => {
  const bash = Bash.build({ cwd: '/tmp' });
  expect(bash).toBeInstanceOf(Bash);
});
