import { File } from './file';
import fs from 'fs/promises';

/* Generated by @n1k1t/unit-generator */
it('append should add content when non-empty', () => {
  const f = new File({ path: '/tmp/a.txt', lang: 'txt', content: 'hello' });
  f.append('world');
  expect(f.content).toEqual('hello\nworld');
});

/* Generated by @n1k1t/unit-generator */
it('append should not change content when empty', () => {
  const f = new File({ path: '/tmp/a.txt', lang: 'txt', content: 'hello' });
  f.append('');
  expect(f.content).toEqual('hello');
});

/* Generated by @n1k1t/unit-generator */
it('prepend should add content when non-empty', () => {
  const f = new File({ path: '/tmp/a.txt', lang: 'txt', content: 'world' });
  f.prepend('hello');
  expect(f.content).toEqual('hello\nworld');
});

/* Generated by @n1k1t/unit-generator */
it('prepend should not change content when empty', () => {
  const f = new File({ path: '/tmp/a.txt', lang: 'txt', content: 'world' });
  f.prepend('');
  expect(f.content).toEqual('world');
});

/* Generated by @n1k1t/unit-generator */
it('write should update content and call fs.writeFile', async () => {
  const spy = jest.spyOn(fs, 'writeFile').mockResolvedValue();
  const f = new File({ path: '/tmp/a.txt', lang: 'txt', content: 'old' });
  await f.write('new');
  expect(spy).toHaveBeenCalledWith('/tmp/a.txt', 'new', 'utf8');
});

/* Generated by @n1k1t/unit-generator */
it('refresh should load content from file', async () => {
  jest.spyOn(fs, 'readFile').mockResolvedValue('file-content');
  const f = new File({ path: '/tmp/a.txt', lang: 'txt', content: 'old' });
  await f.refresh();
  expect(f.content).toEqual('file-content');
});

/* Generated by @n1k1t/unit-generator */
it('remove should call fs.rm with path', async () => {
  const spy = jest.spyOn(fs, 'rm').mockResolvedValue();
  const f = new File({ path: '/tmp/a.txt', lang: 'txt', content: 'c' });
  await f.remove();
  expect(spy).toHaveBeenCalledWith('/tmp/a.txt');
});

/* Generated by @n1k1t/unit-generator */
it('build should create file if missing and return File', async () => {
  const location = '/tmp/new.txt';
  jest.spyOn(fs, 'stat').mockImplementation(() => Promise.reject(new Error('no')));
  jest.spyOn(fs, 'writeFile').mockResolvedValue();
  jest.spyOn(fs, 'readFile').mockResolvedValue('');
  const result = await File.build(location);
  expect(result.path).toEqual(location);
});
