import { File, FileReplaceError, FileBuildError } from './file'
import fs from 'fs/promises'

/* Generated by @n1k1t/unit-generator */
it('should append content to the file', () => {
  const file = new File({ cwd: '/tmp', lang: 'txt', path: 'test.txt', content: 'hello' });
  file.append('world');
  expect(file.content).toEqual('hello\nworld');
})

/* Generated by @n1k1t/unit-generator */
it('should prepend content to the file', () => {
  const file = new File({ cwd: '/tmp', lang: 'txt', path: 'test.txt', content: 'world' });
  file.prepend('hello');
  expect(file.content).toEqual('hello\nworld');
})

/* Generated by @n1k1t/unit-generator */
it('should replace content in the file', () => {
  const file = new File({ cwd: '/tmp', lang: 'txt', path: 'test.txt', content: 'hello world' });
  file.replace('world', 'universe');
  expect(file.content).toEqual('hello universe');
})

/* Generated by @n1k1t/unit-generator */
it('should throw FileReplaceError when replacing non-existent content in strict mode', () => {
  const file = new File({ cwd: '/', lang: 'txt', path: 'test.txt', content: 'hello', options: { strict: true } });
  expect(() => file.replace('missing', 'target')).toThrow(FileReplaceError);
});

/* Generated by @n1k1t/unit-generator */
it('should throw FileReplaceError when replacing ambiguous content in strict mode', () => {
  const file = new File({ cwd: '/', lang: 'txt', path: 'test.txt', content: 'a\na\na', options: { strict: true } });
  expect(() => file.replace('a', 'b')).toThrow(FileReplaceError);
});

/* Generated by @n1k1t/unit-generator */
it('should throw FileBuildError when trying to build a directory', async () => {
  jest.spyOn(fs, 'stat').mockResolvedValue({ isDirectory: () => true } as any);
  await expect(File.build('dir')).rejects.toThrow(FileBuildError);
});

/* Generated by @n1k1t/unit-generator */
it('should throw FileBuildError when file does not exist in strict existent mode', async () => {
  jest.spyOn(fs, 'stat').mockRejectedValue(null);
  await expect(File.build('test.txt', { strict: true, state: 'existent' })).rejects.toThrow(FileBuildError);
});

/* Generated by @n1k1t/unit-generator */
it('should throw FileBuildError when file exists in strict new mode', async () => {
  jest.spyOn(fs, 'stat').mockResolvedValue({ isDirectory: () => false } as any);
  await expect(File.build('test.txt', { strict: true, state: 'new' })).rejects.toThrow(FileBuildError);
});

/* Generated by @n1k1t/unit-generator */
it('should write content to file', async () => {
  const spy = jest.spyOn(fs, 'writeFile').mockResolvedValue(undefined);
  jest.spyOn(fs, 'mkdir').mockResolvedValue(undefined);
  const file = new File({ cwd: '/', lang: 'txt', path: 'test.txt', content: 'content' });
  await file.write('new content');
  expect(spy).toHaveBeenCalledWith('/test.txt', 'new content', 'utf8');
});

/* Generated by @n1k1t/unit-generator */
it('should refresh content from file', async () => {
  jest.spyOn(fs, 'readFile').mockResolvedValue('file content');
  const file = new File({ cwd: '/', lang: 'txt', path: 'test.txt', content: 'old' });
  await file.refresh();
  expect(file.content).toBe('file content');
});

/* Generated by @n1k1t/unit-generator */
it('should remove file', async () => {
  const spy = jest.spyOn(fs, 'rm').mockResolvedValue(undefined);
  const file = new File({ cwd: '/', lang: 'txt', path: 'test.txt', content: 'content' });
  await file.remove();
  expect(spy).toHaveBeenCalledWith('/test.txt');
});

/* Generated by @n1k1t/unit-generator */
it('should not append empty content', () => {
  const file = new File({ cwd: '/', lang: 'txt', path: 'test.txt', content: 'a' });
  file.append('');
  expect(file.content).toBe('a');
});

/* Generated by @n1k1t/unit-generator */
it('should not prepend empty content', () => {
  const file = new File({ cwd: '/', lang: 'txt', path: 'test.txt', content: 'a' });
  file.prepend('');
  expect(file.content).toBe('a');
});
