/* Generated by @n1k1t/unit-generator */
it('should re-export AssistantExport from assistant module', () => {
  jest.resetModules();
  const mockAssistantExport = 'mockedAssistantValue';
  jest.doMock('./assistant', () => ({
    AssistantExport: mockAssistantExport,
  }));
  const { AssistantExport } = require('./index');
  expect(AssistantExport).toBe(mockAssistantExport);
});

/* Generated by @n1k1t/unit-generator */
it('should re-export CoberturaExport from cobertura module', () => {
  jest.resetModules();
  const mockCoberturaExport = 'mockedCoberturaValue';
  jest.doMock('./cobertura', () => ({
    CoberturaExport: mockCoberturaExport,
  }));
  const { CoberturaExport } = require('./index');
  expect(CoberturaExport).toBe(mockCoberturaExport);
});

/* Generated by @n1k1t/unit-generator */
it('should re-export FileExport from file module', () => {
  jest.resetModules();
  const mockFileExport = 'mockedFileValue';
  jest.doMock('./file', () => ({
    FileExport: mockFileExport,
  }));
});
