import fs from 'fs/promises';

import { AttachmentContent } from './content';
import { GroupContent } from './content';
import { Project } from './project';

/* Generated by @n1k1t/unit-generator */
it('should return empty group content when dependencies are missing', () => {
  const project = new Project({ sources: { ignore: [], files: [] } });
  expect(project.content.dependencies().type).toBe('group');
});

/* Generated by @n1k1t/unit-generator */
it('should return attachment content when dependencies exist', () => {
  const project = new Project({
    sources: { ignore: [], files: [], dependencies: { lodash: '4.17.21' } },
  });
  const content = project.content.dependencies();
  expect(content).toBeInstanceOf(AttachmentContent);
});

/* Generated by @n1k1t/unit-generator */
it('should return empty group content when editorconfig is missing', () => {
  const project = new Project({ sources: { ignore: [], files: [] } });
  expect(project.content.editorconfig().type).toBe('group');
});

/* Generated by @n1k1t/unit-generator */
it('should return attachment content when editorconfig exists', () => {
  const project = new Project({
    sources: { ignore: [], files: [], editorconfig: 'indent_size = 2' },
  });
  const content = project.content.editorconfig();
  expect(content).toBeInstanceOf(AttachmentContent);
});

/* Generated by @n1k1t/unit-generator */
it('should add a file to the project files list', () => {
  const project = new Project({ sources: { ignore: [], files: ['a.ts'] } });
  project.files.add('b.ts');
  expect(project.sources.files).toContain('b.ts');
});

/* Generated by @n1k1t/unit-generator */
it('should remove files matching the path prefix', () => {
  const project = new Project({
    sources: { ignore: [], files: ['src/a.ts', 'src/b.ts', 'test/c.ts'] },
  });
  project.files.rm('src/');
  expect(project.sources.files).toEqual(['test/c.ts']);
});

/* Generated by @n1k1t/unit-generator */
it('should return empty GroupContent when dependencies are missing', () => {
  const project = new Project({ sources: { ignore: [], files: [] } });
  expect(project.content.dependencies()).toEqual(GroupContent.build([]));
});

/* Generated by @n1k1t/unit-generator */
it('should return empty GroupContent when editorconfig is missing', () => {
  const project = new Project({ sources: { ignore: [], files: [] } });
  expect(project.content.editorconfig()).toEqual(GroupContent.build([]));
});

/* Generated by @n1k1t/unit-generator */
it('should return empty GroupContent when no files match the tree pattern', () => {
  const project = new Project({ sources: { ignore: [], files: [] } });
  expect(project.content.tree(['non-existent'])).toEqual(
    GroupContent.build([]),
  );
});

/* Generated by @n1k1t/unit-generator */
it('should return all files when no patterns are provided to glob', () => {
  const files = ['a.ts', 'b.js'];
  const project = new Project({ sources: { ignore: [], files } });
  expect(project.files.glob()).toEqual(files);
});

/* Generated by @n1k1t/unit-generator */
it('should add a new file path to the project files', () => {
  const project = new Project({ sources: { ignore: [], files: ['a.ts'] } });
  project.files.add('b.ts');
  expect(project.sources.files).toContain('b.ts');
});

/* Generated by @n1k1t/unit-generator */
it('should remove files starting with the given path', () => {
  const project = new Project({
    sources: { ignore: [], files: ['src/a.ts', 'src/b.ts', 'test/c.ts'] },
  });
  project.files.rm('src/');
  expect(project.sources.files).toEqual(['test/c.ts']);
});

/* Generated by @n1k1t/unit-generator */
it('should return GroupContent when dependencies are missing', () => {
  const project = new Project({ sources: { ignore: [], files: [] } });
  const result = project.content.dependencies();
  expect(result).toBeInstanceOf(GroupContent);
});

/* Generated by @n1k1t/unit-generator */
it('should return GroupContent when editorconfig is missing', () => {
  const project = new Project({ sources: { ignore: [], files: [] } });
  const result = project.content.editorconfig();
  expect(result).toBeInstanceOf(GroupContent);
});

/* Generated by @n1k1t/unit-generator */
it('should return GroupContent when tree files are empty', () => {
  const project = new Project({ sources: { ignore: [], files: [] } });
  const result = project.content.tree(['non-existent']);
  expect(result).toBeInstanceOf(GroupContent);
});

/* Generated by @n1k1t/unit-generator */
it('should return all files when no patterns are provided to glob', () => {
  const project = new Project({
    sources: { ignore: [], files: ['a.ts', 'b.js'] },
  });
  const result = project.files.glob();
  expect(result).toEqual(['a.ts', 'b.js']);
});

/* Generated by @n1k1t/unit-generator */
it('should add a new file path to sources', () => {
  const project = new Project({ sources: { ignore: [], files: ['a.ts'] } });
  project.files.add('b.ts');
  expect(project.sources.files).toContain('b.ts');
});

/* Generated by @n1k1t/unit-generator */
it('should remove files starting with the given path', () => {
  const project = new Project({
    sources: { ignore: [], files: ['src/a.ts', 'src/b.ts', 'test/c.ts'] },
  });
  project.files.rm('src/');
  expect(project.sources.files).toEqual(['test/c.ts']);
});

/* Generated by @n1k1t/unit-generator */
it('should return empty GroupContent when dependencies are missing', () => {
  const project = new Project({ sources: { ignore: [], files: [] } });
  expect(project.content.dependencies()).toEqual(GroupContent.build([]));
});

/* Generated by @n1k1t/unit-generator */
it('should return AttachmentContent when dependencies are present', () => {
  const project = new Project({
    sources: { ignore: [], files: [], dependencies: { lodash: '4.17.21' } },
  });
  expect(project.content.dependencies()).toBeInstanceOf(AttachmentContent);
});

/* Generated by @n1k1t/unit-generator */
it('should return empty GroupContent when editorconfig is missing', () => {
  const project = new Project({ sources: { ignore: [], files: [] } });
  expect(project.content.editorconfig()).toEqual(GroupContent.build([]));
});

/* Generated by @n1k1t/unit-generator */
it('should return AttachmentContent when editorconfig is present', () => {
  const project = new Project({
    sources: { ignore: [], files: [], editorconfig: 'indent_size = 2' },
  });
  expect(project.content.editorconfig()).toBeInstanceOf(AttachmentContent);
});

/* Generated by @n1k1t/unit-generator */
it('should return empty GroupContent when no files match the tree pattern', () => {
  const project = new Project({ sources: { ignore: [], files: [] } });
  expect(project.content.tree(['non-existent'])).toEqual(
    GroupContent.build([]),
  );
});

/* Generated by @n1k1t/unit-generator */
it('should return AttachmentContent when files match the tree pattern', () => {
  const project = new Project({
    sources: { ignore: [], files: ['src/index.ts'] },
  });
  expect(project.content.tree(['.'])).toBeInstanceOf(AttachmentContent);
});

/* Generated by @n1k1t/unit-generator */
it('should add a file to the project sources', () => {
  const project = new Project({ sources: { ignore: [], files: [] } });
  project.files.add('new-file.ts');
  expect(project.sources.files).toContain('new-file.ts');
});

/* Generated by @n1k1t/unit-generator */
it('should remove a file from the project sources', () => {
  const project = new Project({
    sources: { ignore: [], files: ['file1.ts', 'file2.ts'] },
  });
  project.files.rm('file1.ts');
  expect(project.sources.files).not.toContain('file1.ts');
});

/* Generated by @n1k1t/unit-generator */
it('should build project instance with default options', async () => {
  const project = await Project.build();
  expect(project).toBeInstanceOf(Project);
});

/* Generated by @n1k1t/unit-generator */
it('should parse dependencies from package.json during build', async () => {
  jest
    .spyOn(fs, 'readFile')
    .mockResolvedValue(JSON.stringify({ dependencies: { lodash: '4.17.21' } }));
  const project = await Project.build();
  expect(project.sources.dependencies).toEqual({ lodash: '4.17.21' });
});

/* Generated by @n1k1t/unit-generator */
it('should filter out @types dependencies during build', async () => {
  jest
    .spyOn(fs, 'readFile')
    .mockResolvedValue(
      JSON.stringify({
        dependencies: { '@types/node': '18.0.0', lodash: '4.17.21' },
      }),
    );
  const project = await Project.build();
  expect(project.sources.dependencies).toEqual({ lodash: '4.17.21' });
});
