import env from '../env'
import path from 'path'
import os from 'os'

import { File } from './file';
import { Spec } from './spec';

/* Generated by @n1k1t/unit-generator */
it('parses import and require statements into imports array', () => {
  const spec = Object.create(Spec.prototype) as Spec;
  spec.content = "import fs from 'fs';\nconst p = require('path');\nconst a = 1;";
  spec.lang = 'ts';
  spec.parse();
  expect(spec.imports).toContain("import fs from 'fs';");
})

/* Generated by @n1k1t/unit-generator */
it('does not include variable declarations without require', () => {
  const spec = Object.create(Spec.prototype) as Spec;
  spec.content = "const a = 1;\nconst b = 2;";
  spec.lang = 'js';
  spec.parse();
  expect(spec.imports).not.toContain('const a = 1;');
})

/* Generated by @n1k1t/unit-generator */
it('extractImportNodes returns empty array on parse error', () => {
  const spec = Object.create(Spec.prototype) as Spec;
  spec.content = 'invalid {';
  spec.lang = 'js';
  const nodes = (spec as any).extractAstNodes();
  expect(nodes).toEqual([]);
})

/* Generated by @n1k1t/unit-generator */
it('initializes imports to empty array', async () => {
  jest.resetModules();
  jest.doMock('./file', () => {
    class File {
      constructor(file?: File) {}
      static async build(location: string) {
        return new File();
      }
      async write(content: string) {}
      async refresh() {}
    }
    return { File };
  });
  const { Spec } = require('./spec');
  const { File } = require('./file');
  const spec = new Spec(new File());
  expect(spec.imports).toEqual([]);
});

/* Generated by @n1k1t/unit-generator */
it('write calls super.write with content', async () => {
  jest.resetModules();
  jest.doMock('./file', () => {
    class File {
      constructor(file: File) {}
      async write(content: string) {}
    }
    return { File };
  });
  const { Spec } = require('./spec');
  const { File } = require('./file');
  const spec = new Spec(new File());
  const spy = jest.spyOn(File.prototype, 'write').mockResolvedValue(undefined);
  await spec.write('hello');
  expect(spy).toHaveBeenCalledWith('hello');
});

/* Generated by @n1k1t/unit-generator */
it('write calls parse after super.write', async () => {
  jest.resetModules();
  jest.doMock('./file', () => {
    class File {
      constructor(file: File) {}
      async write(content: string) {}
    }
    return { File };
  });
  const { Spec } = require('./spec');
  const { File } = require('./file');
  const spec = new Spec(new File());
  const parseSpy = jest.spyOn(Spec.prototype, 'parse').mockImplementation(function(this: File) {
    return this;
  });
  await spec.write('content');
  expect(parseSpy).toHaveBeenCalledTimes(1);
});

/* Generated by @n1k1t/unit-generator */
it('refresh calls parent refresh', async () => {
  const instance = Object.create(Spec.prototype) as Spec;
  const superRefresh = jest.spyOn(File.prototype, 'refresh').mockImplementation(async () => {});
  const parseSpy = jest.spyOn(Spec.prototype, 'parse').mockReturnThis();
  await instance.refresh();
  expect(superRefresh).toHaveBeenCalled();
});

/* Generated by @n1k1t/unit-generator */
it('refresh calls parse', async () => {
  const instance = Object.create(Spec.prototype) as Spec;
  jest.spyOn(File.prototype, 'refresh').mockImplementation(async () => {});
  const parseSpy = jest.spyOn(Spec.prototype, 'parse').mockReturnThis();
  await instance.refresh();
  expect(parseSpy).toHaveBeenCalled();
});

/* Generated by @n1k1t/unit-generator */
it('replace should replace all occurrences of source with target', () => {
  const fileLike = { path: 'e.ts', lang: 'ts', content: 'hello world hello' } as any;
  const spec = new Spec(fileLike);
  spec.replace('hello', 'hi');
  expect(spec.content).toBe('hi world hi');
});

/* Generated by @n1k1t/unit-generator */
it('parse should handle invalid source by producing no imports/helpers', () => {
  const fileLike = { path: 'f.ts', lang: 'ts', content: '<<< invalid code >>>' } as any;
  const spec = new Spec(fileLike);
  spec.parse();
  expect(spec.imports.length).toBe(0);
});

/* Generated by @n1k1t/unit-generator */
it('replace replaces all occurrences', () => {
  const spec = new Spec({ path: 'a.ts', lang: 'ts', content: 'foo bar foo' });
  spec.replace('foo', 'baz');
  expect(spec.content).toBe('baz bar baz');
});

/* Generated by @n1k1t/unit-generator */
it('parse handles invalid content without throwing and results in no tests', () => {
  const spec = new Spec({ path: 'invalid.ts', lang: 'ts', content: '<<<' });
  const parsed = spec.parse();
  expect(parsed.tests.length).toBe(0);
});

/* Generated by @n1k1t/unit-generator */
it('replace replaces occurrences', async () => {
  const file = new File({ path: '/tmp/spec-replace.ts', lang: 'ts', content: 'hello foo world' });
  const spec = new Spec(file);

  spec.replace('foo', 'bar');

  expect(spec.content).toContain('bar');
});

/* Generated by @n1k1t/unit-generator */
it('parse handles invalid content by returning empty arrays', async () => {
  const file = new File({ path: '/tmp/spec-parse-invalid.ts', lang: 'ts', content: '' });
  const spec = new Spec(file);

  spec.content = '<<invalid code>>';
  spec.parse();

  expect(spec.imports).toHaveLength(0);
});

/* Generated by @n1k1t/unit-generator */
it('write calls parse after writing', async () => {
  const location = path.join(os.tmpdir(), 'spec-write-test.ts');
  const file = new File({ path: location, lang: 'ts', content: '' });
  const spec = new Spec(file);

  const spy = jest.spyOn(Spec.prototype, 'parse');

  await spec.write('content');

  expect(spy).toHaveBeenCalled();

  spy.mockRestore();
});

/* Generated by @n1k1t/unit-generator */
it('replace should replace all occurrences and return self', () => {
  const file = new File({ path: path.join(os.tmpdir(), 'replace.test.ts'), lang: 'ts', content: 'hello world hello' });
  const spec = new Spec(file);

  const returned = spec.replace('hello', 'hi');

  expect(returned).toBe(spec);
});

/* Generated by @n1k1t/unit-generator */
it('parse should handle parser errors and result in empty imports/helpers/tests', () => {
  const file = new File({ path: path.join(os.tmpdir(), 'parse-error.test.ts'), lang: 'ts', content: '<<<' });
  const spec = new Spec(file);

  spec.parse();

  expect(spec.imports).toEqual([]);
});

/* Generated by @n1k1t/unit-generator */
it('extractTests should handle describe nesting and remove env.marker from test content', () => {
  const source = `describe('group', () => {\n  ${env.marker}\n  it('should do something', () => {})\n})`;
  const file = new File({ path: path.join(os.tmpdir(), 'describe.test.ts'), lang: 'ts', content: source });
  const spec = new Spec(file);

  spec.parse();

  expect(spec.tests[0].title).toBe('group.should do something');
});
