import { File } from './file';
import { Spec } from './spec';

/* Generated by @n1k1t/unit-generator */
it('parses import and require statements into imports array', () => {
  const spec = Object.create(Spec.prototype) as Spec;
  spec.content = "import fs from 'fs';\nconst p = require('path');\nconst a = 1;";
  spec.lang = 'ts';
  spec.parse();
  expect(spec.imports).toContain("import fs from 'fs';");
})

/* Generated by @n1k1t/unit-generator */
it('does not include variable declarations without require', () => {
  const spec = Object.create(Spec.prototype) as Spec;
  spec.content = "const a = 1;\nconst b = 2;";
  spec.lang = 'js';
  spec.parse();
  expect(spec.imports).not.toContain('const a = 1;');
})

/* Generated by @n1k1t/unit-generator */
it('extractImportNodes returns empty array on parse error', () => {
  const spec = Object.create(Spec.prototype) as Spec;
  spec.content = 'invalid {';
  spec.lang = 'js';
  const nodes = (spec as any).extractAstNodes();
  expect(nodes).toEqual([]);
})

/* Generated by @n1k1t/unit-generator */
it('initializes imports to empty array', async () => {
  jest.resetModules();
  jest.doMock('./file', () => {
    class File {
      constructor(file?: File) {}
      static async build(location: string) {
        return new File();
      }
      async write(content: string) {}
      async refresh() {}
    }
    return { File };
  });
  const { Spec } = require('./spec');
  const { File } = require('./file');
  const spec = new Spec(new File());
  expect(spec.imports).toEqual([]);
});

/* Generated by @n1k1t/unit-generator */
it('write calls super.write with content', async () => {
  jest.resetModules();
  jest.doMock('./file', () => {
    class File {
      constructor(file: File) {}
      async write(content: string) {}
    }
    return { File };
  });
  const { Spec } = require('./spec');
  const { File } = require('./file');
  const spec = new Spec(new File());
  const spy = jest.spyOn(File.prototype, 'write').mockResolvedValue(undefined);
  await spec.write('hello');
  expect(spy).toHaveBeenCalledWith('hello');
});

/* Generated by @n1k1t/unit-generator */
it('write calls parse after super.write', async () => {
  jest.resetModules();
  jest.doMock('./file', () => {
    class File {
      constructor(file: File) {}
      async write(content: string) {}
    }
    return { File };
  });
  const { Spec } = require('./spec');
  const { File } = require('./file');
  const spec = new Spec(new File());
  const parseSpy = jest.spyOn(Spec.prototype, 'parse').mockImplementation(function(this: File) {
    return this;
  });
  await spec.write('content');
  expect(parseSpy).toHaveBeenCalledTimes(1);
});

/* Generated by @n1k1t/unit-generator */
it('refresh calls parent refresh', async () => {
  const instance = Object.create(Spec.prototype) as Spec;
  const superRefresh = jest.spyOn(File.prototype, 'refresh').mockImplementation(async () => {});
  const parseSpy = jest.spyOn(Spec.prototype, 'parse').mockReturnThis();
  await instance.refresh();
  expect(superRefresh).toHaveBeenCalled();
});

/* Generated by @n1k1t/unit-generator */
it('refresh calls parse', async () => {
  const instance = Object.create(Spec.prototype) as Spec;
  jest.spyOn(File.prototype, 'refresh').mockImplementation(async () => {});
  const parseSpy = jest.spyOn(Spec.prototype, 'parse').mockReturnThis();
  await instance.refresh();
  expect(parseSpy).toHaveBeenCalled();
});
