import { Spec } from './spec';
import { File } from './file';

/* Generated by @n1k1t/unit-generator */
it('should parse empty content without error', async () => {
  const file = new File({
    cwd: process.cwd(),
    lang: 'ts',
    path: 'test.ts',
    content: '',
  });
  const spec = new Spec(file);
  expect(spec.parse()).toBe(spec);
});

/* Generated by @n1k1t/unit-generator */
it('should extract imports from require statements', async () => {
  const content = "const fs = require('fs');";
  const file = new File({
    cwd: process.cwd(),
    lang: 'ts',
    path: 'test.ts',
    content,
  });
  const spec = new Spec(file);
  spec.parse();
  expect(spec.imports).toContain("const fs = require('fs');");
});

/* Generated by @n1k1t/unit-generator */
it('should extract function declarations as helpers', async () => {
  const content = 'function helper() {}';
  const file = new File({
    cwd: process.cwd(),
    lang: 'ts',
    path: 'test.ts',
    content,
  });
  const spec = new Spec(file);
  spec.parse();
  expect(spec.helpers).toContain('function helper() {}');
});

/* Generated by @n1k1t/unit-generator */
it('should extract tests from it blocks', async () => {
  const content = "it('test title', () => {});";
  const file = new File({
    cwd: process.cwd(),
    lang: 'ts',
    path: 'test.ts',
    content,
  });
  const spec = new Spec(file);
  spec.parse();
  expect(spec.tests[0].title).toBe('test title');
});

/* Generated by @n1k1t/unit-generator */
it('parse assigns empty collections when parsing fails', () => {
  const spec = new Spec({
    cwd: '',
    path: 'spec.ts',
    content: 'invalid(',
    lang: 'ts',
  } as File);

  spec.parse();

  expect(spec.tests).toHaveLength(0);
});

/* Generated by @n1k1t/unit-generator */
it('parse collects an import declaration', () => {
  const spec = new Spec({
    cwd: '',
    path: 'spec.ts',
    content: "import value from 'pkg';",
    lang: 'ts',
  } as File);

  spec.parse();

  expect(spec.imports).toHaveLength(1);
});

/* Generated by @n1k1t/unit-generator */
it('parse collects a function declaration as a helper', () => {
  const spec = new Spec({
    cwd: '',
    path: 'spec.ts',
    content: 'function helper() {}',
    lang: 'ts',
  } as File);

  spec.parse();

  expect(spec.helpers).toHaveLength(1);
});

/* Generated by @n1k1t/unit-generator */
it('parse collects a require variable declaration as an import', () => {
  const spec = new Spec({
    cwd: '',
    path: 'spec.ts',
    content: "const value = require('pkg');",
    lang: 'ts',
  } as File);

  spec.parse();

  expect(spec.imports).toHaveLength(1);
});

/* Generated by @n1k1t/unit-generator */
it('parse collects a non-require variable declaration as a helper', () => {
  const spec = new Spec({
    cwd: '',
    path: 'spec.ts',
    content: 'const value = createValue();',
    lang: 'ts',
  } as File);

  spec.parse();

  expect(spec.helpers).toHaveLength(1);
});

/* Generated by @n1k1t/unit-generator */
it('parse extracts a top-level it title', () => {
  const spec = new Spec({
    cwd: '',
    path: 'spec.ts',
    content: "it('title', () => {});",
    lang: 'ts',
  } as File);

  spec.parse();

  expect(spec.tests[0].title).toBe('title');
});

/* Generated by @n1k1t/unit-generator */
it('parse extracts a nested describe title', () => {
  const spec = new Spec({
    cwd: '',
    path: 'spec.ts',
    content: "describe('group', () => { it('title', () => {}); });",
    lang: 'ts',
  } as File);

  spec.parse();

  expect(spec.tests[0].title).toBe('group.title');
});

/* Generated by @n1k1t/unit-generator */
it('write reparses after writing content', async () => {
  const spec = new Spec({
    cwd: '',
    path: 'spec.ts',
    content: '',
    lang: 'ts',
  } as File);

  const writeSpy = jest
    .spyOn(File.prototype, 'write')
    .mockResolvedValue(undefined as void);
  const parseSpy = jest.spyOn(spec, 'parse');

  await spec.write("it('title', () => {});");

  expect(parseSpy).toHaveBeenCalled();
});

/* Generated by @n1k1t/unit-generator */
it('refresh reparses after refreshing content', async () => {
  const spec = new Spec({
    cwd: '',
    path: 'spec.ts',
    content: '',
    lang: 'ts',
  } as File);

  const refreshSpy = jest
    .spyOn(File.prototype, 'refresh')
    .mockResolvedValue(undefined as void);
  const parseSpy = jest.spyOn(spec, 'parse');

  await spec.refresh();

  expect(parseSpy).toHaveBeenCalled();
});

/* Generated by @n1k1t/unit-generator */
it('build parses the file returned by File.build', async () => {
  jest.spyOn(File, 'build').mockResolvedValue({
    cwd: '',
    path: 'spec.ts',
    content: "it('title', () => {});",
    lang: 'ts',
  } as File);

  const spec = await Spec.build('location');

  expect(spec.tests).toHaveLength(1);
});
