import dotenv from 'dotenv';

const config = dotenv.config();

export default {
  key: config.parsed?.UNIT_GENERATOR_API_KEY,
  url: config.parsed?.UNIT_GENERATOR_API_URL,

  model: config.parsed?.UNIT_GENERATOR_MODEL ?? 'gemini-flash-latest',
  provider: config.parsed?.UNIT_GENERATOR_PROVIDER,

  command: config.parsed?.UNIT_GENERATOR_TEST_COMMAND ?? 'npm test',
  cobertura: config.parsed?.UNIT_GENERATOR_COBERTURA_PATH ?? 'coverage/cobertura-coverage.xml',

  iterations: Number(config.parsed?.UNIT_GENERATOR_MAX_ITERATIONS ?? 5),
  target: Number(config.parsed?.UNIT_GENERATOR_COVERAGE_TARGET ?? 0.8),

  marker: config.parsed?.UNIT_GENERATOR_MARKER ?? '/* Generated by @n1k1t/unit-generator */',

  parallel: Boolean(JSON.parse(config.parsed?.UNIT_GENERATOR_PARALLEL ?? 'true')),
  debug: Boolean(JSON.parse(config.parsed?.UNIT_GENERATOR_DEBUG ?? 'false')),

  langfuse: {
    url: config.parsed?.LANGFUSE_BASE_URL,

    keys: {
      public: config.parsed?.LANGFUSE_PUBLIC_KEY,
      secret: config.parsed?.LANGFUSE_SECRET_KEY,
    },
  },
};
