import dotenv from 'dotenv';

interface IExtractOverload {
  <T extends string>(name: string, fallback: NoInfer<T>): T;
  <T extends string>(name: string): T | undefined;
}

const config = dotenv.config();

const extract = <IExtractOverload>((name: string, fallback: unknown) => {
  if (config.parsed?.[name]?.length) {
    return config.parsed[name];
  }
  if (process.env[name]?.length) {
    return process.env[name];
  }

  return fallback;
});

export default {
  key: extract('UNIT_GENERATOR_API_KEY'),
  url: extract('UNIT_GENERATOR_API_URL'),

  model: extract('UNIT_GENERATOR_MODEL') ?? 'gemini-flash-latest',
  provider: extract('UNIT_GENERATOR_PROVIDER'),

  command: extract('UNIT_GENERATOR_TEST_COMMAND') ?? 'npm test',
  cobertura: extract('UNIT_GENERATOR_COBERTURA_PATH') ?? 'coverage/cobertura-coverage.xml',

  iterations: Number(extract('UNIT_GENERATOR_MAX_ITERATIONS') ?? 5),
  target: Number(extract('UNIT_GENERATOR_COVERAGE_TARGET') ?? 0.8),

  marker: extract('UNIT_GENERATOR_MARKER') ?? '/* Generated by @n1k1t/unit-generator */',

  parallel: Boolean(JSON.parse(extract('UNIT_GENERATOR_PARALLEL') ?? 'true')),
  debug: Boolean(JSON.parse(extract('UNIT_GENERATOR_DEBUG') ?? 'false')),

  langfuse: {
    url: extract('LANGFUSE_BASE_URL'),

    keys: {
      public: extract('LANGFUSE_PUBLIC_KEY'),
      secret: extract('LANGFUSE_SECRET_KEY'),
    },
  },
};
