import * as index from './index';

/* Generated by @n1k1t/unit-generator */
it('exports should be an object', () => {
  expect(typeof index).toEqual('object');
});

/* Generated by @n1k1t/unit-generator */
it('index should not have a default export', () => {
  expect(Object.prototype.hasOwnProperty.call(index, 'default')).toEqual(false);
});
