import { buildCounter, cast, wait } from './utils';

/* Generated by @n1k1t/unit-generator */
it('should create a counter with default initial value 0 and step 1', () => {
  const counter = buildCounter()
  expect(counter()).toEqual(1)
})

/* Generated by @n1k1t/unit-generator */
it('should create a counter with custom initial value', () => {
  const counter = buildCounter(5)
  expect(counter()).toEqual(6)
})

/* Generated by @n1k1t/unit-generator */
it('should create a counter with custom initial value and step', () => {
  const counter = buildCounter(10, 2)
  expect(counter()).toEqual(12)
})

/* Generated by @n1k1t/unit-generator */
it('should increment counter by custom value', () => {
  const counter = buildCounter(5)
  expect(counter(3)).toEqual(8)
})

/* Generated by @n1k1t/unit-generator */
it('should maintain state between calls', () => {
  const counter = buildCounter(0)
  counter()
  expect(counter()).toEqual(2)
})

/* Generated by @n1k1t/unit-generator */
it('should handle negative initial value', () => {
  const counter = buildCounter(-5)
  expect(counter()).toEqual(-4)
})

/* Generated by @n1k1t/unit-generator */
it('should handle negative step value', () => {
  const counter = buildCounter(10, -2)
  expect(counter()).toEqual(8)
})

/* Generated by @n1k1t/unit-generator */
it('should return the same value passed to cast function', () => {
  const value = 'test'
  expect(cast(value)).toEqual('test')
})

/* Generated by @n1k1t/unit-generator */
it('should cast number value', () => {
  const value = 42
  expect(cast(value)).toEqual(42)
})

/* Generated by @n1k1t/unit-generator */
it('should cast object value', () => {
  const value = { key: 'value' }
  expect(cast(value)).toEqual({ key: 'value' })
})

/* Generated by @n1k1t/unit-generator */
it('should cast array value', () => {
  const value = [1, 2, 3]
  expect(cast(value)).toEqual([1, 2, 3])
})

/* Generated by @n1k1t/unit-generator */
it('should cast null value', () => {
  const value = null
  expect(cast(value)).toEqual(null)
})

/* Generated by @n1k1t/unit-generator */
it('should return a promise from wait function', () => {
  const result = wait(100)
  expect(result).toBeInstanceOf(Promise)
})

/* Generated by @n1k1t/unit-generator */
it('should have value property equal to ms parameter', () => {
  const result = wait(500)
  expect(result.value).toEqual(500)
})

/* Generated by @n1k1t/unit-generator */
it('should have abort method', () => {
  const result = wait(100)
  expect(typeof result.abort).toEqual('function')
})

/* Generated by @n1k1t/unit-generator */
it('should resolve after specified time', async () => {
  const start = Date.now()
  await wait(50)
  const elapsed = Date.now() - start
  expect(elapsed).toBeGreaterThanOrEqual(45)
})
