import { ContentFactory } from './factory';

/* Generated by @n1k1t/unit-generator */
it('creates plain content from markdown payload', () => {
  const factory = ContentFactory.build();
  const plain = factory.plain('# Header');

  expect(plain.type).toEqual('plain');
})

/* Generated by @n1k1t/unit-generator */
it('creates rules content from list of strings', () => {
  const factory = ContentFactory.build();
  const rules = factory.rules(['Rule 1', 'Rule 2']);

  expect(rules.type).toEqual('rules');
})

/* Generated by @n1k1t/unit-generator */
it('creates tasks content from list of strings', () => {
  const factory = ContentFactory.build();
  const tasks = factory.tasks(['Task 1']);

  expect(tasks.type).toEqual('tasks');
})

/* Generated by @n1k1t/unit-generator */
it('creates sources links content for provided schema array', () => {
  const factory = ContentFactory.build();
  const sources = factory.sources([
    {
      title: 'Example',
      url: 'https://example.com',
    },
  ] as any);

  expect(sources.type).toEqual('sources');
})

/* Generated by @n1k1t/unit-generator */
it('ContentFactory.is recognizes content instance by type', () => {
  const factory = ContentFactory.build();
  const plain = factory.plain('Hello');

  const result = ContentFactory.is('plain', plain);

  expect(result).toEqual(true);
})
